= Interlingue Course in 10 Lessons
:author: Marcos Cruz (programandala.net)
:revdate: 2020-04-02
:toc:
:toc-title: Contents/Contenete

// This file is part of project
// _Interlingue Course in 10 Lessons_
//
// by Marcos Cruz (programandala.net)
// http://ne.alinome.net
//
// This file is in Asciidoctor format
// (http//asciidoctor.org)
//
// Last modified 202004021445

// English {{{1
== English

// Abouth this project {{{2
=== Abouth this project

Goal:: Make an e-book version of _Occidental Course in 10 Lessons_,
the English version of _Okzidental-Kursus in 10 Lektionen_ (by Mag.
phil. A.Z. Ramstedt, 1929), translated into English, updated and
edited by Dave MacLeod in 2018-2019 in
http://cosmoglotta.pbworks.com[cosmoglotta.pbworks.com].

Author:: Marcos Cruz, 2019, 2020.

Website:: http://ne.alinome.net[ne.alinome.net].

// How to build the book {{{2
=== How to build the book

If you cannot wait for the release of the next version, you can convert the
source files yourself.

First, make sure the programs listed under the "Requirements" section
of the <Makefile> file are installed in your system.

Then enter the project's directory and give the `make` command as
follows:

|===
| Command             | Effect

| make                | Convert into the *recommended formats*
| make all            | Convert into all of the formats (even experimental or with issues)
| make dbk            | Convert into DocBook
| make epub           | Convert into EPUB (all variants)
| make epubd          | Convert into *EPUB with Asciidoctor EPUB3 (recommended)*
| make epubd          | Convert into EPUB with dbtoepub
| make epubp          | Convert into EPUB with Pandoc
| make epubx          | Convert into EPUB with xsltproc (equivalent to dbtoepub)
| make html           | Convert into HTML (all variants)
| make htmlap         | Convert into HTML with Asciidoctor (plain variant, without styles)
| make htmlas         | Convert into HTML with Asciidoctor (stylish variant)
| make htmlpb         | Convert into HTML with Pandoc (body only)
| make htmlpc         | Convert into HTML with Pandoc (complete)
| make odt            | Convert into OpenDocument
| make pdf            | Convert into PDF (both sizes)
| make pdfa4          | Convert into *PDF (DIN A4 size) (recommended)*
| make pdfl           | Convert into *PDF (letter size) (recommended)*
|===

The documents are built in the <target> directory.

// Names of the target files {{{2
=== Names of the target files

When all target files are built (as included in the GitHub releases and in the
corresponding archives downloadable from
http://ne.alinome.net[ne.alinome.net]), the contents of the <target> directory
are the following:

- interlingue_course_in_10_lessons.adoc._a4.pdf
- interlingue_course_in_10_lessons.adoc._letter.pdf
- interlingue_course_in_10_lessons.adoc._plain.html
- interlingue_course_in_10_lessons.adoc._stylish.html
- interlingue_course_in_10_lessons.adoc.dbk
- interlingue_course_in_10_lessons.adoc.dbk.dbtoepub.epub
- interlingue_course_in_10_lessons.adoc.dbk.pandoc._body.html
- interlingue_course_in_10_lessons.adoc.dbk.pandoc._complete.html
- interlingue_course_in_10_lessons.adoc.dbk.pandoc.epub
- interlingue_course_in_10_lessons.adoc.dbk.pandoc.odt
- interlingue_course_in_10_lessons.adoc.dbk.xsltproc.epub

The names are self-explanatory: They indicate the format conversion process
from the http://asciidoctor.org[Asciidoctor] source document, the converters
used and the style or size variants of the final formats (DocBook, EPUB, HTML,
OpenDocument and PDF). Beside, this naming convention prevents name clashes in
the future, if more tools or formats are added to the project.

NOTE: Four converters are used to build the EPUB files. Those built by dbtoepub
and xsltproc are virtually identical, but both of them are included just in
case. Perhaps any of the variants gives better results on your reader.

// Interlingue {{{1
== Interlingue

// Pri ti projecte {{{2
=== Pri ti projecte

Scope:: Crear un libre digital de _Occidental Course in 10 Lessons_,
li anglesi version de _Okzidental-Kursus in 10 Lektionen_ (de Mag.
phil. A.Z. Ramstedt, 1929), traductet in anglesi, actualisat e
redactet de Dave MacLeod in 2018-2019 in
http://cosmoglotta.pbworks.com[cosmoglotta.pbworks.com].

Autor:: Marcos Cruz, 2019.

Web-loc:: http://ne.alinome.net[ne.alinome.net].

// Qualmen constructer li libre {{{2
=== Qualmen constructer li libre

Si vu ne posse atender li liberation del sequent version, vu self
posse converter li documentes fontal.

In prim, ples confirmar que li programas listat in li section
«Requirements» (besones) del document <Makefile> es instalat in vor
sistema.

Tande ples intrar li documentiere del projecte e comandar `make` secun lu
sequent:

|===
| Comande             | Efecte

| make                | Converter in li *formates recomandat*
| make all            | Converter in omni formates e variantes (mem tis experimental o con problemas)
| make dbk            | Converter in DocBook
| make epub           | Converter in EPUB (omni variantes)
| make epuba          | Converter in *EPUB per Asciidoctor EPUB3 (recomandat)*
| make epubd          | Converter in EPUB per dbtoepub
| make epubp          | Converter in EPUB per Pandoc
| make epubx          | Converter in EPUB per xsltproc (equivalent a dbtoepub)
| make html           | Converter in HTML (omni variantes)
| make htmlap         | Converter in HTML per Asciidoctor (crud variante, sin stiles)
| make htmlas         | Converter in HTML per Asciidoctor (stilisat variante)
| make htmlpb         | Converter in HTML per Pandoc (solmen li córpore)
| make htmlpc         | Converter in HTML per Pandoc (complet)
| make odt            | Converter in OpenDocument
| make pdf            | Converter in PDF (ambi grandores)
| make pdfa4          | Converter in *PDF con grandore DIN A4 (recomandat)*
| make pdfl           | Converter in *PDF con grandore «letter» (recomandat)*
|===

Li documentes es creat in li documentiere <target>.

// Nómines del documentes final {{{2
=== Nómines del documentes final

Quande omni documentes final es constructet (talmen anc contenet in e li
liberaturas che GitHub e li archives descargabil ex
http://ne.alinome.net[ne.alinome.net]), li contenete del documentiere <target>
es ti:

- interlingue_course_in_10_lessons.adoc._a4.pdf
- interlingue_course_in_10_lessons.adoc._letter.pdf
- interlingue_course_in_10_lessons.adoc._plain.html
- interlingue_course_in_10_lessons.adoc._stylish.html
- interlingue_course_in_10_lessons.adoc.dbk
- interlingue_course_in_10_lessons.adoc.dbk.dbtoepub.epub
- interlingue_course_in_10_lessons.adoc.dbk.pandoc._body.html
- interlingue_course_in_10_lessons.adoc.dbk.pandoc._complete.html
- interlingue_course_in_10_lessons.adoc.dbk.pandoc.epub
- interlingue_course_in_10_lessons.adoc.dbk.pandoc.odt
- interlingue_course_in_10_lessons.adoc.dbk.xsltproc.epub

Li nómines es self-explicatori: Ili indica li operation de conversion de
formates ex li documente fontal de http://asciidoctor.org[Asciidoctor], li
convertores usat e li variantes de stil o grandore por li formates final
(DocBook, EPUB, HTML, OpenDocument e PDF). Ultra to, ti convention nominal
prevente futur colisiones de nómines, si plu convertores o formates vel esser
adjuntet al projecte.

NOTE: Quar convertores es usat por constructer li documentes EPUB. Tis
constructet per dbtoepub e xsltproc es virtualmen identic, ma ambi es includet
por un possibil beson. Fórsan alcun ex li variantes functiona plu bon in vor
libre-letor.
