= Interlingue Course in 10 Lessons
:author: Mag. phil. A.Z. Ramstedt
:revnumber: 0.2.0-dev.6+20190408
:version-label: Digital edition version
:description: A course of the international auxiliary language Interlingue in 10 lessons
:lang: en
// :sectnumlevels: 3
ifdef::backend-pdf[]
:doctype: book
:toc: auto
:toclevels: 5
:toc-title: Contenete
endif::[]

// This file is part of project
// _Interlingue Course in 10 Lessons_
//
// by Marcos Cruz (programandala.net)
// http://ne.alinome.net
//
// This file is in Asciidoctor format
// (http//asciidoctor.org)
//
// Last modified 201904081222

:dot: .

// :sectnums!:

// About this book {{{1
== About this book

// XXX FIXED -- "Helsinki" -> "Helsingfors" (beside, Cosmoglotta
// always mentions it as his town)

Author:: Mag. phil. A.Z. Ramstedt, Helsingfors.

Original title in German:: Okzidental-Kursus in 10 Lektionen.

Original publisher:: Occidental-Buró Berlin, 1929.

Transcription of the original contents:: Thomas Schmidt, 2006.
Available in http://interlingue.narod.ru/[interlingue.narod.ru] and
http://ie-munde.com[ie-munde.com].

English translation, orthographic modernization and new additions::
Dave MacLeod, 2019.  Title: Occidental Course in 10 Lessons (English
translation).  Available in
http://cosmoglotta.pbworks.com[cosmoglotta.pbworks.com (wiki)] and
https://drive.google.com/file/d/1gelftqO9zPPi0KUkqdjOjikax2O1GvBL/view[drive.google.com
(PDF format)].

Revision and e-book edition:: Marcos Cruz, 2019.  Available in
http://ne.alinome.net[ne.alinome.net] in EPUB, PDF and other formats.

Main changes in this edition::

- All errors and typos found have been fixed.
- In order to make the contents more legible in any format, the layout
  of tables, lists, notes, block quotes, etc. has been modified.
- For easier consulting, vocabulary tables have been converted to
  alphabetic lists, and the notation has been homogenized.

// Some changes and improvements are unfinished yet. See the
// http://github.com/ne-alinome/interlingue-course-in-10-lessons/blob/master/TO-DO.adoc[to-do
// list in the project repository] for details.

Edition made only by libre programs:: 
http://asciidoctor.org[Asciidoctor],
https://github.com/asciidoctor/asciidoctor-pdf[asciidoctor-pdf],
dbtoepub,
http://debian.org[Debian],
http://git-scm.com/[Git],
https://www.gnu.org/software/make/[GNU make],
http://pandoc.org[pandoc],
http://http://jonas.nitro.dk/tig[Tig],
http://vim.org[Vim],
http://xmlsoft.org/XSLT/[xsltproc]...

Version of this edition:: {revnumber}.

Contributions:: Corrections and suggestions for next versions are
welcome at http://ne.alinome.net[ne.alinome.net].

NOTE: The name of Interlingue was "`Occidental`" until 1949.

// Pronunciation and accent {{{1
== Pronunciation and accent

Interlingue is written with the 26 Latin letters. The letters of the
alphabet are pronounced as _a, be, ce, de, e, ef, ge, ha, i, jot, ka,
el, em, en, o, pe, qu, er, es, te, u, ve, duplic ve, ix, ypsilon, and
zet_.

// Pronunciation {{{2
=== Pronunciation

The vowels "`a`", "`e`", "`i`", "`o`" , and "`u`" have a continental
pronunciation, as in German, Italian and Spanish, and are all sounded:

a:: father
e:: bed, yes
i:: machine
o:: door, hot
u:: rule, pull

All <<_stress,unstressed vowels>> are short. Stressed vowels can be lengthened
if they are not followed by a doubled consonant.

A strict rule on the long or short, closed or open pronunciation of the vowels
does not exist. Pronunciations similar to German, Italian or Spanish are
preferable.

The "`y`" (initial and medial) are pronounced as in "`yes`", "`ey`"
(final) as in "`they`", and "`eu`" as "`éh-oo`".

The consonants are pronounced as in English, with the following exceptions:

c::

When before "`e`" and "`i`" = [ts]: *cive*, *helice*.  Elsewhere "`c`"
is hard as in "`can`".

ch::

[ʃ], English "`sh`": *chambre*.

g::

When before "`e`" and "`i`" = [ʒ], French "`j`", or English "`s`" in
"`pleasure`": *plage*, *giraffe*. Elsewhere "`g`" is hard as in
"`go`".

j::

[ʒ], French "`j`", or English "`s`" in "`pleasure`".

s::

Between vowels = [z]: *rose*, *positiv*.

ss::

[s] as in "`pass`".

t::

When followed by "`ia`", "`io`", "`iu`", or "`ie`" and
not preceded by an "`s`" = [ts]:  *nation*. Elsewhere as [t]:
*bastion*.

z::

[dz].

zz::

[ts].

Other doubled consonants are pronounced as a single consonant, unless
when separated they would be pronounced differently. Ex. *grammatica*
is pronounced as if written *gramatica*, but *occidental* and
*suggestion* are pronounced as if written as "`oc`" followed by
"`cidental`", and "`sug`" followed by "`gestion`".

// Stress {{{2
=== Stress

// XXX TODO -- Use uppercase to mark the stress.

// XXX FIXME -- Effect of exception endings.

// XXX TODO -- Add example of plural with "-s".

- Words are generally stressed on the vowel before the final
  consonant: *intercal__ar__*, *par__ol__*, *__for__me*.
- Pluralizing a noun does not change the stress: *par__ol__es*,
  *__for__mes*.
- The endings *-bil*, *-ic*, *-im*, *-ul* and *-um* do not change the
  stress (even when more than one is present in a single word), nor
  does the adverbial ending *-men*: *ra__pid__men*, *__dup__lic*,
  *bon__iss__im*, *__sin__gul*, *poss__i__bil*, *__max__imum*,
  *sta__tis__ticas*.
- Two vowels together are diphthongized and do not count as two
  syllables for the purpose of stress: *fa__mil__ie*, *po__ten__tie*,
  unless the word is a single consonant or consonant cluster followed
  by two vowels: *d__i__e*, *d__e__o*. Compound words are stressed
  based on the last word in the compound: *hod__i__e*, *substr__a__e*.
- In cases where the accent is irregular, it is indicated by an
  accent: *caf__é__*, *__ín__possibil*, *numer__ó__*, *n__ú__mere*,
  *felicit__á__*.

// :sectnums:

// Unesim letion {{{1
== Unesim letion

// XXX FIXED -- Texte -> Textus (in all headings)

// Textus {{{2
=== Textus

// Un international congress {{{3
==== Un international congress

// XXX FIXED -- "symbol" (old orthography) -> "simbol"

// XXX FIXED -- "correspondentes" (old orthography) -> "corespondentes"

Noi have un grand international congress in li cité. Li nationes de
Europa es representat per eminent cultural persones. Li centre del
congress es in li palace del parlament. Elegant modern automobiles sta
ante li portas e sur li stradas e plazzas. Li fassades es decorat per li
national flaggas. Li flaggas del nordic landes have li cruce quam
simbol. On vide delegationes de divers partes de Europa, de nord e sud,
de ost e west. Un deputation visita li presidente del state in li
grandiosi residentie contra li ópera. Special corespondentes fa
observationes e scri articules por li redactiones de grand jurnales e
telegrafa al burós de information.

// XXX FIXED -- "official" (old orthography) -> "oficial"

// XXX FIXED -- "applaude" (old orthography) -> "aplaude"

In li grand sala del palace es li general convent. In li micri chambres
li special comissiones e comités have secret conferenties. Nu li
oficial programma comensa. Li
borgomastre del cité saluta li congressantes. On electe un presidente.
Du secretarios scri li protocolles. Un delegat del central states
presenta un proposition pri li organisation del international trafic per
aeroplanes. Li orator parla con fascinant eloquentie e li auditoria
escuta con interesse e aplaude con entusiasme. Un polemic debatte
comensa e it fini per un resolution in favor al propositor. On accepta
li proposition e refusa li contrapropositiones.

// XXX FIXED -- "corridores" (old orthography) -> "coridores"

In li vestibules e corridores sta gruppes de persones, famosi
professores de universitás, rich directores de commercial firmas,
energic secretarios de social e professional organisationes, e militares
in gala-uniformes. Ili have portafolias con documentes e actes e
discusse li actual situation e international aferes.

// Vocabularium {{{4
===== Vocabularium

- *afere* = affair               
- *ante li portas* = in front of the doors
- *cité* = city                 
- *con* = with                 
- *contra* = against              
- *cruce* = cross                
- *discusse* = discuss              
- *eloquentie* = eloquence
- *escuta* = listen               
- *fa* = do
- *famosi* = famous               
- *fascinant* = fascinating
- *fini* = finishes             
- *grand* = large                
- *ili* = they
- *letion* = lesson
- *on vide* = one sees             
- *parla* = talks
- *parte* = part                 
- *per* = through, by
- *por* = for
- *portafolies* = briefcases
- *propositor* = proposer             
- *quam* = as                   
- *residentie* = residence
- *sala* = room
- *scri* = write
- *sta* = stand(s) (verbal form)
- *star* = to stand
- *visita* = visit(s) (verbal form)
- *visitar* = to visit
- *unesim* = first

// Li macules in li sole {{{3
==== Li macules in li sole

Un yun monaco sede in un turre e observa interessat li sole tra un
telescope. Per hasard il fa un sensational observation: it existe
macules in li sole. Il hasta al prior del monastere e exclama:

"`Patre, qui nu posse esser sin macules, nam mem li sole have
macules.`"

Ma li prior responde tranquilmen:

// XXX FIXED -- "mentionapri"

// XXX FIXED -- "till" (old orthographie) -> "til" (several cases in
// the text)

"`Tu erra, mi filio. Yo ha leet Aristóteles multvez, de comensa til
fine, e necú il mentiona pri macules in li sole. Tui ocules have
macules, e ne li sole.`"

// Vocabularium {{{4
===== Vocabularium

- *esser* = to be
- *exclama* = exclaims
- *hasard* = chance
- *hasta* = rushes (lit. hastes)
- *macul* = spot
- *mem* = even
- *mentiona* = mentions (verbal form)
- *mentionar* = to mention
- *mi filio* = my son
- *monastere* = monastery
- *multvez* = many times
- *nam* = because
- *patre* = father
- *responde* = responds
- *sede* = sits
- *tra* = through
- *tranquilmen* = tranquilly
- *tu erra* = you err (=are wrong)
- *tui ocul* = your eye
- *turre* = tower
- *yo ha leet* = I have read
- *yun monaco* = young monk

// Aforismes {{{3
==== Aforismes

[quote,Edison]
____
Genie es un percent inspiration e ninant nin percent transpiration.
____

// XXX FIXED -- "surrogat" (old orthography) -> "surogat"

[quote, Goethe]
____
Li humore es un del elementes del genie, ma, si it domina, solmen un
surogat de it; it es li compane del diminuent arte e destructe,
anihila it in fine.
____

// XXX FIXED -- "systema" (old orthographie) -> "sistema"

[quote, Hume]
____
Un bon comedie es plu durabil quam un sistema de filosofie.
____

[quote, Pauly]
____
Grand artistes es li sol riches qui divide lor tot felicie con nos.
____

// Vocabularium {{{4
===== Vocabularium

- *compane* = companion
- *destructe* = destroys (verbal form)
- *destructer* = to destroy
- *diminuent* = smaller, diminishing
- *divide* = divide, share (verbal form)
- *divider* = to divide, to share
- *domina* = dominates
- *felicie* = happiness, fortune
- *lor* = their
- *nin* = nine
- *ninant* = ninety
- *nos* = us
- *plu durabil* = more durable
- *quam* = than
- *si* = if
- *sol* = sole, only
- *tot* = entire, whole

// Explanations {{{2
=== Explanations

// XXX FIXED -- Titul: "Explanation" -> "Explanations"

Reading the <<_unesim_letion,first lesson>>, we find that the majority of words in
Interlingue are already long familiar to us. That is, the vocabulary in
Interlingue is largely composed of already-existing international words,
those that most countries in Europe (and of course countries in the
Americas, in Australia, African countries with European languages, etc.)
can already understand, and do not need to learn anew. These
international words are, as we can see through these examples, used in
an "`unmutilated`" form. But, — and this is what makes Interlingue unique —
in the language they are not foreign loanwords, but entirely regularly
composed and derived from international root words, that have been
chosen in such a way that all these completely international and natural
words come into being by themselves. This has never been achieved before
in existing planned world languages.

The word-building system in Interlingue is in fact the same one that is
found in international words, but as we will see later, can be easily
learned and mastered with the help of a few rules.

But it's not just the vocabulary of Interlingue that is natural and easy
to learn; the grammar is also extremely easy thanks to its regularity.

// Article {{{3
==== Article

====
- *un congress* = a congress
- *un lampe* = a lamp
- *li congress* = the congress
- *li lampe* = the lamp
====

There is no grammatical gender in Interlingue. *Un* is the indefinite
article (a/an), and does not decline (change form).

*Li* is the definite article (the), which also does not decline.

// Singular and plural {{{3
==== Singular and plural

// XXX FIXED -- "Dictionnarium(s)" -> "Dictionarium(s)"

====
- *genie* = genius
- *genies* = geniuses
- *congress* = congress
- *congresses* = congresses
- *lampe* = lamp
- *lampes* = lamps
- *suc* = juice
- *sucs* = juices
- *dictionarium* = dictionary
- *dictionariums* = dictionaries
====

Plural is formed with an *-s*, *-es* after a consonant. Some consonant
endings such as "`g`", "`um`", "`c`" only add an *-s* for phonetic reasons.

// Cases {{{3
==== Cases

====
- *de un congress* = of a congress
- *a un congress* = to a congress
- *del congress* = of the congress
- *al congress* = to the congress
====

For the definite article (the), *a*{nbsp}+ *li* is abbreviated to *al*
and *de*{nbsp}+ *il* to *del*.

// Adjectives {{{3
==== Adjectives

====
- *un modern automobil* = a modern automobile
- *du modern automobiles* = two modern automobiles
====

Adjectives in Interlingue do not decline for gender, number or case.

// Persons {{{3
==== Persons

While verbs in English conjugate depending on the person and number,
they do not in Interlingue.

|===
| *yo have*   | I have            | *yo es*   | I am
| *tu have*   | you have          | *tu es*   | you are
| *il have*   | he has            | *il es*   | he is
| *ella have* | she has           | *essa es* | she is
| *it have*   | it has            | *it es*   | it es
| *noi have*  | we have           | *noi es*  | we are
| *vu have*   | you (plural) have | *vu es*   | you are
| *Vu have*   | you (polite) have | *Vu es*   | you are
| *ili have*  | they have         | *ili es*  | they are
| *on have*   | one has           | *on es*   | one is
|===

// Duesim letion {{{1
== Duesim letion

// Textus {{{2
=== Textus

// Un dialog {{{3
==== Un dialog

Un yun mann promena sur li trottuore de un strada e observa li vive. Il
incontra un amíco, quel saluta le e strax comensa questionar:

"`Bon die, mi amíco. Quo Vu fa nu?`"

"`Yo promena.`"

"`Quo Vu ha fat hodie? Yo ne ha videt Vos ante nu.`"

"`Yo ha laborat.`"

"`Quo Vu fat yer?`"

"`Yo esset in hem e reposat.`"

"`Quo Vu hat fat anteyer, si Vu esset yer tam fatigat?`"

"`Yo hat laborat li tot die e nocte.`"

"`Quo Vu va far deman?`"

"`Yo va scrir un long articul por un jurnal, e yo espera, que yo va har
scrit it til fine posdeman.`"

"`Mey Vu haver success in Vor interprense! Ma it vell esser interessant
saver, pri quo Vu va scrir e por qui Vu va scrir.`"

"`Ci noi ne posse star plu. Noi deve ear.`"

"`Lass nos visitar un café! Ta noi posse seder e trincar un glass de bir
e parlar. O si Vu vole, café o té. Ples venir con me!`"

"`Mersí pro Vor invitation! Ma ples pardonar: pro quo Vu vole saver quo
yo fa, e pri quo e por qui yo scri?`"

"`Pro que un yun mann deve saver omnicos.`"

NOTE: *hodie* as a combination of *ho-*{nbsp}+ *die* is stressed as
*hodíe*, and *omnicos* as a combination of *omni* (all){nbsp}+ *cose*
(thing) is stressed as *omnicós*.  They may be also written as *hodíe*
and *omnicós*.

// XXX FIXED -- "I hope that" -> "I hope that…";
// The original example is confusing, because "that" can be
// also a pronoun.

// Vocabularium {{{4
===== Vocabularium

// XXX FIXED -- Separate "*le strax* = him right away"

// XXX FIXED -- "trottuor" -> "trottuore" (which is the form used in
// the text, and in the "-uore" suffix).

- *amíco* = friend
- *ante nu* = before now
- *bon die* = good day
- *ci* = here
- *deman* = tomorrow
- *dever* = to must
- *duesim* = second
- *ear* = to go
- *esperar* = to hope
- *fatigar* = to tire
- *hodie* = today
- *interprense* = endeavour
- *laborar* = to work
- *le* = him
- *mersí* = thanks
- *ne* = not
- *nocte* = night
- *o* = or
- *omnicos* = everything
- *plu* = more
- *por qui* = for who(m)
- *por* = for
- *posdeman* = the day after tomorrow
- *pri quo* = about what
- *pro que* = because ("`due to that…`")
- *pro quo* = why ("`due to what`")
- *pro* = due to
- *promena* = strolls (cf. promenade)
- *que* = that (as in "`I hope _that_…`")
- *questionar* = to question, to ask
- *quo* = what
- *reposar* = to repose, to rest
- *saver* = to know
- *strax* = right away
- *ta* = there
- *tam* = so
- *trottuore* = sidewalk
- *venir* = to come
- *vive* = life
- *voler* = to want
- *Vor* = your (polite form)
- *Vos* = you (object)
- *yer* = yesterday

// Li furtard e li prestro {{{3
==== Li furtard e li prestro

Un furtard veni a un prestro por confesser su mult peccas e reciver
pardon e absolution. Li prestro sede in su stul e escuta benevolent,
durant que li furtard raconta le pri su trics.

"`Quo tu ha fat, mi filio?`" questiona li prestro. – In li sam moment li
furtard vide, que li prestro porta un fin aurin horloge in un tasca de
su gilete. Il prende it sin que li prestro remarca to.

"`Yo furte,`" li furtard responde.

"`Talmen tu ne deve dir. Ples dir, yo ha furtet!`" – Nu li furtard ja ha
deposit li horloge in su tasca.

"`Yo ha furtet,`" il confirma.

"`Yes, bon, mi filio. Nu tu deve retornar to quo tu ha furtet.`"

"`Esque Vu ne vole haver it?`"

"`No, tu deve dar it al possessor.`"

"`Li possessor ne vole haver it.`"

"`In tal casu, ples departer in pace. Tui peccas es pardonat.`"

// Vocabularium {{{4
===== Vocabularium

// XXX FIXED -- "asked to ask questions" -> "used to ask questions"

- *aurin* = golden
- *casu* = case (circumstance)
- *confesser* = to confess
- *confirmar* = to confirm
- *dar* = to give
- *deposir* = to put in, to deposit
- *dir* = to say
- *durant que* = while
- *esque* = (used to ask questions)
- *fin* = fine
- *furtard* = thief
- *furter* = to steal
- *gilete* = vest
- *horloge* = watch (wristwatch)
- *mult* = much
- *pace* = peace
- *pecca* = sin
- *portar* = to carry
- *possessor* = owner (possessor)
- *prender* = to take
- *prestro* = priest
- *racontar* = to tell
- *reciver* = to receive
- *remarcar to* = notice it
- *retornar* = to return
- *sam* = same
- *su* = his, hers, its
- *tal* = such a
- *talmen* = thus, in that way
- *tasca* = pocket
- *to* = it, that
- *tui* = your (informal)

// Anecdotes {{{3
==== Anecdotes

Li persian legates postulat del Spartanes terra e aqua quam signe de
subjugation. Li Spartanes jettat les in un profund bronn: "`Ta vu have
terra e aqua.`"

Zeno, li filosofo, dit a un querellant yun mann: "`Li natura ha dat nos
du oreles e un bocca, por que noi mey escutar mult e parlar poc.`"

"`Si yo va venir a Laconia, yo va extinter omnicos e omnihom per foy e
gladie,`" scrit Philippos, li rey de Macedonia, al Spartanes. "`Si,`"
respondet li Spartanes.

Un asiatic potentate esset questionat, quel esset su opinion pri li vin.
Il respondet: "`It es un fluide, quel es extraet de lingues de féminas e
cordies de leones, pro que, quande yo ha trincat vin, yo posse parlar
sin cessar e combatter mem li diábol.`"

// Vocabularium {{{4
===== Vocabularium

- *bocca* = mouth
- *cessar* = to stop
- *combatter* = to combat
- *cordie* = heart
- *diábol* = devil
- *extinter* = to extinguish
- *fluide* = fluid
- *foy* = fire
- *fémina* = woman
- *gladie* = sword
- *jettar* = to throw, to toss
- *leon* = lion
- *omnihom* = everyone
- *orel* = ear
- *poc* = little
- *por que* = in order to ("`for that…`")
- *postular* = to demand
- *profund* = deep
- *quel* = which
- *querellar* = to quarrel
- *terra e aqua* = earth and water
- *vin* = wine

// Proverbies {{{3
==== Proverbies

- Mannes fa domes, ma féminas fa hemes.
- Li infante es li patre del mann.
- Plu vu studia, plu vu trova, que vu save necos.
- Aure dat por sanitá, ne es dat in vanitá.
- On ne posse seder sur du stules.
- Errar es homan, pardonar divin.
- Parlar es plu facil quam far.
- Quande li fox predica tolerantie, ples gardar vor ganses.
- Sur un rulant petre moss ne cresce.
- Li morites governa li viventes.
- Bon comensat es demí parat.
- Que sempre es comensant, nequande es finient.
- Mult homes es vocat, ma poc homes es electet.
- Li sapon es li mesura de bon-esser e cultura del state.

// Vocabularium {{{4
===== Vocabularium

- *aure* = gold
- *crescer* = to grow
- *divin* = divine
- *dom* = house
- *du* = two
- *facil* = easy
- *gardar* = to guard
- *hem* = home
- *hom* = person
- *homan* = human
- *in vanitá* = in vain
- *infante* = infant, child
- *morir* = to die
- *necos* = nothing
- *nequande* = never
- *parat* = done
- *petre* = stone
- *predicar* = to preach
- *proverbie* = proverb
- *quande* = when
- *rular* = to roll
- *sanitá* = health
- *sapon* = soap
- *sempre* = always
- *trovar* = to find
- *vocar* = to call

// Explanations {{{2
=== Explanations

// Conjugation {{{3
==== Conjugation

// XXX FIXED -- "as as" -> "as an"

Verbs in Interlingue are all regular (except for the verb "`to be`" (*esser*)
which is written *es* in the present). There is only one conjugation
with four forms. Taking the verbal stem *ama-* (love) as an example we
have the following four forms:
*ama*,
*ama__r__*,
*ama__nt__*,
*ama__t__*.

* *ama* has the following uses:
** Active present indicative (regular present form): *yo ama* = I love,
  *il ama* = he loves, *vu ama* = you love, etc.
** Active present conjunctive: *Il di que il ama* = He says that he
  loves.
** Imperative: *ama*! = love!, *veni*! = come!

* *amar* is the infinitive. *amar* = to love, *venir* = to come,
   *presser* = to press.

* *amant* is the active participle (English "`-ing`"). *amant* = loving,
   *venient* = coming, *pressent* = pressing.

* *amat* has the following uses:
** Perfect participle (i.e. an adjective): *amat* = loved, *venit* =
  come, *presset* = pressed. *Li amat patria* = the (be)loved
  homeland.
** Active indicative preterite (i.e. past tense): *yo amat* = I loved,
  *tu amat* = you loved, *il amat* = he loved, *noi amat* = we loved,
  *ili amat su patria* = they loved their homeland, etc.

The other forms are created with the help of auxiliary verbs.

// Active {{{4
===== Active

// XXX FIXED -- "vant amar" -> "hant amar"

|===
| Perfect            | *yo ha amat*     | I have loved
| Pluperfect         | *yo hat amat*    | I had loved
| Future 1           | *yo va amar*     | I will love
| Future 2           | *yo va har amat* | I will have loved
| Optative           | *yo mey amar*    | I may love
| Conditional        | *yo vell amar*   | I would love
| Precative          | *ples amar!*     | please love!
| Hortative          | *lass nos amar!* | let us love!
| Perfect infinitive | *har amat*       | to have loved
| Future infinitive  | *va amar*        | to will love
| Perfect participle | *hant amat*      | having loved
| Future participle  | *hant amar*      | having to love
|===

*har* resembles *haver* (to have) but is used for verb conjugation,
while *haver* only refers to the verb "`to have`":
  
- *Yo ha venit.* = I have come.
- *Il ha esset.* = He has been.
- *Noi hat curret.* = We had run.
- *Il hat cadet.* = He had fallen.

*Ples* in *ples amar* adds politeness to the imperative, in the same
way as the English "`please`":

- *Ples venir!* = Please come!
- *Veni!* = Come!

// Passive {{{4
===== Passive

|===
| Present            | *yo es amat*         | I am loved
| Preterite          | *yo esset amat*      | I was loved
| Perfect            | *yo ha esset amat*   | I have been loved
| Pluperfect         | *yo hat esset amat*  | I had been loved
| Future 1           | *yo va esser amat*   | I will be loved
| Optative           | *yo mey esser amat*  | may I be loved
| Conditional        | *yo vell esser amat* | I would be loved
| Present infinitive | *esser amat*         | to be loved
| Perfect infinitive | *har esset amat*     | having been loved
| Present participle | *essent amat*        | being loved
|===

// Other forms {{{5
====== Other forms

Using the verb *ear* (to go) adds a sense of continuation (the
construction is going on):

====

- *Li dom ea constructet.* = The house is being built.
- *Li libre eat printat.* = The book was being printed.

====

Using the verb *star* (to stand) adds a sense of finality (the
construction "`stands`" built):

====

- *Li dom sta constructet.* = The house is built.
- *Li libre stat printat.* = The book was printed (the book's printing
  was all done).

====

Using *se* after a verb to make it passive or reflexive (to make it
refer to itself):

====

- *Li jurnal printa se rapidmen.* = The magazine is being quickly
  printed (the magazine "`prints itself`" quickly).
- *Li cose explica se simplicmen.* = It's easy to understand ("`the
  thing explains itself simply`").
- *Yo nómina le Brian.* = I call him Brian.
- *Il nómina se Brian.* = His name is Brian ("`he calls himself
  Brian`").

====

Adding *se* to a verb may also give a sense similar to that in
English:

====

- *Yo procurat un libre.* = I got a book.
- *Yo procurat me un libre.* = I got myself (me) a book.

====

// Progressive form {{{4
===== Progressive form

|===
| Present   | *il es laborant*       | he is working
| Preterite | *il esset laborant*    | he was working
| Perfect   | *il ha esset laborant* | he has been working
|===

The progressive form is used much less often than in English, and is
used to stress the fact that the action is ongoing.

====
- *Il esset laborant quande yo intrat.* = He was working when I entered.
====

It works as an adjective in the same way as in English:

====
- *It va esser un tre fatigant annu.* = It will be a very tiring year
  (from *fatigar*, "`to tire`").
====

// Triesim letion {{{1
== Triesim letion

// Textus {{{2
=== Textus

// Li creation {{{3
==== Li creation

In li Bible sta scrit, que Deo ha *creat* li munde.

Pro to il es nominat li *creator* del munde.

Li *creation* durat six dies.

Noi ne have *creatori* qualitás, solmen Deo es vermen *creativ*.

Quo il ha creat? Nos e omni altri *creaturas*.

// Vocabularium {{{4
===== Vocabularium

- *altri* = other
- *crear* = to create
- *creatori* = "`creator-y`"
- *Deo* = God
- *durar* = to last
- *munde* = world
- *nominar* = to name
- *qualitá* = quality
- *triesim* = third
- *vermen* = truly

// Un brilliant carriera {{{3
==== Un brilliant carriera

Mi fratre have un amíco, un ingeniero, qui ha fat un brilliant carriera.
Ja quam yun studente su aspirationes evocat atention. Pos obligatori
teoretic studies in un technical institute e practic preparatori labores
in un micri fabrica, in quel il laborat quam reparator de electric
motores e transformatores, il recivet un transitori ocupation quam
supervisor del machines in un grand industrial interprense. Mersí a su
intensiv labor e su extraordinari organisatori talentes il avansat
gradualmen, de position a position, e nu il es executiv director de un
association de industries in li sam branche.

Su precessores esset in oposition a innovationes, ma quam successor de
ti conservativ administratores il devet interprender mult reformationes
e un total reorganisation del administration. Li production e vendition
del productes e fabricates crescet enorm in comparation a to, quo ili
esset ante il. Il ha prendet parte in mult negociationes con extran
states, e li resultate ha esset plu e plu extensiv, comercial
transactiones de exportationes e concessiones in exotic landes.

Difamatori lingues di, que il es un poc imperatori, ma to es
exageration. Quande il ha decidet un afere, il es firm in su decision,
ne tolera contradition e intervention, e pro to il have success in su
interprenses. Tal qualificationes es anc absolutmen necessi a decisiv
por un mann in su position.

Il es inventor de mult patentat aparates, queles es ancor in su exclusiv
possession. Quam possessor de grand capitales, il ha fat mult donationes
in favor a cultural institutiones, e pro to il have li reputation de un
grand donator e favorisator del scienties e artes.

// Vocabularium {{{4
===== Vocabularium

- *anc* = also
- *conceder* = to concede
- *difamar* = to speak ill of (cf. defamation)
- *donar* = to give, to donate
- *evocar* = to evoke
- *exagerar* = to exaggerate
- *extender* = to extend
- *extran* = outside, abroad
- *fratre* = brother
- *gradualmen* = gradually
- *imperar* = to order (cf. imperative)
- *innovar* = to innovate
- *intervenir* = to intervene (lit. "`between-come`")
- *ja* = already
- *necessi* = necessary
- *negociar* = to negotiate
- *preceder* = to precede
- *quande* = when
- *succeder* = to succeed (to follow)
- *transacter* = to transact
- *transitori* = transitory
- *vendir* = to sell

// Li eterni problemas {{{3
==== Li eterni problemas

It existe témpores, quande li filosofic speculation sembla haltar in
total o partial resignation ante li grand problemas del vive, quande ne
solmen definitiv ma anc provisori responses al eterni questiones sembla
van. It concentra se a examination e inregistration de ti resultates,
queles li exploratores e laboratores del special scienties presenta. It
es periodes, quande li homan pensa fa quasi un sorte de guerre de
position contra li eterni problemas, un guerre de position, quel postula
mult devot perlaboration de detallies e penetrativ analise.

Ma it existe anc témpores, quande li pensa abandona su timid, defensiv
position, marcha adavan e fa un general atacca. It es tal témpores, pri
queles Hegel ha dit, que "`li universal spíritu fa un choc adavan.`" Con
egal justification on posse nominar les témpores de productiv erras. Tal
periodes seque successiv un pos altri, in ritmic fluctuation quam
sómmites e valleyes de undes.

Pos li potent flut del Renascentie, quel in fin manifestat se in li
grand sistemas, sequet li rationalisme del enciclopedistes e lor
imitatores. Ti rationalisme havet su culmination e su coronation, ma anc
su contra-evolution in Kant, li titane del filosofie. Pos il sequet li
romantica, con nov gigantic constructiones de sistemas.

E denove, pos li romantica, li filosofie devet retirar a su positiones.
Li positivisme detronat li filosofie in favor al special scienties. Li
materialisme devenit li successor de ti sublim, genuin idealistic
spíritu, quel, malgré omni fantastic misprenses, esset li directiv
factor del romantica. Li special scienties fa nov e nov decovritiones,
ma nor spiritual horizonte deveni plu strett.

E nu, esque li signes de nor propri témpore ne da nos indicationes pri
un nov era de filosofic speculation, un nov romantica e idealisme, támen
con plu critic reflection quam li antiqui? Li munde fórsan ne es ancor
tam senil, quam li profetes de fatiga vole far nos creder.

// Vocabularium {{{4
===== Vocabularium

- *abandonar* = to abandon
- *adavan* = forwards
- *choc* = shock
- *coronar* = to crown
- *creder* = to believe
- *culminar* = to culminate
- *defender* = to defend
- *detronar* = to dethrone
- *devenir* = to become
- *devot* = devoted
- *erra* = error
- *eterni* = eternal
- *evoluer* = to evolve
- *explorar* = to explore
- *fatiga* = fatigue
- *fluctuar* = to fluctuate
- *fórsan* = perhaps
- *guerre* = war
- *imitar* = to imitate
- *indicar* = to indicate
- *justificar* = to justify
- *les* = them
- *malgré* = despite
- *misprense* = misunderstanding
- *nor* = our
- *omni* = all
- *penetrar* = to penetrate
- *pensa* = thought
- *pos* = after
- *propri* = own (one's own)
- *Renascentie* = Renaissance
- *retirar* = to retire
- *semblar* = to seem
- *senil* = senile
- *sequer* = to follow
- *spíritu* = spirit
- *strett* = narrow
- *sómmite* = summit
- *ti* = this, that
- *támen* = however
- *témpore* = time
- *unde* = wave
- *van* = in vain

NOTE: *omni* before a singular means "`each`" (same as *chascun*), while
before a plural it means "`all`".

// Anecdotes {{{3
==== Anecdotes

On questionat li filosof Aristippos de Kyrene, per quo li filosofos
distinte se del altri homes. Il respondet: "`Si omni leges vell esser
abrogat, solmen li filosofos vell viver quam antey.`"

Alquí objectet que on frequent incontra li filosofos avan li portas del
riches. Aristippos replicat: "`Sam quam li medicos avan li portas del
malades. Esque pro to li malades es plu reputat quam li medicos?`"

"`Moné,`" il declarat, "`yo prende del riches ne pro que yo besona it, ma
por que ili mey saver in quel maniere ili posse investir it.`"

// Vocabularium {{{4
===== Vocabularium

- *abrogar* = to abrogate, to repeal
- *alquí* = someone
- *antey* = before
- *avan* = before
- *besonar* = to need
- *distinter* = to distinguish
- *in quel maniere* = in which way
- *lege* = law
- *malad* = sick
- *medico* = doctor
- *moné* = money
- *objecter* = to object
- *per quo* = by what
- *plu reputat* = more reputed
- *porta* = door
- *pro to* = that's why
- *replicar* = to reply
- *sam quam* = same as
- *viver* = to live

// Explanations {{{2
=== Explanations

// XXX FIXED -- Text moved to the following subsection and modified,
// instead of running into the title. It seems more legible.

// Suffixes -ion, -or, -ori, -iv, -ura {{{3
==== Suffixes -ion, -or, -ori, -iv, -ura

We have just seen a large number of expressive international words that
end with these five suffixes.
Note that these words in Interlingue are regularly derived from verbs.

The words with <<_ion,*-ion*>>, <<_or,*-or*>>, <<_ori,*-ori*>>,
<<_iv,*-iv*>> and <<_ura,*-ura*>> are created with the perfect stem of
the verb. But dictionaries only give the infinitive of a verb. How do
you find the perfect stem?  This is where we come to the de Wahl's
Rule.

// XXX FIXED -- Completed the previous sentence.  It seems confusing,
// letting the text continue into a title.

// XXX FIXED -- "de Wahl's Rule" -> "The de Wahl's Rule"

// The de Wahl's Rule {{{3
==== The de Wahl's Rule

First remove the *-r* from a verb, or *-er* for an *-er* verb. What is
at the end?

// XXX FIXED -- Moved "extracter" and "distincter" to the third step,
// with the related notes.

1. If it's a vowel, then add a "`t`":
+
|===
| Infinitive                   | Perfect stem   | Derived word

| *decora/r*, decorate         | *decorat-*     | *decoration*
| *defini/r*, define           | *definit-*     | *definition*
| *le/er*, read                | *let-*         | *letion*, reading/lesson
| *devo/er*, to devote         | *devot-*       | *devotion*
| *institu/er*, to institute   | *institut-*    | *institution*
|===

2. If it's a "`d`" or an "`r`", then it becomes "`s`":
+
|===
| Infinitive              | Perfect stem    | Derived word 

| *explod/er*, to explode | *explos-*       | *explosion*
| *adher/er*, to adhere   | *adhes-*        | *adhesion*
| *decid/er*, to decide   | *decis-*        | *decision*
|===

3. If it's a consonant, then you already have the perfect stem.
+
|===
| Infinitive                   | Perfect stem   | Derived word

| *construct/er*, to construct | *construct-*   | *construction*
| *express/er*, to express     | *express-*     | *expression*
| *opin/er*, to opine          | *opin-*        | *opinion*
| *extract/er*, to extract     | *extract-*     | *extraction*
| *distint/er*, to distinguish | *distint-*     | *distintion*, distinction
|===
+
[[_note_about_verb_pairs]]
[NOTE]
--
As in English, Interlingue sometimes has two groupings of verbs
with nearly the same meaning where the more Latin-like one has a more
formal or heavy character. To derive *extraction* above the
verb *extracter* is used, but the verb *extraer* also exists
(lit. *ex-traer*, to pull out), which above would lead
to *extra-er* -> *extrat* -> *extration*. This gives them a slightly
nuanced meaning: an *extraction*, derived from *extracter* (to extract),
is only an *extraction*. But an *extration*, derived from *extraer* (to
pull out), is both a pulling out and an extraction.

Similarly, the word reader (*letor*, from *le/er* -> *let* -> *letor*)
has a "`hidden`" companion in the form of *lecter* that can be seen from
the word *lector* (same meaning in Interlingue as in English) that one
can see derived as *lecter* -> *lect-* -> *lector*. The
word *letion* above can also be written *lection*, which carries a more
formal or pompous meaning. This freedom given to the user to explore the
language oneself is a powerful tool for adding nuance in writing.
--

Five verbs are exceptions to the above and must be learned separately.

|===
| Infinitive        | Perfect stem   | Derived example

| *ceder*, to cede  | *cess-*        | *recession*
| *seder*, to sit   | *sess-*        | *session*
| *tener*, to hold  | *tent-*        | *retention*
| *venir*, to come  | *vent-*        | *intervention*
| *verter*, to wind | *vers-*        | *version*
|===

NOTE: The original de Wahl's Rule included the exception *mover* (to
move) -> *mot-*, from which is derived *motion*. The Interlingue
community noted however that *motion* (plus *emotion*)
and *movement* are semantically different and that using two
verbs *moer* (to move, to budge) and *mover* (to move) would allow
greater precision while doing away with an irregularity. Thus, the word
motion is regularly derived from *mo/er* -> *mot-* -> *motion*.

// Meaning of the suffixes {{{3
==== Meaning of the suffixes

// -ion {{{4
===== -ion

The action, result or location of a verb.

====
- *fabrication*, from *fabricar* (to fabricate)
- *administration*, from *administrar* (to administrate)
- *expedition*, from *expedir* (to send, to expedite)
====

// -or {{{4
===== -or

The acting person, thing or factor of a verb.

====
- *decorator*, from *decorar* (to decorate)
- *fabricator*, from *fabricar*
- *administrator*, from *administrar*
- *expeditor*, from *expedir*
- *compressor*, from *compresser* (to compress)
====

// -ori {{{4
===== -ori

Adjective derived from <<_or,*-or*>> above, similar to English
"`-ory`". Refers to something that is dedicated to or working as:

====

- *un obligatori servicie* = an obligatory service (from *obligar*, to
  obligate)
- *un organisatori talent* = a talent for organization (lit. an
  organisor-y talent; Interlingue allows greater freedom than English
  with such words)
- *un preparatori mesura* = a preparatory measure (from *preparar*, to
  prepare)
- *un transitori stadie* = a transitory stage (from transir, to cross)
- *contraditori propositiones* = contradictory propositions (from
  *contradir*, to contradict)
- *un ilusori pensa* = an illusory thought (from *iluder*, to feint or
  delude)
- *scritori crampe* = writer's cramp (i.e. the cramp of a *scritor*)
- *defensori discurse* = lit. "`defensive discourse`" (e.g. the speech
  on the defendant's side, from *defender*, to defend)

====

// -iv {{{4
===== -iv

English "`-ive`", forms adjectives that denote an active ability:

====

- *un decorativ vase* = a decorative vase (*un decoratori vase* would
  be a vase intended for decoration, but uncertain as to whether it is
  actually decorative or not)
- *un obligativ promesse* = a promise that obligates (*obligatori
  promesse* = an obligatory promise)
- *un explicativ exemple* = an example that explains something
  (*explicar* = to explain)
- *un consolativ response* = a response that brings consolation (*un
  consolatori response* = a response given as consolation) (*consolar*
  = console)
- *un negativ resultate* = a negative result (*negar* = to deny)
- *un instructiv articul* = an instructive article (*instructer* =
  instruct)
- *un decisiv parol* = a decisive word (*decider* = to decide)

====

// -ura {{{4
===== -ura

Similar to English "`-ure`". Forms verbal nouns denoting a concrete,
realized action or its result.

====

- *garnitura* = garnish (the English noun "`garnish`", from *garnir* =
  to garnish)
- *scritura* = writing, scripture (from *scrir* = to write)
- *politura* = polish (the noun "`polish`", from *polir* = to polish)

====

// XXX FIXED -- "to form showing the result" -> "to form the result"

The perfect stem plus an <<_e,*-e*>> (to indicate a noun) is also used
to form the result of the action of a verb:

====

- *tribute* = tribute (from *tribuer*)
- *flute* = flood (from *fluer*)
- *scrite* = writing (also note *manuscrite*, a manuscript, from
  *manu* (hand){nbsp}+ *scrite*)
- *extracte* = extract, from *extracter* (*extrate* for a slightly
  different nuance — see <<_note_about_verb_pairs,note above>>)
- *miscomprense* = misunderstanding (from *miscomprender* =
  misunderstand)

====

// XXX FIXED -- "usage poetry" -> "usage in poetry"

The <<_e,*-e*>> is technically optional but is used for clarity; it may be
removed for euphonic purposes (usage in poetry, to translate colloquial or
informal speech, etc.).

The perfect stem on its own is also used as an adjective:

// XXX FIXED -- Markup of the "un pervers(i)" example:

====

- *un apert fenestre* = an open window (from *aperter* = to open)
  (note the difference between this and *un apertet fenestre* = an
  opened window)
- *un pervers(i) opinion* = a perverse opinion (from *perverter* = to
  pervert) Here again there is a difference between *perversi*
  (perverse) and *pervertet* (perverted).
- *un devot amíco* = a devoted friend (from *devoer* = to devote). In
  cases where no obvious difference exists between the perfect stem
  (*devot*) and the past tense (*devoet*), the two tend to be used
  interchangeably.  One could still imagine however situations where
  choosing one or the other is necessary.

====

NOTE: <<_i,*-i*>>, like <<_e,*-e*>> above, is affixed to show that the
word is an adjective. <<_i,*-i*>> is also optional, and tends to be used most
often when euphony demands it (e.g. the word *micri*, small, could not
be pronounced without it).

NOTE: The perfect stem is used when deriving (forming) words, but
not for verb conjugation. Technically words above such
as *apert*, *pervers(i)* etc. can be learned and thought of as
separate entities but knowing how they are derived from verbs gives the
user of the language a much greater range of options when speaking and
leads to much less looking up of words in the dictionary.

// Quadresim letion {{{1
== Quadresim letion

// Textus {{{2
=== Textus

// Li misterie del cratere in Sall {{{3
==== Li misterie del cratere in Sall

In fine del septembre mill nin cent duant sett (1927) li conosset
geofisico Professor Wegener (de Graz in Austria) visitat un ja de long
conosset, ma per su orígine absolutmen misteriosi cratere in Sall sur li
insul Oesel (Saaremaa), quel apartene al Republica de Estonia. Il esset
in un societé de professores Kraus e Meyer del universitá in Riga e fat
explorationes pri ti fenomen del natura.

In to omni expertes esset unanim til nu, que ci ne acte se pri un
extint vulcan, quam on pensa in circules de laicos. Li max probabil
opinion esset ti, que li cratere es un funel de ruition. Nu professor
Wegener expresset un nov surprisant interpretation del orígine de ti
strangi formation. Il pensa que on have ci un funel de penetration de un
grandissim meteorite, simil al funeles de grenades, queles noi conosse
desde li guerre mundan. Li cratere de Sall have un diametre de du cent
quinant (250) e un profundore de deciquin (15) metres. It sembla esser
un diminuet simil formation quam li famosi Arizona-crater in Nord
America, quel advere have du mill (2000) metres in diametre.

Ma quo es significativ – per forationes on ja ha constatat in quar cent
(400) metres sub li solea del cratere un enorm meteorite de circa mill
du cent (1200) metres in diametre, it es, un córpore de dimensiones de
un micri satellite. Wegener aprecia li grandore del meteorite, quel ha
productet li cratere de Sall, ye circa cent til cent quinant (100 til
150) metres in diametre, e supposi que it deve trovar se in circa
quinant til settant quin (50 til 75) metres de profundore. Adplu it es
remarcabil, que in li vicinitá del principal cratere es situat pluri
simil, ma mult plu micri, funeles, probabilmen causat per partes, queles
ha separat se durant li cadida, quo es sovente observat che li cadidas
de meteorites.

Si li suposition de prof. Wegener es rect, tande li cratere in Sall es
un unic monument de natura in Europa, e li duesim sur li tot globe de
terra.

// Vocabularium {{{4
===== Vocabularium

- *acter* = to act
- *adplu* = furthermore
- *advere* = indeed
- *apertener* = to belong
- *cader* = to fall
- *causar* = to cause
- *circul* = circle
- *conosser* = to know
- *córpore* = body
- *extinter* = to extinguish
- *forar* = to bore, to drill
- *funel* = funnel
- *grandissim* = huge
- *grandore* = size (cf. grandeur)
- *laico* = layperson (i.e. not a specialist)
- *max* = most
- *orígine* = origin
- *penetrar* = to penetrate
- *pluri* = several
- *probabil* = probable
- *producter* = to produce
- *profundore* = depth
- *quadresim* = fourth
- *rect* = right, correct
- *ruir* = to collapse
- *separar* = to separate
- *simil* = similar
- *situat* = situated, located
- *solea* = sole, bottom
- *sovente* = often
- *strangi* = strange
- *suposir* = to suppose
- *tande* = then
- *unanim* = unanimous
- *unic* = unique
- *vicinitá* = vicinity

// Li numerales {{{3
==== Li numerales

Li *cardinal* numerales, queles responde al question *"`quant?`"* es:

// XXX FIXED -- "quar mill sett cent undeci" -> "quar mill sett cent
// deciun"

[cols=">13,<24"]
|===
| 1             | un
| 2             | du
| 3             | tri
| 4             | quar
| 5             | quin
| 6             | six
| 7             | sett
| 8             | ott
| 9             | nin
| 10            | deci
| 11            | deciun
| 12            | decidu
| 13            | decitri
| 14            | deciquar
| 15            | deciquin
| 16            | decisix
| 17            | decisett
| 18            | deciott
| 19            | decinin
| 20            | duant
| 30            | triant
| 31            | triant un
| 40            | quarant
| 50            | quinant
| 60            | sixant
| 70            | settant
| 75            | settant quin
| 80            | ottant
| 90            | ninant
| 100           | cent
| 200           | du cent
| 300           | tri cent
| 400           | quar cent
| 500           | quin cent
| 600           | six cent
| 700           | sett cent
| 800           | ott cent
| 900           | nin cent
| 1000          | mil
| 4711          | quar mill sett cent deciun
| 1 000 000     | un million
| 1 000 000 000 | un milliard
|===

Per adjuntion del suffix *-esim* noi have li *ordinal* numerales,
respondent al question *"`quantesim?`"*:

// XXX FIXED -- Remove duplicated "quantesim" here.

[cols=">5,<15"]
|===
| 1    | unesim
| 2    | duesim
| 3    | triesim
| 4    | quadresim
| 5    | quinesim
| 10   | decesim
| 30   | triantesim
| 55   | quinantquinesim
| 100  | centesim
| 1000 | milesim
|===

[NOTE]
--
*decesim* (tenth) is written as *decesim* and
not *deciesim* because <<_i,*-i*>> in *deci* is the adjectival ending we
encountered above (the root itself is *dec*). This is another example of
an adjective that requires the <<_i,*-i*>> ending on its own as
otherwise *dec* would be pronounced "`dek`".

*-esim* also gives rise to internationally-recognized words such as
*ínfinitesim* (an infinitessimal part) and *infinitesimal*. In
Interlingue these words are regularly derived from common verbs:
*ín*{nbsp}+ <<_the_de_wahls_rule,*fini-r* (to finish){nbsp}+
*t*>>{nbsp}+ *-esim*{nbsp}+ <<_al,*-al*>> = *ínfinitesimal*.

Similarly, sometimes the *-ant* is written *-anti* for euphonic
purposes. But because *-ant* on its own is easy enough to pronounce
the *-anti* form is much rarer.
--

Per adjuntion del sufix *-plic* (*-uplic* pos consonantes) (del verbe
"`plicar`") noi recive li *multiplicativ* numerales, queles responde al
question *"`quantuplic?`"*:

- unuplic (simplic)
- duplic
- triplic
- duantquinuplic
- decuplic
- duantuplic
- qua__d__ruplic
- centuplic

NOTE: From these words are also derived many known words: *duplicitá*
(duplicity), *triplicar* (to triplicate), etc. Also note the "`d`" in
*quadr* to form recognizable terms such as *quadratic*, *quadrennial*,
etc.

NOTE: To summarize: *quant* asks how many, *quantesim* asks which
place (the "`howmany-ith`"), and *quantuplic* how many times (the
"`howmany-uple`").

Existe anc *colectiv* numerales, queles expresse un colection o un
aproximativ númere:

- unité
- pare
- triene
- quarene
- quinene
- sixene
- decene
- deciduene
- duantene
- centene
- milene

NOTE: The above numbers are used collectively or approximatively in
phrases such as *un centene de soldates*: a hundred soldiers. English
uses collective nouns rarely (a group of people, a pair of ducks,)
while Interlingue allows it with any number with the *-ene* ending.

Li fractiones es:

[cols="<10,<35"]
|===
| 1/1        | un tot
| 1/2        | un demí (o un duesim)
| 1/3        | un ters (o un triesim)
| 1/4        | un quart
| 1/5        | un quinesim
| 1/100      | un centesim
| 0,1        | null e un decesim
| 2,3        | du tot e tri decesim (o du comma tri)
| 1 1/2      | un e demí
| 2 3/4      | du e tri quart
| 2 x 2 = 4  | du vez du es quar
| 10 / 2 = 5 | deci sur du es quin
|===

De 1/5 li fractiones es simil al ordinales.

// Vocabularium {{{4
===== Vocabularium

// XXX REMARK -- Ni "in vice de" ni "vice" es usat in ti letion, ma
// solmen in ti vocabularium:

- *adjunter* = to add to
- *colecter* = to collect
- *composir* = to compose
- *deciduene* = a dozen
- *in vice de* / *vice* = instead of 
- *multiplicar* = to multiply   
- *pare* = pair
- *plicar* = to fold
- *quant* = how many   
- *quantesim* = which place
- *reciver* = to receive
- *unité* = unit       

// Li témpore e su division {{{3
==== Li témpore e su division

Quel hora es? Quel es li témpore?

- 12:00 = a decidu horas (precis); it es midí
- 12:45 = a un hora ante un quart
- 1:00 = a un hora (precis)
- 1:25 = a un hora e duantquin

// XXX REMARK -- This comment just prevents both lists to be combined
// into one.

- Sixant secundes es un minute.
- Sixant minutes es un hor.
- Duant quar hores es un die.
- Sett dies constitue un semane.
- In un mensu es circa quar semanes.
- Decidu mensus es un annu.
- Cent annus es nominat un secul, mill annus un millennie.

Li sett dies del semane es: soledí, lunedí, mardí, jovedí, mercurdí,
saturdí.

Li decidu mensus es: januar, februar, marte, april, may, junio, julí,
august, septembre, octobre, novembre e decembre.

[NOTE]
--
The word *hora* refers to the hour of the day. The
word *hor* refers to an hour of time.

The word *clocca* is an alternative to the word *hora*. It was
replaced by *hora* during the 1940s but seems to have remained popular
and has a bit of a slangy feel. *Ye clocca du = a du horas*.

While we are on the subject, the same has happened with the
word *flicca* ("`girl`", from Swedish _flicka_), which was changed
to *puella* a long time ago. Now *flicca* has a similar feel to
English "`gal`" or "`chick`".
--

// XXX REMARK -- The "verse" block name causes Asciidoctor create a
// blockquote container in DocBook, no matter if the delimiters are
// "____", "--" or omitted.

[verse]
--
Triant dies hav' septembre,
April, junio, novembre,
Triant un have altris tot,
Februar sol have duant ott;
Except in annus intercalar
Duant nin have februar.
--

[verse]
--
In li verne plantes cresce in li renascet natura.
In estive flores vive e li dies es calid.
In autune flores mori e li fructes es matur.
In hiverne veni nive e li dies es frigid.
--

// Vocabularium {{{4
===== Vocabularium

- *annu* = year
- *autune* = autumn
- *calid* = hot
- *die* = day
- *estive* = summer
- *flore* = flower
- *hiverne* = winter
- *mensu* = month
- *midí* = midday
- *millennie* = millennium
- *nive* = snow
- *quel* = which
- *renascer* = to be reborn (cf. renaissance, *renascentie* in Interlingue)
- *secul* = century
- *semane* = week
- *verne* = spring

// Aforismes {{{3
==== Aforismes

[quote, Bismarck]
____
In null altri ocasion on menti tant quam pos un chasse, durant un guerre
e ante un election.
____

[quote, Seneca]
____
Si li veritá vell esser dat me con li condition, que yo deve celar it in
me e ne dar it de me – yo vell refusar it.
____

[quote, Locke]
____
It es just egal, si on interprende liberar homes queles have null firm
conceptiones ex lor erras, quam si on vole expussar un vagabunde qui
have null firm dom ex su hem.
____

[quote, Spinoza]
____
Quo noi nómina accidentie, es li asil del ignorantie.
____

// Vocabularium {{{4
===== Vocabularium

- *accidentie* = accidence, chance
- *celar* = to hide
- *chasse* = hunt
- *expussar* = to chase out
- *ignorantie* = ignorance
- *interprender* = to undertake
- *liberar* = to free, to liberate
- *mentir* = to lie (not tell the truth)
- *null* = no (none)
- *ocasion* = occasion, event
- *refusar* = to refuse
- *veritá* = truth

// Explanations {{{2
=== Explanations

// XXX FIXED -- Titul: "Explanation" -> "Explanations"

Knowing how to derive words with prefixes and suffixes is of great
importance in the understanding of international words, because being
able to do this allows you to form a large number of
internationally-understood words on your own from a single root. None of
the prefixes or suffixes in Interlingue, seemingly so large in number,
were created from scratch, but already exist in many internationally
known foreign words. The difference in that in Interlingue they are not
simply imported loanwords, and have been given a more precise sense and
have been made for more general and meaningful use.

Let's take the root *centre* as an example (centre in English as
well). From this word we already recognize words derived from
it: *central, centrale, centralisme, centralisar, centralisation,
centralisator, decentralisar, decentralisation, concentrar,
concentration, excentre, excentric, excentricitá, subcentral*, etc. By
learning Interlingue's derivation one gains an understanding for how they
are made up.

We are now going to look at prepositions, which in Interlingue are not
simply standalone particles but also used to form words.

// Prepositions {{{3
==== Prepositions

// XXX FIXED -- Titul: "Prepositiones" -> "Prepositions"

|===
| *a, ad*     | to
| *along*     | along
| *alor*      | then
| *ante*      | before
| *apu*       | by, next to
| *avan*      | before
| *caus*      | because of
| *che*       | at, with
| *circum*    | around
| *con*       | with
| *contra*    | against
| *de*        | of, from
| *desde*     | since
| *detra*     | behind
| *durant(e)* | during
| *ex*        | out
| *except*    | except
| *extra*     | besides
| *in*        | in
| *infra*     | below
| *intra*     | between
| *malgré*    | despite
| *per*       | by, through
| *por*       | for
| *pos*       | after
| *preter*    | past
| *pri*       | regarding
| *pro*       | due to
| *secun*     | according to
| *sin*       | without
| *sub*       | under
| *sur*       | on
| *súper*     | over
| *til*       | until
| *tra*       | through
| *trans*     | across
| *ultra*     | beyond
| *vers*      | towards
| *vice*      | instead
| *ye*        | preposition used when no other apt preposition comes to mind
|===

Let's take a look at a few from all of these.

// a {{{4
===== a

// XXX FIXED -- "Of." -> "To.":

To. Has many uses:

// XXX FIXED -- regrettar -> regretar

====

- *Il dat li flores a su amata.* = He gave the flowers to his
  girlfriend.
- *Un epistul a nor societé.* = A letter to our society (note: society
  as in a group or company).
- *Yo viagea a Berlin.* = I travel to Berlin.
- *Li vapornave ea a Lisbon.* = The steamboat goes to Lisbon.
- *Clar a departer.* = Ready (clear) to depart.
- *Un error a regretar.* = A regretful error (lit. an error to
  regret).

====

// ante {{{4
===== ante

Means "`before`" in terms of time and place (*avan* only refers to place).

====
- *ante Cristo* = before Christ
- *avan li dom* = before the house
====

// caus {{{4
===== caus

Because of. The reason for something goes right after *caus*, which is
an abbreviation of the longer *in cause de*.

====
- *caus vor intervention* = because of your intervention
- *caus li politic evenimentes* = because of the political events
====

// con {{{4
===== con

With.

====
- *Li filio ea con su patre.* = The son goes with his father.
- *Ella stat con lácrimes in li ocules.* = She stood with tears in her
  eyes.
====

NOTE: The phrasing "`the hands`", "`the eyes`" to refer to body parts
is more common internationally than the English his/her/their. But
English also uses it sparingly such as in "`look me in the eyes`" (not
"`look me in my eyes`").

// de {{{4
===== de

*De* has a wide usage, and oftentimes other prepositions can be used
in its place.

====

- *Li dom de mi patre.* = The house of my father, my father's house.
- *Li dramas de Schiller.* = Schiller's dramas.
- *Ti libre es scrit de un fémina.* = This book is written by a woman
  (*per* fits here as well).
- *Un senior de Berlin.* = A gentleman from Berlin (*ex* fits here as
  well).
- *Li max grand de omnis.* = The largest of all (*ex* potentially fits
  here as well).
- *Un vase de aure.* = A vase of gold.

====

// desde {{{4
===== desde

Since, for.

====

- *Desde du annus.* = For two years.

====

// ex {{{4
===== ex

Out (of), from.

====

- *Il venit ex su chambre.* = He came out ofhis room.
- *Yo trinca ex li glass.* = I drinkt out of the glass.
- *Traductet ex german in Interlingue.* = Translated from German into
  Interlingue.

====

// per {{{4
===== per

By, through, with

====

- *Il defendet se per un gladie.* = He defended himself with a sword.
- *Il salvat se per svimmar.* = He saved himself by swimming.
- *Li moné ha esset furtet per un ínconosset hom.* = The money has been
  stolen by an unknown person.

====

// por {{{4
===== por

====

- *Un libre por omnes e por nequí.* = A book for all and for nobody.
- *On manja por viver, on ne vive por manjar.* = You eat to live, you
  don't live to eat.

====

// pri {{{4
===== pri

====

- *Noi parlat pri politica.* = We talked about politics.
- *Yo mersia pro Vor auxilie.* = I thank (you) for your help.

====

// til {{{4
===== til

====

- *Yo laborat til decidu horas.* = I worked until twelve o'clock.
- *Til li extrem fine del munde.* = Until the very end of the world.

====

// tra {{{4
===== tra

====
- *Yo videt le tra li fenestre.* = I saw him through the window.
====

// trans {{{4
===== trans

====

- *Lindberg volat trans li Atlantic Ocean.* = Lindberg flew across the
  Atlantic Ocean.

====

// vers {{{4
===== vers

====
- *Li avie volat vers li sole.* = The bird flew towards the sun.
====

// Words formed by prepositions {{{3
==== Words formed by prepositions

These prepositions are also used to form other words.

====

- *aportar* = to bring (*a*{nbsp}+ *portar*, to carry)
- *antediluvian* = antediluvian (*ante*{nbsp}+ *diluvie*, a flood)
- *avanposto* = outpost (*avan*{nbsp}+ *posto*)
- *circumstantie* = circumstance (*circum*{nbsp}+ *stantie* from
  *star* = to stand)
- *constellation* = constellation (*con*{nbsp}+ *stelle* = star)
- *contravention* = contravention (*contra*{nbsp}+ *vention* = coming,
  from *venir*)
- *deportar* = to deport (*de*{nbsp}+ *portar*, to carry)
- *exportar* = to export (*ex*{nbsp}+ *portar*, to carry)
- *ex-imperator* = former emperor
- *extraordinari* = extraordinary (*extra*{nbsp}+ *ordinari*)
- *inclusiv* = inclusive (*in*{nbsp}+ *cluder*, to close or shut)
- *intervalle* = interval (*inter*{nbsp}+ *valle*, a bulwark or
  embankment (related to English wall))
- *preterpassant* = passing by (*preter*{nbsp}+ *passar*, to pass)
- *subordination* = subordination (*sub*{nbsp}+ *ordinar*, to order)
- *traducter* = to translate or render (*tra*{nbsp}+ *ducter*, to
  lead)
- *transatlantic* = transatlantic
- *vice-presidente* = vice president (*vice*{nbsp}+ *presidente*)

====

// Prefixes {{{3
==== Prefixes

The following prefixes are only used in compound words.

// XXX FIXED -- "bei-" -> "bel-"

// bel- {{{4
===== bel-

Related by marriage.

====

- *belfratre* = brother-in-law (*fratre* = brother)

====

// des- {{{4
===== des-

(Usually *de-* before consonants.)

Before nouns: nullation or opposing meaning, un-:

====

- *desagreabil* = disagreeable (*agreabil* = agreeable, friendly)
- *deshonor* = dishonour
- *desilusion* = disillusion

====

On verbs: loss of something:

====
- *desarmar* = to disarm (*armar* = to arm)
====

// dis- {{{4
===== dis-

Separation, moving away:

====

- *dismembrar* = to dismember (*membre* = limb)
- *distracter* = to distract (*tracter* or *traer* = to pull)

====

// ín- {{{4
===== ín-

// XXX FIXED -- "in/un/etc." -> "(in-, un-, etc.)"

// XXX FIXED -- "official" (old orthography) -> "oficial"

Opposite meaning (in-, un-, etc.):

====

- *ínoficial* = unoficial
- *ínclar* = unclear
- *íncurabil* = uncurable
- *ínpossibil* = impossible

====

[NOTE]
--
Other more internationally-recognized forms such
as *impossibil* (vs. *ínpossibil*), *irregular* (vs. *ínregular*) etc.
were often used in Interlingue but the user base showed a preference for
a regular *ín-* and the other forms have become rarer.

Not to be confused with the unstressed preposition *in-*,
similar to the one in English in words such as *inclusiv*, *inspecter*.
--

// mis- {{{4
===== mis-

Wrong, improper, mis-:

====

- *miscomprender* = to misunderstand (*comprender* = to understand)
- *misparlar* = to misspeak (*parlar* = to speak)

====

// pre- {{{4
===== pre-

Before, pre-:

====

- *prematur* = premature (*matur* = mature)
- *prevenir* = to forestall, to preempt, to prevent (*venir* = to come)
- *prehistoric* = prehistoric

====

// pro- {{{4
===== pro-

Ahead, forth

====

- *producter* = to produce (*ducter* = to lead)
- *projecter* = to project (*jecter* = to throw)

====

// re- {{{4
===== re-

Again, re-:

====

- *reaction* = reaction
- *renascentie* = renaissance, rebirth (*nascentie* = birth)
- *revider* = to see again (*vider* = to see)

====

// Which form to use? {{{3
==== Which form to use?

When Interlingue was first announced in 1922, Edgar de Wahl proposed a
number of standalone and derived words that he believed to be equally
valid, leaving the decision between them to the community to see which
form it preferred. This process of ironing out took place over the next
25 years, at a very gradual pace as all changes in the end were very
minor. Some examples of theoretically equally valid forms are the
following:

[cols="25,25,50"]
|===
| Etymologic | Doubled consonant | Modern single consonant form

| *adportar*
| *apportar*
| *aportar* (to bring, from *ad*{nbsp}+ *portar*, lit. to "`to pull`")

| *adnexion*
| *annexion*
| *anexion* (to annex, from *ad*{nbsp}+ *nexer*, lit. to "`to tie`")

| *adtractiv*
| *attractiv*
| *atractiv* (to attract, from *ad*{nbsp}+ *tracter*, lit. to "`to pull`")

| *obpression*
| *oppression*
| *opression* (to oppress, from *ob*{nbsp}+ *presser*, lit. to "`against press`")

| *subposition*
| *supposition*
| *suposition* (to suppose, from *sub*{nbsp}+ *poser*, lit. to "`under place`")

|===

The form on the left was rarely if ever used, due to 1) the
uninternational appearance and 2) the possibility of appearing to have a
different meaning. *Subposition* for example simply looks like "`under
position`" and does not give the sense of "`supposition`".

The second form was used for a time, but eventually the community
settled on the form on the right for simplicity, with doubled consonants
used in the cases mentioned in the beginning of the book ("`ss`" to maintain
the [s] sound in all cases, "`ch`" for [sh], etc.).

// Quinesim letion {{{1
== Quinesim letion

// Textus {{{2
=== Textus

// Regress e progress {{{3
==== Regress e progress

Etsi it sempre ne es litteralmen ver que it custa torrentes de sangue
por pussar li homanité in moventie un millimetre adavan, it támen es
ínnegabil e pruvat del experientie, que íncredibil mult eforties es
necessi por far li homanité comprender un nov idé, benque it vell
aportar it grand avantages. It existe tro mult homes, queles relate con
índiferentie e indolentie a lu nov, o monstra admaxim un platonic
benevolentie, e anc tales, queles combatte it con apert íntolerantie e
mem acumula barrieres e impedimentes por desfacilisar li progress del
cultur. In consequentie de lor ignorantie ili quasi time líber pensada e
li aparentie de nov idés, e ili da preferentie solmen a to, quo sta in
acordantie a lor propri restrictet saventies. Qual perseverantie de su
pioneros ha postulat e va postular li movement por un lingue
international, qual persistentie in li confidentie e esperantie al final
victorie del nobil idé!

Omni progress es li resultate de un tenaci luctada inter du tendenties:
un, quel crede in li permanentie de lu existent e insiste in li
conservation de it, e un altri, quel crede in li existentie de alquicos
plu bon. Fórsan con un cert exageration on nómina li unesimes frenatores
e reactionarios, li duesimes fantasistes e utopistes. Li fundamental
diferentie inter li du partises es proprimen to, que li regressistes ne
conosse li essentie del nov idés e pro to ne posse apreciar lor valore e
importantie, durant que li progressistes es tro inclinat depreciar li
existentie del conservativ leges del realitá e li potentie del temporari
circumstanties. On vell posser nominar ti du partises realistes e
idealistes, de to ne vell esser alquant ínjust, nam anc li realistes
have su ideales, e anc li idealistes calcula con un realitá, quel posse
fórsan esser plu ver quam li evident.

Un filosof unquande ha expresset li sam pensa per ti paroles: "`Li munde
sempre ha ridet pri to quo plu tard ha verificat se. In omni témpores
existe homes qui pensa, e homes qui ride. Quande li témpore ha passat e
un nov intrat – it ha sempre esset talmen, ne existe exceptiones – tande
li munde ha regardat a retro e erectet monumentes a tis qui pensat, e
ridet pri tis qui ridet.`"

// Vocabularium {{{4
===== Vocabularium

- *acordantie* = accordance
- *acumular* = to accumulate
- *admaxim* = at most
- *alquant* = quite
- *alquicos* = some thing
- *aparer* = to appear
- *apert* = open
- *apreciar* = to appreciate
- *avantage* = advantage
- *barrar* = to bar
- *calcular* = to calculate
- *cert* = certain
- *circumstantie* = circumstance
- *confider* = to confide
- *custar* = to cost
- *depreciar* = to depreciate
- *effortie* = effort
- *erecter* = to erect, to raise
- *essentie* = essence
- *etsi* = although
- *exception* = exception
- *frenar* = to brake
- *fórsan* = perhaps
- *impedir* = to impede
- *importantie* = importance
- *inclinar* = to incline, to tend
- *indolentie* = indolence
- *insister* = to insist
- *intrar* = to enter
- *lege* = law
- *luctar* = to fight, to struggle
- *líttere* = letter
- *monstrar* = to show
- *mover* = to move
- *negar* = to deny
- *nobil* = noble
- *partise* = party
- *perseverar* = to persevere
- *persister* = to persist
- *potentie* = might, power
- *pruvar* = to prove
- *pussar* = to push
- *quasi* = as if, quasi
- *regardar* = to regard
- *relater* = to relate
- *restricter* = to restrict
- *retro* = backwards, retro
- *rider* = to laugh
- *sangue* = blood
- *tenaci* = tenacious
- *timer* = to fear
- *tro mult* = too much
- *unquande* = once
- *valore* = worth
- *verificar* = to verify
- *victorie* = victory
- *índiferentie* = indifference
- *ínjust* = unjust

// Economisation {{{3
==== Economisation

Si noi vole economisar moné, noi deve deposir it e ne spoliar it in
omnidial micri expenses. Ma si noi vole economisar témpore, nor hores e
minutes, noi deve utilisar les, e plu exclusivmen ili es usat por digni
scopes, plu ili es transformat in un capitale de caractere,
intelligentie e potentie. Noi cresce ne in aritmetic, ma in geometric
progression, li flut de nov vive ne es solmen addit, ma multiplicat per
lu antean. Un nov pensa, quel on excisela, ne es solmen juntet al
anteyan pensas, ma transforma les e multiplica les, da nos nov
vispunctus, de queles noi vide omni relationes e idés in un altri
perspective.

Un passu ancor ad-supra li monte fa li horizonte plu vast in omni
directiones.

Channing

// Vocabularium {{{4
===== Vocabularium

- *ad-supra* = up
- *ancor* = still, yet
- *anteyan* = former
- *digni* = dignified
- *economisar* = to economize, to save
- *exciselar* = to chisel out (*ciselar* = to chisel)
- *flut* = flood, flow
- *junter* = to join
- *monte* = mountain
- *moné* = money
- *passu* = a step
- *plu … plu …* = the more … the more …
- *scope* = goal, aim
- *spoliar* = to spoil, to waste
- *usar* = to use
- *vast* = vast

// Li division de labor {{{3
==== Li division de labor

Noi ha studiat mult e perfectionat mult, durant li ultim témpore,
concernent li grand invention del civilisation: li division de labor.
Solmen noi da it un fals nómine. It ne es, si noi expresse li veritá, li
labor, quel es dividet, ma li homes: dividet in segmentes de homes,
ruptet in micri fragmentes e pezzes de vive, talmen que li micri parte
del intelligentie, quel resta in un hom, ne es suficent por far un
pivote o un clove, ma exhauste se per far li fine de un pivote o li cap
de un clove. E li grand cri, quel eleva se ex nor industrial cités, plu
sonori quam lor sofflada de fornes – omnicos deriva de to, que noi
fabrica omnicos in ili, except homes. Noi inpallida coton, e indura
stal, e raffina sucre e modella ceramica, ma clarar, indurar, rafinar o
modellar un singul vivent anim, tó nequande trova se in nor
calculationes de profite.

Ruskin

NOTE: *to* is only written with an accent here to show emphasis
("`_that_ is never found in our profit calculations`").

// Vocabularium {{{4
===== Vocabularium

- *anim* = soul
- *cap* = head
- *clove* = nail
- *concerner* = to concern
- *coton* = cotton
- *cri* = a cry
- *derivar* = to derive
- *elevar* = to elevate, to raise
- *fals* = false
- *fine* = end
- *forn* = oven
- *indurar* = to harden
- *inpallidar* = to bleach (also *pallidar*, *in-* strengthens the
  verb a bit as in "`to bleach in`")
- *pezze* = piece
- *pivote* = fulcrum, hinge
- *restar* = to remain
- *rupter* = to break, to rupture
- *sonori* = sonorous
- *suficent* = sufficient
- *ultim* = final, recent

// Sofistica {{{3
==== Sofistica

// XXX FIXED -- Protagoras -> Protágoras

Un yun greco hat aprendet de Protágoras li arte de sofistes contra
payament de 50 mines ínmediatmen e ulterior 50 mines, quande il hat
victet in su unesim processu. Proque il tardat payar li ultim parte,
Protágoras comensat processu contra il. In ti die, in quel li judicament
evenit, li du parties incontrat ante li deliberationes del judicos.

"`It es plu bon, que tu paya me nu,`" dit li mastro, "`nam si yo victe, tu
va esser judicat a payar, e si tu victe, tande tu ya ha victet in unesim
processu, e va dever payar me anc in ti casu.`"

// XXX FIXED -- Erra ex li original german: "in mu unesim processu" ->
// "in unesim processu"

"`No, ples atender un poc,`" replicat li yun mann, "`si tu victe, tande yo
ne ha victet in unesim processu, e tande, comprensibilmen, yo ne deve
payar te e si yo victe, tande li judicament ya va esser tal, que yo ne
deve payar.`"

// XXX FIXED -- Markup of "índemiatmen":

// Vocabularium {{{4
===== Vocabularium

// XXX FIXED -- "Ancient" -> "ancient"

// XXX FIXED -- Made "comprensibilmen" the headword, which is the one
// used in the text, and make "comprensibil" its explication. The
// german original transcription had this issue too.

- *aprender* = to learn
- *atender* = to wait
- *comprender* = to understand
- *comprensibilmen* = of course (from *comprensibil* = understandable,
  natural)
- *evenir* = to happen
- *judicar* = to judge
- *judico* = a judge
- *mastro* = master
- *mine* = mine (ancient Greek currency)
- *payar* = to pay
- *replicar* = to reply
- *tardar* = to delay
- *victer* = to win
- *ínmediatmen* = immediately

// Li max perfect lingue {{{3
==== Li max perfect lingue

Un lingue, aprioric e logic, in quel chascun parol vell esser solmen un
signe de un sol fix notion, un lingue sin images e metáfores e sin alcun
associationes de idés, queles nequande vell lurar li pensa a altri
notiones, un tal lingue vell esser perfectissim, pur principiarimen, pur
teoricmen. Li paroles vell esser solmen instrumentes del pensa e necos
plu.

Ma, it es un fact, noi nequande vell posser aprender un tal lingue. To
es, si noi ne presuposi, que li vocabularium deve esser micrissim
possibil. Ma tande it ne vell esser possibil expresser to, quo un
civilisat nation, mem li micrissim popul, posse expresser per su lingue.
Li homan memorie besona firm punctus por adherer, ma sur li
calv, glacie-polit superficie del logic notiones it ne posse retener se.
Just caus lor ínperfectitás e ruditás li natural lingues da nos plu
secur adhesion por li memorie.

Li amore al metáfores es tam inradicat in nor mentes, que, etsi noi vell
posser dispensar li metáfores, noi támen ne vell voler it. In omni
lingues, nov e antiqui, on posse constatar li fenomen, que simplic,
descolorat nómines es viceat per paroles, queles per su images
e associationes de idés es quasi plu vivent, plu interessant. E noi
posse profetisar, que tam long quam nor homanité ne ha perdit se ancor
in pur ration, tam long quam sentiment e imagination ancor lude un rol,
tam long quam homes ama li flores del verne ne solmen li sicc folies del
autune – tam long un lingue aprioric, sin historie e sin metáfores ne
va esser parlat sur ti ci globe.

// Vocabularium {{{4
===== Vocabularium

- *adherer* = to adhere
- *amore* = love
- *besonar* = to need
- *calv* = bald
- *chascun* = each
- *dispensar* = to dispense, to rid oneself of
- *fix* = fixed, fast
- *glacie* = ice
- *luder* = to play
- *lurar* = to lure
- *mente* = mind
- *necos* = nothing (n.b. derived from *ne*{nbsp}+ *cose*, thus
  accented as *necós* and often written with the accent)
- *perdir* = to lose
- *presupposir* = to presuppose
- *pur* = pure
- *radica* = a root
- *rol* = role
- *rud* = rude, rough
- *sentir* = to feel
- *sicc* = dry
- *superficie* = surface
- *vicear* = to replace

// Proverbies {{{3
==== Proverbies

Honestie es li max bon politica.

Exemples es plu bon quam prescrites.

Laude fa bon homes plu bon, e mal homes plu mal.

Fortuna favora li braves.

Li oldes save, quo li yunes ne conosse, ma li yunes aprende, quo li
oldes ne posse.

Li bravo merite li bella.

De lu sublim a lu comic es sovente solmen un passu.

Leges es quam li texturas del aranés; li micri moscas es captet, li
grandes trapassa.

// Vocabularium {{{4
===== Vocabularium

- *arané* = spider
- *brav* = brave
- *capter* = to catch
- *fortuna* = fortune
- *laude* = praise
- *meriter* = to merit
- *mosca* = a fly
- *texter* = to spin
- *trapassar* = to pass through

// Li historie {{{3
==== Li historie

// XXX FIXED -- abyss -> abiss

Per li studia del historie noi percepte li intim conexion, quel existe
inter lu present e lu passat. Li present moment es un transient cose, su
radicas es in lu passat, su esperas in lu futuri. Si omnicos vell
depender del subtil fil del fugient moment, quel ilumina e dura solmen
durant un move del ocul, solmen por evanescer in li abiss de Nihil,
tande omni vive vell significar solmen un exeada ad in li morte. Noi es
tro inclinat regardar lu passat quam alquicos mort, ma it existe ye
vivent evidentie in nor animas hodie. It opresse nos e stimula nos al
action, it tirannisa nos e inspira nos a coses plu sublim.

// Vocabularium {{{4
===== Vocabularium

- *abiss* = abyss
- *conexion* = connection
- *depender* = to depend
- *evanescer* = to evanesce
- *exeada* = exit
- *fil* = thread
- *fugir* = to flee
- *futuri* = future (adjective)
- *mort(i)* = dead
- *morte* = death
- *Nihil* = Nothing
- *passat* = past
- *percepter* = to perceive
- *significar* = to mean, to signify
- *subtil* = subtle
- *transir* = to transit, to go by

// Aforismes {{{3
==== Aforismes

[quote, O. Fehlmann]
____
Li historie demonstra, que un energie e scop-conscient labor finalmen
triumfa, ne pro que grand masses de homes auxilia realisar alcun cose,
ma sovente pro que li iniciatores sin repose acte por li idé.
____

[quote, O. Wilde]
____
Sovente it es plu desfacil viver por un idé quam morir por it. To es li
diferentie inter heróes e martiros.
____

// XXX FIXED -- "de fa" -> "ne fa"

[quote, Multatuli]
____
Du levul gantes ne fa un pare de gantes, du demí veritás ne fa un
veritá.
____

// Vocabularium {{{4
===== Vocabularium

- *alcun* = some
- *auxiliar* = to help
- *cose* = thing
- *finalmen* = finally
- *gante* = glove
- *iniciar* = to initiate, to start
- *levul* = left
- *repose* = repose
- *scop-conscient* = goal-conscious

// Explanations {{{2
=== Explanations

Endings for types of words such as nouns, adjectives and the like are no
more obligatory in Interlingue than in natural languages. Vowels at the
end of words are mainly justified by ease of pronunciation.
Internationally-known words found in many languages are just as diverse
in Interlingue as in other languages. Some of them are: *firma* (company),
*boa*, *auto*, *conto* (account), *cangurú* (kangaroo), *marabú* (a type of tree),
*tabú*, *colibrí* (hummingbird), *lampe*, *idé* (idea), etc. Nouns, adjectives
and particles can end in any vowel or consonant, as long as the word can
be clearly spoken.

// -e {{{3
==== -e

// XXX FIXED -- Removed "(nouns)" (which was the format of the
// original german transcription)

A very common end vowel in Interlingue is *-e*,
which does not have any particular meaning, but is used for ease of
pronunciation and to distinguish words from others. Nouns: *teatre*,
*centre*, *lampe*. Adjectives: *pie* (pious), *varie* (varied). An
adverb: *sovente* (often). The *-e* is also seen in plurals after a
consonant before the *-s*: *nation*, *nationes*. It can also play a role in
distinguishing a noun from an adjective: *central* (central),
*centrale* (headquarters).

// -i {{{3
==== -i

// XXX FIXED -- commen -> common
// XXX FIXED -- pronounciation -> pronunciation 

The most common adjectival ending is *-i*,
which is also used for pronunciation and distinguishing types of words:

====

- *vivaci* = vivacious/lively
- *sagi* = wise
- *omni* = all
- *stormi* = stormy (*storm* = storm)
- *uniformi* (the noun is *uniform*)

====

// -o, -a {{{3
==== -o, -a

For nouns referring to living creatures, the ending *-o*
is used to indicate the male gender, and *-a*
the female, when necessary. (Genderless or unspecified: <<_e,*-e*>> or no
ending):

====

- *un germano* = a German man
- *un germana* = a german woman
- *amíco* = male friend
- *amíca* = female friend
- *cavallo* = male horse (stallion)
- *cavalla* = female horse (mare)
- *gallino* = rooster
- *gallina* = hen

====

// XXX TODO -- This explanation doesn't seem fine, because "o" and "a"
// ar part of "-iero" and "-iera", "-ia":

In many other words the *-o* ending is used for a specific item, while *-a*
refers to something in a more collective sense, a location or
time. <<_iero,*rosiero*>> = rose bush, <<_iera,*rosiera*>> = rose
garden, <<_eríe,*barbería*>> =
barbershop, *auditoria* = auditorium, *imperia* = empire, etc.

Substantival (noun) adjectives may be used as nouns:

====

- *li rich e li povri* = the rich and the poor
- *li riches e li povres* = the rich and the poor (lit. the rich ones
  and the poor ones)

====

The same endings can be used on adjectives to indicate the gender:

====

- *li bello* = the handsome man
- *li bella* = the beautiful woman
- *li yunos* = the young ones (boys)
- *li yunas* = the young ones (girls)

====

The ending can also be used on the definite article itself if there is
no particular noun in mind:

- Masculine: *lo bell* = the handsome
- Feminine: *la bell* = the beautiful
- Neutral: *lu bell* = the beautiful

NOTE: *lu* is by far the most often used of the three above.

// -um {{{3
==== -um

Finally, the ending *-um*
can be used on an adjective to form a noun that
expresses the general idea of something:

====

- *novum* = newness
- *bonum* = goodness
- *caracteristicum* = characteristicness

====

// Comparative forms {{{3
==== Comparative forms

Comparative (more, less) and superlative (most, least) adjectives are
formed in the following way:

====

- *li bell flore* = the beautiful flower
- *li _plu_ bell flore* = the more beautiful flower
- *li _max_ bell flore* = the most beautiful flower (also *maxim*)
- *li _min_ bell flore* = the less beautiful flower (also *minu*)
- *li _minim_ bell flore* = the least beautiful flower
- *li bell__issim__ flore* = the very beautiful (gorgeous, etc.) flower

====

The above are the regular comparative forms. Other less regular forms
exist due to their being part of already existing international words:

====

- *bon* = good
- *melior* = better (<<_ar,*a__melior__ar*>>, to improve)
- *optim* = best (<<_ist,*__optim__ist*>>)
- *mal* = bad
- *pejor* = worse (<<_iv,*__pejor__ativ*>>)
- *pessim* = worst (<<_ist,*__pessim__ist*>>)
- *grand* = large
- *major* = larger (<<_tá_té,*__major__ité*>>)
- *maxim* = largest (<<_al,*__maxim__al*>>)
- *micri* = small
- *minor* = smaller (<<_tá_té,*__minor__ité*>>)
- *minim* = smallest (<<_al,*__minim__al*>>)

====

NOTE: *minim* is included here for the sake of completeness even
though it is part of the regular comparative forms.

// Divers suffixes {{{3
==== Divers suffixes

// XXX FIXED -- Titul: "Divers sufixes" -> "Divers suffixes" (anglesi)

// -ett {{{4
===== -ett

The usual diminutive (making smaller) suffix is *-ett*:

====

- *filietto* = sonny, *filietta* = little daughter (*filie* = child)
- *brunetti* = brunette (brun = brown), *rosette* = rosette (from
  rose, rose)
- *cigarette* = cigarette (*cigare* = cigar)
- *pincette* = pincette (*pince* = pincers)
- *foliettar* = to leaf through (*folie* = leaf)
- *volettar* = to flutter (*volar* = to fly)

====

The same suffix is used to indicate small tools or instruments.
Example: *inflammette* = match (from flamme, flame), *tenette* = grip,
hilt (on a sword, from *tener*, to hold)

// -ach {{{4
===== -ach

The usual suffix to make something pejorative is *-ach*:

====

- *cavallacha* = nag (*cavall* = horse)
- *populache* = mob, the unwashed (*popul* = people)
- *criticachar* = to complain, to bitch (*criticar* = to criticize)
- *imitachar* = to ape (*imitar* = to imitate)

====

Many other expressions can be pejorative on their own: *simiar* also
means to ape (*simie* = monkey, ape).

// -ar {{{4
===== -ar

Verbs are usually formed with the *-ar* suffix, the most commonly used for
immediate derivation.

====

- *formar* = to form (from *form*, form)
- *laborar* = to work (from *labor*, work)
- *salar* = to salt (from *sale*, salt)
- *motivar* = to motivate (from *motiv*, motive)
- *coronar* = to crown (from *coron*, crown)
- *scruvar* = to screw (from *scruv*, screw)
- *brossar* = to brush (from *bross*, brush)
- *lactar* = to milk (from *lacte*, milk)
- *sanguar* = to bleed (from *sangue*, blood)
- *dominar* = to dominate (from *dómino*, master)
- *plenar* = to fill (from *plen*, full)
- *exsiccar* = to dry out (from *sicc*, dry)
- *abellar* = to beautify (from *bell*, beautiful)
- *afacilar* = to facilitate (from *facil*, easy)

====

As the last examples show, adjectives are frequently made into verbs
along with a preposition in front.

The present participle can also be made into verbs:

====

- *sedentar* = to sit (from *sedent* = sitting, thus to "`make sit`")
- *reviventar* = to revive (from *re*{nbsp}+ *vivent* = living, thus
  to "`re-make living`")
- *calentar* = to heat (*caler* = to feel warm, thus *calent* = being
  warm and *calentar* = to make warm)

====

// -isar {{{4
===== -isar

"`To make thus`", "`to make as`", similar to English:

====

- *electrisar* = to electrify (charge with electricity)
- *idealisar* = to idealize (from *ideal*, ideal, which comes from
  *idé*, idea)

====

NOTE: *electrisar* is formed from a sort of hidden word (*electr-*) formed
by removing the suffix <<_ic,*-ic*>>, which forms other words as well such
as *electron* (the <<_on,*-on*>> suffix will show up in the <<_sixesim_letion,next chapter>>).

*-isar* can also be used, though more rarely, with nouns. They form
words you already know:

====

- *canalisar* = to canalize (from *canale*, canal)
- *tirannisar* = to tyrannize (from *tiranno*, tyrant or bully)
- *terrorisar* = to terrorize (from *terrore*, terror)

====

// -ificar {{{4
===== -ificar

"`To make into something`", "`to bring towards`" — similar to <<_isar,*-isar*>>
above but slightly different.

// XXX FIXED -- "with power cables with" -> "with power cables"

====

- *electrificar* = to electrify (note the difference between this and
  <<_isar,*electrisar*>> above. *Electrisar* means to make something electric,
  to charge it, while *electrificar* means to equip something with
  electricity or make electric. Flipping a switch would thus
  *electrisa* one's room, while equipping a village with power cables
  *electrifica* it. Though such subtle differences are not too
  relevant in fluid conversation)
- *identificar* = to identify (from *identic*, identical; identify has
  these two meanings in English as well: 1) to establish the identity
  of and 2) to make the same)
- *falsificar* = to falsify (*fals* = false)
- *rectificar* = to rectify (*rect* = right)

====

// -ijar {{{4
===== -ijar

To become. The word itself to become is *devenir*, and *-ijar* is an
alternate way of expressing the idea.

====

- *maturijar* = to mature, to become mature (= *devenir matur*)
- *verdijar* = to green, to become green (= *devenir verd*)
- *oldijar* = to become old, to age (= *devenir old*)

====

// -ear {{{4
===== -ear

This suffix forms verbs that indicate a swinging or repeating motion, or
an intense state of being.

*undear* = to undulate, to wave (from *unde* = a wave)

*flammear* = to flicker (from *flamme* = flame)

*verdear* = to green (greening fields, verdant forests, etc.)

// Suffixes for verbal nouns {{{3
==== Suffixes for verbal nouns

The verbal stem (present tense) can also be used as a verbal noun, which
refers to a simple action.

====

- *yo pensa* = I think; *mi pensa* = my thought
- *il batte* = he hits; *un batte* = a hit

====

NOTE: For *-ar* and *-ir* verbs, this often gives the opportunity to make
very subtle distinctions if one wishes, due to the general <<_e,*-e*>> and
vowelless ending for nouns. This is better explained with examples:

// XXX FIXED -- "pensa" and "pense" were exchanged in the first
// sentence:

The word *pense* refers to a thought, while *pensa* refers to
thought. Both are correct, and have a subtle difference:

====

- *Li pensa venit a me* = the thought came to me (*pensa* is preferred
  here as it refers to the action of thinking)
- *penses e paroles* = thoughts and words.

====

This is, again, a subtle distinction that one may use if wished or
ignore at will, like the English words "`clothing`" and "`clothes`",
"`dinner`" and "`supper`", "`precise`" and "`accurate`", "`venom`" and
"`poison`", etc.)

We have already gone over the suffixes <<_ion,*-ion*>> and <<_ura,*-ura*>> in <<_triesim_letion,chapter 3>>.
Here are some others:

// -ada, -ida {{{4
===== -ada, -ida

*-ar* verbs use the *-ada* suffix, *-er* and *-ir* verbs the *-ida* suffix. It
refers to the activity of a verb in its duration.

====

- *promenada* = a walk, a stroll, a promenada (*promenar* = to stroll)
- *cannonada* = cannonade (a repeated firing of cannons, from
  *cannonar*, to fire a cannon, from *cannon* = a cannon)
- *cavalcada* = a cavalcade, riding (*cavalcar* = to ride)
- *currida* = running (*currer* = to run)

====

// -ntie {{{4
===== -ntie

More or less equivalent to the English "`-nce`" (designates a
condition in its duration), this is formed from the
<<_conjugation,*-nt* participle>> plus <<_ie,*-ie*>>.

====

- *existentie* = existence (*exister* = to exist)
- *índependentie* = independence (*depender* = to depend)
- *confidentie* = confidence (*confider* = to confide)
- *provenientie* = provenance (*provenir* = originate)
- *tolerantie* = tolerance (*tolerar* = to tolerate)

====

// -ment {{{4
===== -ment

// XXX FIXED -- full stop:

(This suffix requires some special attention, as their international use
is more limited than the way they are used in English and in French
which uses "`-ment`" with great frequency.)

Forms nouns that signify a special, concrete action or its outcome or
the means for it.

====

- *experiment* = an experiment (*experir* = to experience;
  *experientie* = experience)
- *fundament* = a foundation (*fundar* = to found; *fundation* refers
  to a founding)
- *impediment* = an impediment (*impedir* = to impede; *impedition*
  refers to an impediment in the sense of impeding)
- *nutriment* = nutrition (*nutrir* = to nourish; *nutrition* =
  nutrition in the sense of nourishing)
- *developament* = development, a development (*developar* = to
  develop; *developation* = development in the sense of developing)

====

Some other examples Edgar de Wahl mentioned in Cosmoglotta:

====

- *abonnament* (subscription) is not the act of subscribing but the
  legal status where one is subscribed
- *payament* (payment) is the money that one pays
- *medicament* (medicine) is the medicine itself, not the act of
  medication
- *ornament* is the ornament itself
- *testament* is the legal document
- *argument* is the argument that one makes, not the act of arguing

====

// -age {{{4
===== -age

1. The activity of a verb, mainly industrial or professional, its
expenses, etc.:
+
====
- *arbitrage* = arbitration, refereeing
- *inballage* = packing (*inballar* = to pack)
- *plantage* = planting
- *passage* = passage (*passar* = to pass)
- *rafinage* = refining (*rafinar* = to refine)
- *postage* = postage
- *doanage* = customs (collecting tax; *doane* = tax)
====

2. Collections with order, things made by:
+
====
- *tonnage* = tonnage (*tonne* = ton)
- *foliage* = foliage (*folie* = leaf)
- *boscage* = boscage (*bosco* = bush)
- *plumage* = plumage (*plum* = feather, pen)
====

// Sixesim letion {{{1
== Sixesim letion

// Textus {{{2
=== Textus

// Li festivitás ye li ocasion del ottcentenarie del cité capital {{{3
==== Li festivitás ye li ocasion del ottcentenarie del cité capital

Ja ante ott horas in li matin li publica comensat barrar li stradas
ductent al grand plazza de parade, talmen que li policistes havet mult a
far por retener it in respectabil distantie. Legionarios e pumperos
esset comandat quam auxiliatores por li policie.

Ja on posset vider un policist, forductent un laceron e un fripon, quel
esset arrestat quam furtard. Un trincard esset remarcat de un policist,
al gaudie de un galoppon de hotel. Un dormion presc restat sub un
automobil.

In li sud-front del plazza esset constructet tribunes por li special
invitat publica. On videt functionarios de divers institutiones,
publicistes e jurnalistes e anc cinematistes. Ye nin horas e tri quart
li central tribune comensat plenar se. Ultra li presidente e su marita,
nascet princessa D. con su can Bolognes, li comissario de policie, li
magistrate municipal, li borgomastro Ciennes on videt mult altri distint
persones. In li diplomatic loge prendet plazze li ambassadores anglesi,
francesi, german, chinesi, japanesi, con lor damas, inter ili li marita
del ambassador italian, li conosset patronessa del societé de
protectores de infantes. Inter li deputates del parlament on remarcat
omni fractiones comensante del max revolutionari bolshevistes, til li
conosset reactionario M., actionario e companion del chef del Grand
Magazin Central, e anc quelc pastores del partise Christian.

Presc precis ye deci horas comensat li grand parade militari con elegant
cavalcada del cavalleristes, inter queles excellet li lanseros. Li
chasseros con lor coloristic vestes evocat general sensation. Poy
defilat li artilleristes con lor modernissim mortatori apparates. Inter
li infanteristes marchat max von li musqueteros, flancat per li
jaloneros. Li officeros portat su órdenes, e on posset remarcar, que li
pedones esset plu decorat quam li truppes de ingenieros.

Pos li militare defilat li brigade de pumperos e depoy sequet li
scoleros de divers institutes con lor directores, preceptores e
instructores. Pos ili marchat li professionales: tallieros, chapeleros,
sapateros, barberos, carreteros, carpenteros, mureros, vitreros,
ferreros etc. Li ovreros del fabricas ne prendet parte in ti parade, ma
li mineros del vicin carbon-miniera esset representat per lor delegates
in su original costumes.

// XXX FIXED -- footballistes (old) -> futballistes (after the
// English-Interlingue Dictionary)

// XXX FIXED -- arrangeat -> arangeat

Nu sequet li sportiv organisationes e on posset vider mult conosset
championes del futballistes, boxeros, velocipedistes, canotistes etc.
In fin sequet un corso de automobilistes e motoristes.

// XXX FIXED -- anachronisme -> anacronisme

In li véspere in li vast sala municipal esset arangeat un grand festa,
u incontrat se li tot population per su eminent laboratores scientific,
politic, artistic e social. Inter li
scientistes on posset reconnosser li professores del universitá, li
romanist E., li germanist F., e li orientalist M. Omni scienties esset
representat, on videt juristes, medicos, inter ili li oculist S., li
internist A. e li dentist U. Anc conosset pictores quam li paisagist L.,
li portretist R. e li aquarellist e aquafortist K. participat al festa.
Ta esset anc li sculptor C. con su marita, li famosi actressa Lola C. On
vide li max diferent persones in amical conversation: ci un radical
socialist fonde se sub li ardent ocules del excentric baronessa S., ta
un prestro del metodistes parla con li millionario e bankero M. e li
proprietario del grand fabrica de motores, lord Ch. Li charitabil
comtessa T. sembla interessar se ye li activitá del conosset calvinistic
missionario B., un alt barbon, quel in ti desbarbat témpore es quasi un
anacronisme.

Li babillada cessat quande li trio: li pianisto Z., li cellisto Str. e
li violinista Senioretta
Ilona M. intonat un arie del local compositor G. Solmen in tard nocte li
festa trovat su fine, talmen que li reporteros havet mult a far scrir li
rapportes al rect témpore, e li redactores e correctores esset occupat
til li límite. Criticastros comprensibilmen ne esset content.

// Vocabularium {{{4
===== Vocabularium

- *alt* = high
- *arder* = to burn
- *auxiliar* = to help
- *babilar* = to chat
- *barbe* = beard
- *chapel* = hat
- *cité capital* = capital city
- *dente* = tooth
- *depoy* = thereafter
- *dormion* = sleeper, sluggard
- *ducter* = to lead
- *ferre* = iron
- *flanc* = side
- *fonder* = to melt
- *fripon* = rascal, scoundrel
- *galoppon* = runner, errand-boy
- *intern* = internal
- *jalon* = a pole
- *laceron* = a rogue, rascal
- *límite* = limit
- *marita* = wife
- *matin* = morning
- *mineros* = miners
- *mur* = wall
- *ovrero* = worker
- *paisage* = landscape
- *pede* = foot
- *pedones* = pedestrians
- *picter* = to paint
- *presc* = almost
- *retener* = to keep back
- *sapate* = shoe
- *sculpter* = to sculpt
- *talliero* = tailor
- *ultra* = besides, beyond
- *veste* = clothing
- *vitre* = glass

// Un farme in li subtropic landes {{{3
==== Un farme in li subtropic landes

// XXX FIXED -- Fixed "vu vide" -> "Vu vide"

Li farmero amabilmen monstrat nos su possessiones. Sur li corte noi
videt a dextri un grand dom. To esset li gallinería, u esset anc anates,
ganses e quelc altri avies. Detra ti voliera extendet se un pisciera
quel servit solmen quam anguilliera. Trans li bassines esset visibil li
grand cafeiera e in lontan un piniera. In li horizonte stat blu montes,
u esset un rich marmoriera, un ardesiera e altri minieras. Li sómmites
esset covrit de nive e glacieros. Del altri látere del corte esset li
orangería con mult tropic plantes e fructieros, bananieros, palmes e
exotic flores. Noi eat sur un bell planat via, de un látere de quel
extendet se un vast herbiera con bellissim trifolie e anc mult bell
flores de camp, queles injoyat li paisage. Ma li farmero totmen ne esset
content con ti malherbe, quam
il nominat les. Il haltat e prendet ex li tasca un tabaciere e presentat
nos quelc cigares: "`Vu ne posse imaginar Vos,`" dit il, "`quant me despita
li insectes! Vu vide ta li pomiera juntet a mi parc. It es presc vivid
pro li mult vermes, con queles yo guerrea nu ja quelc annus. Anc li
verdi pedicules de folies in mi adjacent pruniera, malgré omni
precautiones, expande se in un horribil maniere.`"

"`Esque Vu have fórsan formícas?`"

"`O yes. Ci es pluri formicieras in li boscage vicin. Ili es tre laborosi
insectes. Ples notar que just li formícas cultiva li pedicules, e yo
posse solmen consiliar Vos tam rapid quam possibil exterminar omni
formicieras. Ili es tre nociv animales in un fructiera.`"

// XXX FIXED -- "secuer" -> "sequer" (e in altri locos del libre)

"`Advere! Nu yo va sequer Vor consilie. Ples regardar tra ti clariera,
quel aperte nos li vide súper li mare. Ta Vu posse vider un cannoniere e
du destructores, queles crucea in ti regiones.`"

"`Quel es ti nave, quel sub segles veni al portu?`"

"`To es nor seglero, quel aporta nos salpetre por amelioration del terre.
It veni del famos nitrieras in Chile.`"

Pos har fat un promenada tra li principal branches de su proprietás, li
farmero invitat nos in su "`garsoniera,`" quam il nominat su hem nu,
proque su marita esset in un sanatoria. Quande noi hat sedentat nos in
li comod apoyieres, sub li grand castaniero, un servitor aportat sur un
tablette un chinesi teiere con tasses. Pos har trincat té e restaurat
nos un poc, noi eat regardar li industrial institutiones, li spritería,
li lavería, sapatería, carpentería e ferrería, u on fat omni ferrin
ovres til li max fin ferreríes ornamental. Specialmen simpatic esset to,
que on totmen ne videt forjettat ferrallia, quel talmen desgustant
abunda in altri tal ovrerías. Li old forjero con su long albi barbe stat
apu li incude avan li foyiere con ardent brase illuminant su energic
facie, un image del old témpore.

// Explanations {{{2
=== Explanations

// Personal suffixes {{{3
==== Personal suffixes

The following suffixes create nouns that refer to persons.

// -er- {{{4
===== -er-

(From nouns.) Similar to "`-er`" in English, refers to a person who is
engaged in a type of work, or more rarely someone who coincidentally is
engaged in a task.

====

- *molinero* = miller (*moline* = a mill)
- *barbero* = a barber (*barbe* = beard)
- *lavera* = washwoman (*lava* = washing)
- *passagero* = passenger (*passage* = passage)

====

// -ist {{{4
===== -ist

(From nouns.) The follower of an "`-ism`", or someone engaged in some
sort of artistic, ideal, scientific, military, technical or
sport-related occupation:

====

// XXX FIXED -- "B/bonapartist" and "D/darwinist" are common nouns,
// they are not included in the rules for capital letters in
// Interlingue.

- *librist* = book lover (*libre* = book)
- *socialist* = socialist (*social* = social)
- *bonapartist* = Bonapartist (follower of Napoleon Bonaparte)
- *darwinist* = Darwinist
- *oculist* = eye doctor (*ocul* = eye)
- *cavallerist* = cavalry trooper (*cavallerie* = cavalry)
- *machinist* = machinist (*machine* = machine)
- *telegrafist* = telegrafist (*telegraf* = telegraf)
- *automobilist* = automobilist

====

// -or {{{4
===== -or

(Formed from verbs.) Explained in <<_triesim_letion,lesson 3>>, a simple doer of an action.
Note the following:

====

- *laborero* = a professional worker (this is the *-er-* suffix). This
  is derived from the noun *labor*{nbsp}+ <<_er,*-ero*>>
- *laborator* = a worker in general (this is the <<_or,*-or*>>
  suffix). This is derived from <<_the_de_wahls_rule,*laborar* ->
  *labora*{nbsp}+ *t*>>{nbsp}+ <<_or,*-or*>>

====

// -ario {{{4
===== -ario

A person that is characterized through something exterior, such as a
career:

====

- *millionario* = millionaire (*million* = million)
- *missionario* = missionary (*mission* = mission)
- *functionario* = government worker (from *function*)
- *bibliotecario* = librarian (*biblioteca* = library)
- *notario* = notary (*nota* = enrollment, registration)

====

// -on {{{4
===== -on

A person characterized by an inner or natural character:

====

- *dormion* = sluggard, sleepy head (*dormir* = to sleep)
- *grison* = greybeard (*gris* = grey)
- *savagion* = savage (*savagi* = wild)
- *spion* = spy (*spiar* = to spy)

====

*-on* also serves as a suffix for objects, often implying a greater size:

====

- *cannon* = cannon (*canne* = reed)
- *ballon* = balloon (*balle* = ball)
- *galon* = braid, military stripe (*gala* = gala, festival, pomp)

====

// -ard {{{4
===== -ard

A person with a negative or criminal quality:

====

- *falsard* = counterfeiter (*fals* = false)
- *dinamitard* = terrorist who attacks with dynamite
- *mentiard* = liar (*mentir* = to lie)

====

// -astro {{{4
===== -astro

Someone unskilled at his or her profession:

====

- *medicastro* = quack (*medico* = doctor)
- *politicastro* = political hack, demagogue, politicaster (*politico*
  = politician)
- *poetastro* = rhymester, versifier, poetaster (*poete* = poet)

====

// -es- {{{4
===== -es-

Resident of a place or someone who originates from it (also as an
adjective):

====

- *franceso* = Frenchman (*Francia* = France)
- *francesa* = Frenchwoman
- *francesi* = French
- *borgeso* = bourgeois, middle-class person (*borgo* = borough, town)
- *viennesa* = woman from Vienna

====

// -essa {{{4
===== -essa

Suffix for females indicating an office or dignified position:

// XXX FIXED -- "princesse" -> "princessa"

====

- *comtessa* = countess (*comte* = count)
- *princessa* = princess (*prince* = prince)
- *imperatressa* = empress (*imperator* = emperor)
- *actressa* = actress (*actor* = actor)

====

Note that <<_or,*-or*>> drops the "`o`" in this suffix.

// Qualitative suffixes {{{3
==== Qualitative suffixes

The following suffixes form many of the nouns referring to the states
and properties of other words.

// -ie {{{4
===== -ie

An abstract state:

====

- *maladie* = sickness (*malad* = sick)
- *elegantie* = elegance (*elegant* = elegant)

====

Derivations from participles are particularly numerous:

====

- *existentie* = existence (*existent* = existing). The ending <<_ntie,*-ntie*>>
  was covered in the <<_quinesim_letion,5th lesson>>, and we can see
  that it is simply the <<_conjugation,present participle *-nt*>> plus
  <<_ie,*-ie*>>.

====

It may be used on nouns as well to make them abstract:

====

- *seniorie* = lordship (*senior* = lord, sir)
- *amicie* = friendship (*amic* = friend)
- *astronomie* = astronomy (*astronom* = astronomer) and many other
  types of sciences

====

// -tá, -té {{{4
===== -tá, -té

Quality or character, more or less equivalent to English "`-ty`":

====

- *qualitá* = quality (*qual(i)* = what a)
- *homanitá* = humanity (*homan* = human (adjective), from *hom* =
human, (noun))
- *amabilitá* = amiability, kindness (*amabil* = amiable, kind)
- *membritá* = membership (the status of being a member)

====

Words that refer to a group of people or things use *-té* instead of
*-tá*:

====

- *homanité* = humanity, as in the grouping of people as a whole.
  *homanitá* above refers to the character of being human (humanity in
  the sense of showing kindness and decency)
- *societé* = society (*socio* = associate, member)
- *membrité* = membership (all the members of something)

====

// XXX TODO -- Transalate:

// -tá or -té? {{{5
====== -tá or -té?

Besides the above, *-té* is much more limited in scope and any
doubtful cases are given the *-tá* ending, such as *universitá*
(university), which is neither the character of being a universe
(*universe*{nbsp}+ *tá*) nor a collection of universes
(*universe*{nbsp}+ *té*). In the same way, society (*societá*) is not
simply the state of being a *socio*, but it is also not a collection
of them (a society is not simply a collection of associates) and thus
it becomes *societá*. Rule of thumb: when in doubt, it's probably
*-tá*.

// -ore {{{4
===== -ore

1. (from verbs): a state of feeling, activity, temperature, etc.
+
====
- *amore* = love (from *amar*, to love)
- *terrore* = terror (from *terrer* = to frighten)
- *calore* = heat (*caler* = to be hot)
====

2. (from adjectives): size, value:
+
====
- *longore* = length (*long* = long)
- *grandore* = size (*grand* = large)
====

// -esse {{{4
===== -esse

Special property or condition, most similar to English "`-ness`". Examples:

====

// XXX FIXED -- "being large" -> "largeness"

- *altesse* = highness (*alt* = high, *altore* = height, *altitá* =
  the quality of being high)
- *grandesse* = greatness, magnitude (*grand* = large, *grandore* =
  size, *granditá* = largeness)
- *yunesse* = youth (*yun* = young, *yunitá* = youngness, *yunité* =
  the youth)

====

This is also the suffix used for bombastic titles such as "`your
Highness`" (*Vor Altesse*).

// Local and collective suffixes {{{3
==== Local and collective suffixes

// XXX FIXED -- Titul: "Local e colectiv sufixes" -> Local and
// collective suffixes" (anglesi)

// -ia {{{4
===== -ia

A frequent suffix for the names of places and countries:

====

- *Germania* = Germany (*german* = german)
- *dominia* = dominion (*dómino* = master)
- *abatia* = abbey (*abat* = abbot)
- *auditoria* = auditorium (*auditor* = hearer)

====

// -atu {{{4
===== -atu

A legal, social, or public institution, state, or office (also location,
time, and territory). Often corresponds to English "`-at`" or "`-iat`":

====

- *viduatu* = widowhood (*vidua* = widow)
- *celibatu* = celibacy (*celibo* = bachelor, single man)
- *proletariatu* = proletariat (*proletario* = a proletarian)
- *directoratu* = directorship (*director* = director)
- *secretariatu* = secretariat (*secretario* = secretary)
- *califatu* = caliphate (*calif* = caliph)
- *episcopatu* = episcopate (office of a bishop, from *epíscop* =
  bishop)

====

// -eríe {{{4
===== -eríe

An occupation and its activities. As -*ería*, it refers to the actual
location. Both are actually formed from the *-er-* suffix (doer of an
action), then <<_ie,*-ie*>> as above for the quality, or <<_ia,*-ia*>> for the
location.

====

- *vitreríe* = glasswork, glassware (*vitre* = glass, *vitrero* =
  glassworker)
- *vitrería* = a glassworks (the place)

====

Beyond the occupation, it also refers to a character trait and its
manifestations, same as in English "`-ery`":

====

- *coquetteríe* = coquetry (flirtation, from *coquett* = coquettish or
  flirtatious)
- *bigotteríe* = bigotry (*bigott* = bigoted)
- *diaboleríe* = devilry (*diábol* = devil)

====

// -iera, -iere, -iero {{{4
===== -iera, -iere, -iero

These three are best learned together.

- *-iera*: a vast location containing something
- *-iere*: a vessel or container holding something
- *-iero*: carrying something (forms trees as well — "`carriers`" of
  their fruits)

[[_iere]]
*-iere* words:

====

- *cigariere* = cigar case (*cigar*{nbsp}+ iere)
- *tacabiere* = a tobacco case (*tabaco*{nbsp}+ iere)
- *candeliere* = candle box (*candel* = candle)

====

[[_iero]]
*-iero* words:

====

- *pomiero* = apple tree (*pom* = apple)
- *orangiero* = orange tree (*orange* = orange)
- *glaciero* = glacier (*glacie* = ice)
- *candeliero* = candlestick

====

[[_iera]]
*-iera* words:

====

- *pisciera* = fish pond (*pisc* = fish)
- *torfiera* = peat bog (*torf* = peat)
- *formiciera* = anthill (*formíca* = ant)

====

// -uore {{{4
===== -uore

A place or device where something is done:

// XXX FIXED -- "trottuor" -> "trottuore" (which is the form used in
// the text section).

====

- *trottuore* = sidewalk (*trottar* = trot, jog)

====

// -ade {{{4
===== -ade

A consecutive, ordered series or certain amount of something:

====

- *colonnade* = colonnade (*colonne* = column)
- *boccade* = mouthful (*bocca* = mouth)

====

// -allia {{{4
===== -allia

An unordered or pile of something:

====

- *antiquallia* = old junk (*antiqui* = old)
- *canallia* = pack of dogs (*can(e)* = dog)

====

// -arium {{{4
===== -arium

A more scientific or specialized grouping of something.

====

- *dictionarium* = dictionary (*diction* = a diction)
- *herbarium* = herbarium (*herbe* = grass, herb)
- *planetarium* = planetarium (*planete* = planet)

====

// Settesim letion {{{1
== Settesim letion

// XXX FIXED -- "Setesim" -> "Settesim"

// Textus {{{2
=== Textus

// Li intern veritá {{{3
==== Li intern veritá

To quo, secun li opinion de frances e angles letores, distinte Goethe,
es un qualitá, quel il divide con su nation – constant referentie a
intern veritá. In Anglia e America existe reverentie por talent, e li
publica es satisfat, si li talent es exercit pro un cert fixat o
comprensibil interesse o partie, o in regulari oposition contra un de
tales. In Francia existe un plu grand delicie por intellectual
brilliantie, pro it self. E in omni ti landes talentat homes scri
talentosimen. It es suficent, si li intercomprension es ganiat, li
contact attinger, tant columnes, tant hores ocupat in un vivaci e
honorabil maniere. Al german intellectu manca li frances brilliantie, li
fin practical comprension del angleses, e li american aventura; ma it
have un cert honestie, quel nequande resta in superficial performantie,
ma questiona constant: pro quel scope? Un german publica
demanda controlant sinceritá. "`Ci es un activitá de pensada – ma por
quo? Quo vole li mann? De u, de u omni ti pensas?`"

Sol talent ne posse far un autor. It es necessi que existe un mann detra
li libre, un personalitá qui per su orígine e su qualitá da garantíe a
ti doctrines queles il exposi, e qui existe por vider e constatar li
coses in ti e ne in un altri maniere, qui defende factes proque ili es
factes. Si il ne posse expresser se corect hodie, li sam coses supervive
e va explicar se deman. Un charge jace sur su mente, li charge de un
veritá explicand – plu o minu comprendet, e it constitue su ocupation e
su vocation in li munde soluer li problemas e far les conosset. Quo
importa que il mistrotta e balbutia, que su voce es crud e mis-sonant,
que su metodes e su tropes es ínadequat? Ti mission va trovar metode e
images, articulation e melodie. Etsi il vell esser mut, it vell parlar.
Si ne – si ne vell exister un tal divin parol che li mann – quo noi
cuida, quam fluent, quam brilliant il es...

Emerson

// Vocabularium {{{4
===== Vocabularium

- *atinger* = to attain
- *aventura* = adventure
- *balbutiar* = to stutter
- *charge* = charge, burden
- *crud* = crude
- *cuidar* = to take care of
- *delicie* = a delicacy
- *demandar* = to demand, to request
- *distinter* = to distinguish
- *exercir* = to exercise
- *explicar* = to explain
- *exposir* = to expose
- *ganiar* = to win
- *orígine* = origin
- *performar* = to perform
- *referer* = to reference
- *reverer* = to revere
- *satisfar* = to satisfy
- *scope* = a goal
- *sol* = alone
- *sonar* = to sound
- *trope* = figure of speech, trope
- *vocar* = to call
- *voce* = voice

// XXX FIXED -- nesting of quotes and parens (maybe not after
// the rule in English, but more logical):

[[_note_about_nd]]
NOTE: The <<_nd,*-nd*>> suffix (*-and* for *-ar* verbs, *-end* for *-er* and *-ir* verbs)
adds the meaning "`thing to be (verb)ed`". This is where words
like *dividende* (thing to be divided, from *divider*) come from, which
adds a certain obligation (a thing to do = a thing one should do).  As
an adjective it can also take the <<_i,*-i*>> at the end for euphony. The
above *un veritá explicand* thus means "`a truth to be explained`".
Another way to say the same would be *un veritá a explicar*.

// Aforismes {{{3
==== Aforismes

// XXX FIXED -- "su Due" -> "su Deo"

[quote, Spinoza]
____
Si li triangules vell posser pensar, ili vell imaginar su Deo quam
triangulari.
____

[quote, Montesquieu]
____
Li capes de grand homes diminue, si plures de ili conveni; plu mult li
sagies, plu minimal li sagesse.
____

[quote, Nordau]
____
Moventie, progresse, esperantie, vive, omnis es solmen sinonimes de
optimisme. Li antiqui romano qui pensat li proverbie: durant que yo
spira, yo espera, ha concentrat li filosofie del processe del vive, e
dat a un biologic fundamental veritá li forme de un classic calambure.
____

[quote, Kant]
____
Li damas ne veni in li ciel, nam ja in li Apocalipse es dit in un loc:
It esset silent durant un demí seconde. To ne es pensabil ta, u damas es
present.
____

// Vocabularium {{{4
===== Vocabularium

- *angule* = angle
- *calambure* = wordplay, pun
- *loc* = place
- *sagie* = sage
- *siler* = to be silent (to make no sound)
- *spirar* = to breathe

// Li evangelie del labor {{{3
==== Li evangelie del labor

It existe du folles in li munde. Li un es li millionario, qui crede, que
il posse acumular real potentie per collecter moné; li altri es li
glatt-rasat agitator, qui crede, que si il solmen vell posser prender li
moné de un classe e dar it a un altri, li social maladies vell esser
curat. Ili es ambi sur fals via. Mani del max successosi ho-temporan
collectores de moné ne ha augmentat, ni per minimalissim summa, li
richesse del homanité. Esque cart-luderos contribue al augmentation del
richess del munde?

Si noi omni vell partiprender in li productiv labor, intra li límites de
nor capacitá, on vell posser questionar solmen pri to, esque chascun va
reciver to quo il besona. Un real manca del vital necessitás – ne un
fals manca pro absentie de tintinant metallic monetes in nor tascas –
posse depender solmen de ínsuficent production, e ti es, in su órdine,
tro sovente un consequentie de mancant saventies pri to quo e qualmen on
deve producter.

// XXX FIXED -- arrangear -> arangear

Ja in comensa noi deve fixar quam facte: li terra es capabil producter
decent vive a chascun; ne solmen nutrition ma omnicos quo noi besona;
nam omnicos veni del terra. It es possibil arangear li labor, li
production, li distribution e li recompensation talmen, que a chascun
qui fa su deventie, es garantit un parte del resultate in conformitá al
exact justicie.

Omnicos es possibil. Crede es li substantie de coses pri queles noi
espera, e li testimonie pri coses queles ne es visibil.

Henry Ford

// Vocabularium {{{4
===== Vocabularium

- *acumular* = to accumulate
- *augmentar* = to augment, to increase
- *capabil* = capable
- *capacitá* = capacity
- *deventie* = a duty
- *folle* = a fool
- *luder* = to play
- *monete* = a coin
- *partiprender* = to participate, to take part
- *rasar* = to shave
- *substantie* = substance
- *tintinar* = to jingle

NOTE: *mani* before a singular means "`many a`", while before a plural
it means "`many`" (same as *mult*).

// Un lettre {{{3
==== Un lettre

Cosmopolis, 12-esim marte 1930.

Mi car amíco.

Yo mersia Vos cordialmen pro Vor amabil lettre de 10-esim ho-mensu. Yo
joya leer, que anc Vu have interesse por li lingue international
auxiliari, e yo constata, que yo esset rect, quande yo suposit, que Vu
ne posse esser índiferent pri un question quel have grandissim
importantie por li future de nor civilisation. Quam omni novones in li
interlinguistica Vu comensa per decreter. In Vor curt lettre de quelc
lineas Vu expresse Vor opiniones e exposi tant postulates concernent li
lingue auxiliari, que, si Vu self vell provar satisfar les, Vu vell
haver suficent occupation por quelc cent annus. Vu di, que li lingue
deve esser ne europan; ma universal, i. e. un
sintese de omni lingues existent sur li terra. Vu oblivia, que p. ex. li
lingues chinesi e german es tam diferent, que un lingue, quel deve
satisfar Vor postulate, vell esser quasi un hibride inter harengo e
sparro. Vu di, que li lingue deve esser idealic, i. e. li max perfect
linguistic instrument pensabil. Vu oblivia, que ne omnicos pensabil es
possibil.

Idealic lingues es, secun mi opinion, tam ínpossibil quam idealic
states. Ili apartene ambi a Utopie. Un idealic lingue sam quam un
idealic state es possibil solmen ta u vive idealic homes. Vu di adplu,
que li lingue deve esser absolut regulari, nam tande it vell esser max
facil. Yo ne posse comprender, pro quo regularitá vell esser identic con
facilitá. Li lingue ne es solmen grammatica. It posse esser facil
aprender simplic regules, ma it es tre desfacil memorar e usar
ínaccustomat paroles. Quant minu un nov lingue chargea li memorie del
parlantes, tant plu facil it es.

It existet unquande témpores, quande homes credet seriosimen, que on
posse crear, constructer e formar nov lingues arbitrarimen, ex
profundore de su animas, secun principies, queles ili self inventet. It
eveni ancor sovente, que on audi simil opiniones expresset de homes
íniniciat. Plu valorosi quam inventer es constatar li ja factic existent
international lingue, quel vive latent in li national lingues del
occidental cultura. Li international vocabularium es tre rich, e pro que
li scientie e technica ja possede un international terminologie, ili ne
posse acceptar un altri lingue international quam un tal quel conserva
ti internationalitá.

Vor devoet

Y{dot} Z{dot}

// Vocabularium {{{4
===== Vocabularium

- *acustomar* = to accustom
- *adplu* = moreover
- *chargear* = to charge, to burden
- *devoer* = to be devoted
- *esser rect* = to be right (*haver rason* is another way to say it)
- *exposir* = to expose
- *harengo* = herring
- *iniciat* = initiated
- *mersiar* = to thank
- *obliviar* = to forget
- *ocupation* = occupation
- *sam quam* = same as
- *sparro* = sparrow
- *suposir* = to suppose

// Explanations {{{2
=== Explanations

// XXX FIXED -- Hierarchy:

// Adjectival suffixes {{{3
==== Adjectival suffixes

The three most used adjectival suffixes are:

// -al {{{4
===== -al

A general suffix showing a relationship or dependency: *national* from
*nation*, *central* from *centre*, *diferential* from *diferentie*,
etc.

// -ic {{{4
===== -ic

Being so, possessing properties of the word:

====

- *energic* (energetic) from *energie*
- *fantastic* from *fantaste* (a fantast, someone with eccentric or
  fanciful ideas)

====

NOTE: Greek words ending in "`-ma`" take a "`t`", and those ending in "`-se`" turn
the "`s`" into a "`-t`" ("`xe`" also counts as it is pronounced "`cse`"). Thus:

====

- *sistematic* from *sistema*
- *problematic* from *problema*
- *hipnotic* from *hipnose*
- *sintactic* from *sintaxe*

====

From the adjective <<_ic,*-ic*>> we derive nouns with:

// -ica and -ico {{{4
===== -ica and -ico

*-ica* refers to the name of the science or art in general, and
*-ico* to the person practicing it. This is one situation where the *-o*
does not necessarily denote a male.

====

- *logic* = logical
- *logica* = logic
- *logico* = logician
- *matematic* = mathematic
- *matematica* = mathematics
- *matematico* = mathematician
- *politic* = political
- *politica* = politics
- *politico* = politician
- *critic* = critical
- *critica* = criticism
- *critico* = critic

====

// What about -ical? {{{4
===== What about -ical?

Generally, it is a good idea to resist the urge to express every "`-ical`"
English word with another *-ical* in Interlingue (just <<_ic,*-ic*>> is
preferred). But this is another situation where you can for extra
precision, and a subject mentioned in Cosmoglotta before. Because <<_ica_and_ico,*-ica*>>
as shown above refers to the entire branch of art or science,
<<_al,*-al*>> can make an adjective referring to it. Some examples where <<_ic,*-ic*>>
or *-ical* could be preferred:

====

- *un jardin botanic:* a botanical garden
- *un tractate botanical* = a botanical treatise (a treatise relating
  to botany, the science)
- *precision matematic* = mathematical precision
- *curiositá matematical* = a mathematical curiosity (a curiosity that
  mathematicians are interested in)
- *un progression aritmetic* = an arithmetic progression
- *un problema aritmetical* = an arithmetical problem (a problem that
  arithmeticians are interested in)

====

On a related note, beware of words where English is the odd man out such
as *energic* (energetic) where only English has the added "`-et-`" in the
middle.

// -aci {{{4
===== -aci

Tending to (similar to English "`-acious`"):

====

- *mordaci* = mordacious (*morder* = to bite)
- *tenaci* = tenacious (*tener* = to hold)
- *vivaci* = vivacious (*viver* = to live)

====

// -an {{{4
===== -an

Belonging to (often made into nouns with *-ano*, *-ana*, *-ane*):

====

// XXX FIXED -- "(hom = human)" -> "(hom = a human)". The previous
// identical translations "human" could be confusing.

- *american* = American (*America* = America)
- *homan* = human (*hom* = a human)

====

// -ari {{{4
===== -ari

According to, fitting, belonging to (English "`-ar`"):

====

- *regulari* = regular (*regul* = rule)
- *populari* = popular (*popul* = people)

====

// -at {{{4
===== -at

(On nouns.) Provided with something:

====

- *foliat* = leafed (*folie* = leaf)
- *barbat* = bearded (*barbe* = beard)

====

// -ut {{{4
===== -ut

Very rich in, exuberant:

====

- *barbut* = heavily bearded (barbute)
- *sandut* = sandy
- *armut* = heavily armed

====

// -atri {{{4
===== -atri

A resemblance but not entirely of the same quality (similar to English
"`-ish`"):

====

- *verdatri* = greenish (*verd* = green)
- *spongiatri* = spongy (*spongie* = sponge)

====

// -esc {{{4
===== -esc

(Of people.) Similar to, possessing similar qualities to (similar to
English "`-esque`")

====

- *infantesc* = childlike (*infant* = child)
- *gigantesc* = giantesque (*gigante* = giant, *gigantic* = gigantic)

====

// -bil {{{4
===== -bil

(Transitive verbs): what can be done (transitive verbs) what one can do.
*-ar* verbs: *-abil*, *-er* and *-ir* verbs: *-ibil*.

====

- *navigabil* = navigable (*navigar* = to navigate)
- *formabil* = formable (*formar* = to form)
- *audibil* = audible (*audir* = to hear)
- *horribil* = horrible (*horrer* = to be horrified, to dread)
- *íncredibil* = unbelievable (*creder* = to believe)
- *durabil* = durable (*durar* = to last)
- *ínponderabil* = unthinkable (*ponderar* = to ponder)
- *ínperceptibil* = imperceptible (*percepter* = to perceive)
- *ínexpressibil* = unexpressable (*expresser* = to express)
- *visibil* (from the perfect stem) = visible (*vider* = to see)
- *explosibil* (from the perfect stem) = explodable (*exploder* = to explode)

====

// -in {{{4
===== -in

Denotes ancestry, origin:

====

- *argentin* = silber (*argente* = silver)
- *florentin* = Florentine (from Florence, *Florentia* = Florence)
- *svinine* = pork (*svin* = pig)

====

// -osi {{{4
===== -osi

Rich in, full of:

====

- *famosi* = famous (*fama* = fame)
- *musculosi* = muscled (*muscul* = muscle)
- *respectosi* = respectful (*respecte* = respect)
- *spinosi* = thorny (*spine* = thorn)

====

The similar suffixes <<_iv,*-iv*>> and <<_ori,*-ori*>> were mentioned
in <<_triesim_letion,lesson 3>>.

This finishes up the main suffixes seen in Interlingue for forming new
words. On top of this are many other much less productive affixes that
show up from time to time and are worth noting:

// -id {{{4
===== -id

having the qualities of a verb:

====

- *timid* = timid (*timer* = to fear, *timore* = fear)
- *frigid* = cold, frigid (*friger* = to feel cold, *frigore* = cold)

====

// -nd {{{4
===== -nd

Mentioned once in a <<_note_about_nd,note above>>: what is to be done.

====

- *quo esset demonstrand* = what was to be demonstrated (Latin *quod
  erat demonstrandum*)
- *dividende* = a dividend
- *examinando* = an exam-taker (one who is to examine).

====

// Divers affixes {{{3
==== Divers affixes

// XXX FIXED -- Titul: "Divers afixes" -> "Divers affixes" (anglesi)

Here are some more Latin- or Greek-derived affixes that are seen in
words in Interlingue and most other western European languages:

// anti- {{{4
===== anti-

Against.

====

- *Anticristo* = Antichrist
- *antitoxine* = anti-toxin
- *antisocial* = antisocial, asocial

====

// arch(i)- {{{4
===== arch(i)-

Highest, over-.

====

- *archiepiscop* = archbishop
- *archángel* = archangel
- *archifripon* = an "`arch rogue`"
- *archinull* = total zero, huge loser

====

// auto- {{{4
===== auto-

Auto-, self.

====

*automobile*, *autobiografie*

====

// non- {{{4
===== non-

Non.

*non-agression, nonsense*

// pan- {{{4
===== pan-

Pan-.

====

*paneuropa*, *panslavist*

====

// proto- {{{4
===== proto-

Proto.

====

*protogerman*, *prototipe*

====

// pseudo- {{{4
===== pseudo-

Pseudo, false (note: "`p`" is not silent!)

====

- *pseudo-Cristo* = false Christ
- *pseudoscientie* = pseudoscience

====

// semi-, hemi- {{{4
===== semi-, hemi-

Half.

====

*semivocale, semicólon, hemisfere*

====

// tele- {{{4
===== tele-

Tele-, far.

====

*television, telemicroscope*

====

// -cide {{{4
===== -cide

Killer of.


====

*patricide, suicide, homicide*

====

// -fer {{{4
===== -fer

Bringing, bearing.

// XXX FIXED -- "amammal"

====

- *fructiferi* = fruit-bearing
- *mammifere* = a mammal

====

// -file {{{4
===== -file

-phile, loving.

====

*germanofile*

====

// -fobe {{{4
===== -fobe

Fearing.

====

*germanofobe*

====

// -oide {{{4
===== -oide

-oid, resembling.

====

*negroide, mongoloide, caucasoide, romboide, elipsoide*

====

// Word composition {{{3
==== Word composition

// XXX FIXED -- Titul: "Parol-composition" -> "Word composition"

Words can be joined together in a variety of ways.

1. Through simple joining, either with or without a hypen. a)
Without a hyphen: *postcarte*, *manuscrite*. b) With a
hyphen: *Nord-Europa*, *automobil-garage*

2. With the vowels "`i`" or "`o`" between
words: *uniform*, *unilateral*, *centimetre*, *microcosmo*, *aeroplan*.

The imperative of a verb can also be used to join words
together: *portamoné* (a wallet, lit. a carry-money), *parapluvie* (an
umbrella, lit. a block-rain), *gardarobe* (a wardrobe, lit. a
guard-robe).

// Word families {{{3
==== Word families

// XXX FIXED -- Titul: "Parol-families (word families)" -> "Word
// families"

You might have noticed that properly applying the above derivation rules
almost always produces existing international words with the same
meaning. New ones can be made, as that happens consistently in natural
languages. In the few cases where a regularly formed derivation form
differs substantially from an existing international word, both forms
are permitted.
Examples:

====

- *noctal* = *nocturn*
- *terral* = *terrestri* (terrestrial),
- *cielal* = *celest* (celestial)
- *patrin* = *paternal* (paternal).

====

Here are some example of how international words are created by
deduction and composition from simple elements in the derivation of
Interlingue:

====

- *protecter* = to protect (protect-er)
- *protectoratu* = a protectorate (protect-or-atu)
- *protectoria* = a house for orphans (protect-or-ia)
- *protection* = protection (protect-ion)
- *protectionisme* = protectionism (protect-ion-isme)
- *protectionist* = protectionist (the person) (protect-ion-ist)
- *protectionistic* = protectionistic (adjective) (protect-ion-ist-ic)
- *protectiv* = protective (protect-iv)
- *star* = to stand

*stabil, instabil, stabilitá, ínstabilitá, stabilisar, stabilisation,
stabilisator; station, stationar, stationari, stationario; state, statu,
statue, statuarium, statuette, statuer, statute, statuari, static,
statica; statist; statistic, statistica, statistico; stativ; statura;
constar, constant; constantie, constatar; restar, restantie; distar,
distantie; circumstar, circumstantie*; etc.

====

Plus some others if one considers that the "`-stituer`" ending is also
related to star: *constituer, constitution, instituer, institute,
institution, institutor, restituer, restitution, substituer, substitute,
substitution*,

// Ottesim letion {{{1
== Ottesim letion

// Textus {{{2
=== Textus

// Un somnie {{{3
==== Un somnie

// XXX FIXED -- nested quotes: double for the telling, single for the
// speeches in the telling.

"`In facte, yo havet un drolli somnie just nu,`" racontat un irlandeso.
"`Yo revat, que yo esset in Roma e visitat su Sanctitá, li Papa. Apen yo
hat tappat sur li porta, quande il self apertet it. – '`A, Pat, es it Vu,
qui ha venit, o alquí altri?`' – '`Advere, Vor honore, it es yo e nequí
altri.`' – '`Ples venir con me in li superior etage!`' il dit me. E ta
esset un separat chambre, bellissim equipat, quel yo ne ha videt jamá.
'`Ples seder,`' dit su Sanctitá, '`quo Vu vole?`' – Yo meditat durant un
momente, e in fine yo dit: '`Un glass de fort trincage.`' – '`Deve it esser
frigid o calid?`' – '`Calid,`' yo respondet. E su Sanctitá departet por
aportar li trincage, ma il esset absent tro long e interim yo avigilat
me. Quam yo nu repente, que yo ne hat petit le dar me it frigid.`"

// Vocabularium {{{4
===== Vocabularium

- *apen* = hardly, barely, just as
- *avigilar* = to awaken
- *departer* = to depart
- *droll(i)* = funny
- *equipar* = to equip
- *honore* = honor
- *interim* = meanwhile
- *jamá* = ever, never
- *meditar* = to meditate
- *Papa* = Pope (note: *papá* = papa, daddy)
- *racontar* = to tell (a story, etc.)
- *repenter* = to repent
- *somnie* = dream
- *tappar* = to tap, to knock
- *trincage* = a drink

// Aforismes {{{3
==== Aforismes

// XXX FIXED --
// "de mani autore es acceptat del publica – quande il" ->
// "de mani autor es acceptat del publica – quande il"

Pri un cose noi omni concorda: ne existe plu abominabil erras quam tis
del altres.

It es sovente plu facil pardonar un injurie quel noi ha causat a un
altri hom.

Li opinion de mani autor es acceptat del publica – quande il self ha
abandonat it ja de long.

Mani nómina se idealist: proque il vole viver ne por, ma per un idé.

Un conosset patriot ha dit: "`Yo ne comprende que alcun hom vole nascer
quam extraniano.`"

On posse tacer pro divers motives: anc pro to que on have necos a dir.

Homes (anc Vu ha certmen constatat it) have plu de témpore, quande ili
vole alquicos de nos, quam quande noi vole alquicos de ili.

A un yun mann, qui fanfaronat pri su saventies, un old mann dit: "`Vu es
felici, qui vive ancor in ti etá, quande on save omnicos.`"

Quam ínprudent it vell esser, si noi vell dir a nor conossetes: "`Yo have
exact tant interesse por Vos quant Vu por me.`"

Quande un hom di: "`Un de nos erra,`" yo save strax, quem il alude.

Certmen Vu conosse ti person, qui quande on parla pri un altri hom,
comensa strax parlar pri se self.

Otto Weiss

// Vocabularium {{{4
===== Vocabularium

- *abominabil* = abominable
- *aluder* = to alude
- *concordar* = to agree
- *etá* = age
- *fanfaronar* = to boast, to talk up
- *injurie* = injury, insult
- *mani* = many a
- *tacer* = to be silent (to say nothing)
- *ínprudent* = imprudent, careless

// Bon respondet {{{3
==== Bon respondet

"`Ples pardonar me, Senior,`" dit un tre seriosi aparent mann a un jolli
hom, qui stat fumant un grand cigare sur li strada, "`quant cigares Vu
fuma in un die?`"

// XXX FIXED -- "li response esset" -> "su response esset"

"`O,`" su response esset, "`fórsan quar o quin.`"

"`Quin cigares in un die fa triant quin in un semane, circa un cent
quinant in un mensu, e plu quam mill ott cent in un annu. Ples supposir,
que Vu vell har economisat omni ti moné, quel Vu ha expenset a tabac! Vu
vell posser fórsan esser li possessor de ti bell micri dom, quel Vu vide
ci a levul.`"

"`Esque it es Vor, mi Senior?`"

"`O no, yo ne possede un dom.`"

"`Esque Vu save, de qui it es?`"

"`No.`"

"`It es mi!`"

NOTE: *li mi, li vor* etc. is also used.

// Vocabularium {{{4
===== Vocabularium

- *a levul* = on the left
- *fumar* = to smoke
- *jolli* = jolly
- *seriosi* = serious 

// Aforismes {{{3
==== Aforismes

[quote, Montaigne]
____
To quo yo time max mult, es li timore.
____

[quote, O. Wilde]
____
Ti qui es fidel, conosse solmen li trivial láteres del amore. Solmen li
ínfidel conosse li tragedies de it.
____

[quote, Moszkowski]
____
Existe international artistes qui nequande aprende un lingue perfect:
ili es li nativ extranianos.
____

[quote, Nietzsche]
____
Li fanatisme es li sol fortie de vole quel anc li debiles e li íncertes
posse manifestar.
____

[quote, Berkeley]
____
Poc homes pensa, ma omnes vole haver opiniones.
____

[quote, Schopenhauer]
____
Un mann qui interprende viver per li favor del musas, yo vole dir, per
su poetic talentes, apari me in alcun maniere quam un puella qui vive
per su charmes.
____

[quote, Schopenhauer]
____
Dilettantes, dilettantes, talmen tis qui cultiva un scientie o un arte
pro amore o joy pri it, pro lor delecte, es nominat con despecte de tis
qui ocupa se pri ili pro profite, proque les delecte solmen li moné,
quel es ganiabil per to.
____

[quote, Grillparzer]
____
In mani landes on have ti opinion: tri ásinos constitue junt un
inteligent hom. Ma to es profundmen fals: pluri ásinos in concret fa li
ásino in abstract, e it es un horribil animale.
____

[quote, Jean Paul]
____
Un solari sistema es solmen un punctuat profil del mundan genie, ma un
homan ocul es li miniatura del solari sistema.
____

// Vocabularium {{{4
===== Vocabularium

- *animale* = animal
- *constituer* = constitute
- *debil* = weak
- *despecte* = scorn
- *fidel* = faithful
- *interprender* = to undertake
- *puella* = girl
- *ásino* = donkey, ass

// Iguanodon {{{3
==== Iguanodon

Durant mi viage a Stockholm yo visitat anc li natur-historic muséo e yo
esset vermen impressionat per li granditá opressiv del squelette del
antediluvian iguanodon. Benque yo conosset teoricmen li dimensiones e li
grandore de ti prehistoric gigant, li realitá superat omni
imaginationes. Li longore del caude es tam grand, que it ne have
spacie in li grand sala, ma on ha devet divider it e posir li
detra-parte paralel al squelette.

Su altesse, li prince de S., intrat con mult grandesse in li sala del
iguanodon, ma bentost il esset un modest micri hom apu li colossal
animale. Un dama regardat li gigant e dit: "`It es ínpossibil. Etsi un
tal animal ha vivet, qualmen on posse saver su nómine?`"

// Vocabularium {{{4
===== Vocabularium

- *animale* = animal
- *benque* = even though
- *caude* = tail
- *diluvie* = flood
- *impressionar* = to impress
- *spacie* = space
- *superar* = to surpass
- *viage* = journey

// Explanations {{{2
=== Explanations

// Pronouns {{{3
==== Pronouns

In the preceding texts we have become very familiar with many of the
pronouns in Interlingue. Let's look at them as a whole.

// Personal pronouns {{{4
===== Personal pronouns

// XXX FIXED -- formar -> formal

- *yo, me* = I, me
- *tu, te* = you, you (singular and informal)
- *noi, nos* = we, us
- *vu, vos* = you, you (plural or formal)
- *il, le* = he, him
- *ella, la* = she, her
- *it, it* = it, it
- *ili, les* = they, them

// Possessive pronouns {{{4
===== Possessive pronouns

- *mi* = my
- *tui* = your
- *su* = his, her, its
- *nor* = our
- *vor* = your
- *lor* = their

*Se* is used to form reflexive pronouns, and *unaltru* means "`each
other`".

Some examples:

// XXX FIXED -- Dots have been added after the convention used in this
// book and also in the original german transcription, from which this
// block of examples seems to be an exception without a reason.  The
// nesting of ending dots, parens and quotes is not totally right in
// English, though, but simpler and more logical.

====

- *Il da la su parol. = Il da su parol a ella.* = He gives her his
  word.
- *Yo da te mi parol. = Yo da mi parol a te.* = I give you my word.
- *Li diferentie inter me e te.* = The difference between me and you.
- *Li diferentie inter mi e tui.* = The difference between mine and
  yours.
- *Li nores victet li vores.* = Ours (plural) beat yours (plural).  If
  *noi* had had one and *vu* had also had had one, it would be
  expressed as *Li nor victet li vor*.
- *Yo es tua e tu es mio.* = I am yours and you are mine (said by a
  woman to a man).
- *Ples far lu tui!* = Please do yours! (remember *lu* = "`the thing
  which is`").

====

Note that after prepositions the pronouns except *me* and *te* are in
their subject form). This has long been a subject of discussion, with
some preferring outright object forms (*con le, a la, sin les*) and
others preferring the nominative (*con il, con ella, con ili*). But
interestingly nobody has ever preferred the forms *con yo, con tu*,
only *con me, con te*. Rule of thumb: always *me* and *te*, the others
are up to personal preference. Whether the community will decide on
one form over the other is tough to say: even English has yet to do so
in cases such as "`You are taller than _me_`" (than{nbsp}+ pronoun)
vs. "`You are taller than _I_`" (short for "`than I am`").

// Demonstrative and determinative pronouns {{{4
===== Demonstrative and determinative pronouns

- *ti* = this, that
- *tis* = these, those
- *tal* = such, such a
- *tales* = such (plural)
- *to* = that (in general)
- *tant* = so much, so

*ti* is very general, which is why it is translated as
both *this* and *that*. To add precision, add *ci* (here)
or *ta* (there) after: *ti ci* (this), *ti ta* (that).

====

- *Ti du crayones es li mis: ti ci es curt e ti ta es long; ples
  prender tis.* = These two pencils are mine: this one is short and
  that one is long: please take these.
- *Il es sempre tal.* = He's always like that.
- *Yo ama tal homes.* = I like such people.
- *Vu ne ama tales?* = You don't like such (people)? (Here *tales* could
  be something else besides people as it is not specified)
- *To es ver.* = That's right.
- *To es tant ver.* = That's so right.

====

Interrogative and relative pronouns

- *qui?* = who?
- *quem?* = whom?
- *quel?* = which?
- *qual?* = how?
- *quo?* = what?
- *quant?* = how much?

Examples:

====

- *Qui es ta? It es yo.* = Who is there? It's me.
- *De qui es ti chapel?* = Whose hat is this?
- *Quem tu dat li moné?* = To whom did you give the money? (*a qui* is
  another way to say the same thing)
- *Quem Vu saluta?* = Whom are you greeting?
- *Quem tu ama max mult?* = Whom do you love the most?
- *Quel adresse Vu have nu?* = What/which adress do you have now?
- *Qual es li aqua hodie, calid o frigid?* = How is the water today,
  hot or cold?
- *Quo es to?* = What is that?

====

The most used relative pronouns are *quel* (singular) and *queles*
(plural). For people *qui* is also used in the singular and plural, and
for objects and abstract things also *quo*.

// XXX FIXED -- "fa on constant" -> "fa un constant"
// XXX FIXED -- "progress que" -> "progress que"

====

- *Ti qui* (or *quel*) *es pigri ne fa progresse.* = One who is lazy
  makes no progress.
- *Beat es tis qui* (or *queles*) *ne vide, ma támen crede.* = Blessed
  are those who do not see, but believe.
- *It es un cose quel* (not *qui*) *yo ne comprende.* = It's something
  I don't understand.
- *Yo ne comprendet to quo Vu dit.* = I didn't understand what you
  said.
- *Nor lingue fa un constant progress quo* (= *quel facte*) *tre joya
  me*.  = Our language makes constant progress, which much pleases me.
- *Qual compositor, tal musica.* = As the composer, so the music.
- *Quant vive, tant espera.* = As long as there is life, there is
  (that much) hope.

====

NOTE: Sometimes users of Interlingue do not bother to pluralize *quel*:
*tis, quel…* instead of *tis, queles*. *Queles* in the plural is one
of those words that looks more proper when used but not outright
deserving of a correction when not.

// Various other pronouns {{{4
===== Various other pronouns

Note that many of these are simply formed by prefixing *al-*, *ne-*,
etc. to other existing pronouns. They are not accented.

- *on* = one. This is used much more than in English, where it has a
  pompous feel ("`Pardon me, where can one purchase a…`"). In
  Interlingue it means "`one`", "`we`", "`people`", "`you`" (a general
  "`you`"), and even
  forms the passive. *In Italia on parla italian* = one speaks Italian
  in Italy, we speak Italian in Italy, you speak Italian in Italy,
  Italian is spoken in Italy.
- *self* = self
- *li sam* = the same
- *alquí* = somebody
- *alquem* = (object) (to, on…) somebody.
- *alcun* = some, any
- *alquó, alquicos* = something, some thing
- *quelc* = some (a few)
- *nequí* = nobody
- *nequem* = nobody (object)
- *nequó, necos* = nothing, no thing
- *nequel, null* = no (no water, no money…)
- *nequal* = no (sort of)
- *nequant* = no (quantity)
- *chascun* = each
- *omni* = any, all
- *altri* = other
- *altricos* = something else
- *pluri* = several
- *mult* = many
- *poc* = few
- *un poc* = a few
- *cert* = certain
- *un cert* = a certain
- *mani* = many, many a
- *tot* = all
- *-cunc* = fixed to pronouns to give the sense of "`whatever`".
  *quicunc* = whoever, *quelcunc* = whichever, *quocunc* = whatever.
  *-cunc* is not accented.

NOTE: Because *al-*, *ne-*, *-cunc* etc. are never accented, the pronouns
are often written without accents (*alquo* instead of *alquó*, *alqui*
instead of *alquí*).

These pronouns are easy to remember with sentences incorporating the
same forms:

====

- *Quant vu have? Nequant.* = How much do you have? Nothing.
- *Quant vu have? Alquant.* = How much do you have? Some.
- *Qui veni? Quicunc.* = Who's coming? Whoever.
- *Qui veni? Nequí.* = Who's coming? Nobody.
- *Quo tu have? Nequó.* = What do you have? Nothing.
- *Quem tu dat it? Nequem.* = Who did you give it to? To nobody.
- *Qualmen tu fat it? Talmen.* = How did you do it? Like that.

====

Examples:

// XXX FIXED -- qulec -> quelc

====

- *Oh hom, conosse te self!* = Oh human, know thyself!
- *In li sam témpore e in li sam loc, mi amíca.* = At the same time
  and in the same place, my friend.
- *Si alcun fémina parla pri alquó, ella pensa pri alquí.* = When some
  woman talks about something, she thinks about someone.
- *Chascun hom es forjero de su propri fortune.* = Each person is the
  forger of his/her own fortune.
- *Ples dar me quelc libres, yo have quelc líber hores por leer!* =
  Please give me some books, I have some free hours for reading.
- *Placer a omnes on ne posse, es arte, quel nequí conosse.* =
  Pleasing all one cannot do, it is an art known by no one. (Note: in
  Interlingue it rhymes.)
- *Ja pluri annus yo vive in ti cité.* = I have lived in this city for
  several years already. (Note: only the present tense is used here.
  *Yo ha vivet* is also acceptable)
- *Il have poc espera.* = He has little hope.
- *Il have un poc de espera.* = He has a little hope.
- *Yo conosse un cert senior Miller, ma yo ne es cert, esque il es
  ci.* = I know a certain Mr. Miller, but I'm not certain if he is
  here.
- *It es tot egal, esque Vu vide li tot munde, o quelc partes de it.*
  = It is all the same whether you see the whole world, or some parts
  of it.
- *Quicunc va venir, yo ne es in hem!* = Whoever comes, I'm not at
  home!
- *Quocunc tu di, ples dir li veritá.* = Whatever you say, please
  speak the truth.
- *Quelcunc labor vu fa, ples far it bon.* = Whatever work you do,
  please do it well.

====

// Ninesim letion {{{1
== Ninesim letion

// Textus {{{2
=== Textus

// Un parol — un novelle {{{3
==== Un parol — un novelle

// XXX TODO -- Consultar notatation in Interlingue:
//
// "`Fußvolk,`" -- "`Fußvolk`",

// XXX FIXED -- _infanterie_. -> "`Infanterie,`"
//
// Signes de citation por coherentie con li altri exemples.  Con
// majuscul nam it es un german substantive. Li punctu intern por
// coherentie con li notation del altri exemples, benque su rect
// usation ne es ancor confirmat in Interlingue.

Si yo prende un parol ex un lingue, it va racontar me alcun
cultur-historic facte. Lass nos, por exemple, prender li german parol
"`Infanterie.`" Su form indica, que it es un parol pruntat ex li francesi
lingue. Ergo li franceses deve har havet un cert influentie concernent
li developation e organisation del german armés, altrimen on vell har
conservat li genuin old german parol "`Fußvolk,`" usat ancor in li
decisixesim secul. Ma li parol explica ancor plu. It di, que originalmen
it deve har esset usat por un cert sorte del infanterie, a saver, por li
guardie del Infante de Hispania. Li "`Infante`" de Hispania es identic con
li international parol, e pro to anc de Interlingue,  "`infante,`" originant del
latin "`infans,`" quel es composit del prefix "`in`" (ne) e "`fans`"
(parlant), to es, un hom, quel ancor ne posse parlar. Talmen yo veni in
mi exploration a plu e plu lontan témpores e popules, e yo fini che li
unesim conosset form e sense del parol, che li etimon. Li historie de un
parol es un micri novelle, un excerpte ex un immensimen grand libre: li
Historie del Homanité.

// Vocabularium {{{4
===== Vocabularium

- *concerner* = to concern
- *developar* = to develop
- *etimon* = etymon (a word root — cf. etymology)
- *excerpte* = excerpt
- *genuine* = genuine
- *indicar* = to indicate
- *infante* = infant
- *influentie* = influence
- *lontan* = far
- *pruntar* = to borrow

// Li grand idés {{{3
==== Li grand idés

To quo es necessi por elevar li spíritu, ne es to, que un hom save
omnicos, quo ha esset pensat e scrit in relation al spiritual natura, ne
es to, que un hom deveni un enciclopedie, ma to, que li grand idés, in
quel omni decovritiones termina, queles summa omni scienties, queles li
filosof extrae de ínfinit detallies, es comprendet e sentit. It ne es li
quantitá, ma li qualitá de saventie, quel determina li dignitá del
anima. Un mann de immens erudition posse pro su manca de larg e extensiv
idés, esser mult plu inferior in intelectu quam un laborero, qui, con
micri saventies, támen ha trovat grand veritás. Un grand anima es format
per poc grand idés, ne per infinitá de íncoherent detallies. Yo ha
conosset tre doct homes, qui apparet a me tre povri in intelectu, proque
ili havet null grand pensas. Quo vale to, que un mann ha studiat
quantcunc detalliat li histories de Grecia e Roma, si per li historic
documentes li grand idés de libertá e bellitá e bravitá e spiritual
energie ne ha flammat quam vivent foyes in su anima?

Channing

// Vocabularium {{{4
===== Vocabularium

- *bravitá* = bravery
- *determinar* = to determine
- *elevar* = to raise
- *erudition* = erudition
- *larg* = broad, wide
- *terminar* = to end

// Anecdotes {{{3
==== Anecdotes

// XXX REMARK -- 2019-03-20: Por leibilitá, it esset necessi separar
// ambi anectodes, ma un simplic marca de linea (equivalent a `<hr/>`
// de HTML) ne esset traductet ex Asciidoctor ad-in DocBook, ergo anc
// ne ad-in EPUB (nam it es un marca visual, ne semantic).  Li linea
// esset videbli solmen in PDF, nam ti ci es creat directmen ex
// Asciidoctor.  Finalmen, titoles ha esset adjuntent a ambi
// anecdotes.

// Li question {{{4
===== Li question

Du yun juristes, Miller e Brun, visitat sovente li sam yun dama. Un
véspere Miller esset sol con ella. Il dit in tendri ton:

"`Esque Vu pensa, María, que Vu posse subitmen abandonar patre e matre,
sestra e fratre, ti plesent, comfortabil dom, e emigrar in li savagi
West con un yun jurist, qui posse viver solmen per su profession, e
serchar ta un nov hem, in quel ambi posse esser felici?`"

Inclinante su bell cap sur li epoles de Miller, ella chuchotat
tendrimen: "`Yes, yo pensa que yo posse, Arnold.`"

"`Bon,`" dit Miller, "`it es Brun, qui intente emigrar e desira un sponsa,
yo va mentionar to a il.`"

// Teophrástos dit {{{4
===== Teophrástos dit

A un yun mann, qui sedet silent in un companie, Teophrástos, li famos
grec filosof, dit: "`Si Vu es folli, Vu acte sagimen; si Vu es sagi, Vu
acte follimen.`"

// Vocabularium {{{4
===== Vocabularium

- *ambi* = both
- *chuchotar* = to whisper
- *emigrar* = to emigrate
- *epol* = shoulder
- *felici* = happy
- *foll(i)* = crazy
- *fratre* = brother
- *intenter* = to intend
- *matre* = mother
- *savagi* = wild
- *serchar* = to search
- *sestra* = sister
- *sponsa* = spouse (female)
- *subitmen* = suddenly
- *tendri* = tender

// Aforismes {{{3
==== Aforismes

____
Mem li deos combatte li stupiditá in van.
____

[quote, Swift]
____
Li paroles es solmen vente – li erudition consiste solmen ex paroles –
ergo li erudition es solmen vente.
____

[quote, Schopenhauer]
____
Li gazettes es li secund-indicatores del historie. Ma ili es sovente de
plu ínnobli metalle quam li altri indicatores, e ea anc rarmen correct.
____

[quote, Börne]
____
Quande Pythagoras hat decovrit su conosset teorema, il aportat un
hecatombe al deos. Desde to li boves treme, tam sovente quam un nov
veritá es decovrit.
____

[quote, Pauly]
____
Li majorité del homes lassa voluntarimen presser se in li carne li spine
de un fals teorie, ma ili defende se per omni forties, si on vole denove
extraer it.
____

// Explanations {{{2
=== Explanations

From adjectives we can create adverbs by adding the ending *-men*. This
ending does not change the stress:

====
- *Un prudent mann acte prudentmen.* = A prudent man acts prudently.
====

When the meaning is clear, the adjective by itself may function as an
adverb:

====
- *Il parla bon.* = He speaks well (lit. good).
- *Li sole luce clar.* = The sun shines clear(ly).
====

Another way to form an adjective is to use *in maniere*:

====
- *Il scri in elegant maniere.* = He writes in an elegant manner.
====

Prepositions can be used to form adverbs: *in (li) nocte* = at night,
*in fine* = finally, *in general* = in general, *in ocasion* = on
occasion, *per ocasion* = by chance, etc.

// XXX FIXED -- "Pronomial" -> "Pronominal"

Pronominal adverbs:

- *u?* = where?
- *ci* = here
- *ta* = there
- *necú* = nowhere
- *alcú* = somewhere
- *partú* = everywhere
- *supra* = above
- *infra* = below
- *extra* = outside, besides
- *intra* = inside
- *detra* = behind
- *a(d) u?* = to where?
- *a(d) ci* = to here
- *a(d) ta* = to there
- *adavan* = forward
- *retro* = backward
- *ad supra* = upwards
- *a bass, ad infra* = downwards
- *ex, ad extra* = out from
- *in, ad intra* = into
- *de u?* = from where?
- *de ci* = from here
- *de ta* = from there
- *de supra* = from above
- *de infra* = from below
- *qualmen?* = how? in what way?
- *talmen* = in that way
- *tam* = so (with an adjective or adverb following)
- *alquam* = somehow
- *quande?* = when?
- *tande* = then (also *alor*)
- *unquande* = once
- *apen* = hardly
- *ne totmen* = not entirely
- *totmen ne* = not at all
- *fórsan* = perhaps
- *junt* = together
- *presc* = almost
- *nequam* = not at all
- *nequande* = never
- *alquande* = some time, ever
- *poc a poc* = bit by bit, gradually
- *solmen* = only
- *ya* = indeed, well (strengthens the meaning somewhat)
- *yes!* = yes!
- *no!* = no!
- *ínterim* = meanwhile
- *nu* = now
- *strax* = right away
- *bentost* = soon
- *sovente* = often
- *ja* = already
- *jamá* = (n)ever
- *sempre* = always
- *antey* = before
- *quant?* = how many?
- *tant* that many
- *nequant* = none at all
- *alquant* = a certain amount
- *poy* = after
- *in ante* = beforehand, in advance
- *depoy* = from then
- *ancor* = still
- *adplu, ulterior* = furthermore
- *hodie* = today
- *tre* = very
- *tro* = too
- *circa* = around, circa
- *mult* = many
- *ho-annu* = this year
- *ho-témpore* = these times
- *deman* = tomorrow
- *posdeman* = the day after tomorrow
- *yer* = yesterday
- *anteyer* = the day before yesterday
- *un poc* = a bit
- *suficent* = enough
- *vez* = time (as in two times)

With the enclitic *-cunc* we get words like *ucunc* = wherever,
*quamcunc* = however, as ever, *quandecunc* = whenever, etc.

Some more examples showing their function?

====

- *Qualmen Vu fa it? Talmen.* = How do you do it? Like that.
- *Quam bell es li flore!* = How beautiful the flower is!
- *Tam bell quam un flore.* = As beautiful as a flower.
- *Plu bell quam un flore.* = More beautiful than a flower.
- *Quam un rey. Quam rey.* = Like a king. As king.
- *Quam Vu save, it es talmen.* = As you know, that's the way it is.
- *Quant homes esset ta? Tant quant yer.* = How many people were
  there?  As many as yesterday.

====

// Conjunctions {{{3
==== Conjunctions

The most frequently used conjunctions are:

// XXX FIXED -- "the more … the …" -> "the more … the more …"

- *e* = and
- *e … e* = both … and …
- *o* = or
- *o … o* = either … or …
- *ni* = not (stronger than *ne*)
- *ni* .. *ni* = neither … nor …
- *sive … sive …* = either … or …
- *ma* = but
- *nam* = for, because
- *támen* = however
- *ergo, dunc, do* = therefore, thus, etc.
- *plu … plu* = the more … the more …
- *nu!* = well!
- *vi* = behold, here are
- *nu … nu* = first … now the other (i.e. doing one thing and then
  the other)

There are also some subordinate conjunctions:

// XXX FIXED -- Clearer example with ellipsis:

- *que* = that (e.g. "`He said that …`")
- *si* = if
- *quam* = as, like
- *esque, ca* = whether, if (e.g. "`I don't know whether …`")
- *quasi* = as if, quasi
- *benque* = though, although
- *etsi* = albeit, although
- *sam quam* = same as

// XXX FIXED -- The lists had been combined by mistake. Also, in the
// german transcription `*sam quam* = same as` was in wrong place.

With *quam* and *que* together with other words we get a large number
of conjunctions such as:

- *anteque (ante que)* = before
- *posque (pos que)* = after
- *proque (pro que)* = because
- *porque (por que)* = in order that
- *perque (per que)* = in that (because of…)

NOTE: The *que* here is not translated as "`that`" in English but carries
that sort of meaning. Point to take home: Having *que* means the parts
of the sentence before *que* and after it can stand on their own.
Examples of conjunctions with and without *que* to demonstrate the
difference:

// XXX FIXED -- wha -> who

====

- *Il venit _ante_ quin annus.* = He came five years ago. (*quin
  annus* on its own is not a phrase)
- *Il venit _ante que_ il hat trovat it.* = He came before he had
  found it. (*il hat trovat it* on its own is a phrase)
- *Il laborat _pro_ manca de moné.* = He worked due to lack of money.
  (*manca de moné* is not a phrase)
- *Il laborat _pro que_ il mancat moné.* = He worked because he lacked
  money. (*il mancat moné* is a phrase)
- *Il luctat _por_ su país.* = He fought for his country. (*su país*
  is not a phrase)
- *Il luctat _por_ protecter su país.* = He fought to protect his
  country.  (*protecter su país* is also not a phrase)
- *Il luctat _por que_ su filies mey saver qui hat protectet lor
  país.* = He fought so that his children would know who had protected
  their country. (*su filies mey saver qui hat protectet lor país* =
  may his children know who had protected their country -- is a
  phrase!)

====

// Decesim letion {{{1
== Decesim letion

// Textus {{{2
=== Textus

// "`In comensa esset li parol`" {{{3
==== "`In comensa esset li parol`"

// XXX FIXED -- nested quotes

Li famosi unesim frase del Evangelium de Johannes cela un profund sense,
anc si noi comprende it litteralmen. Nam solmen per su capabilitá
expresser per paroles su intern traviventies, su observationes e
sentimentes, su perceptiones e desiras e comunicar les, evenit li
metamorfose del hom ex un animale, solmen li linguistic talent corona li
hom quam li dómino del creaturas. Sin parol ne vell exister un clar
notion, sin notion null pensation, sin lingue null alt spiritual vive.
Nam li singul notiones, per li medie de queles li hom pensa, es
strictissim ligat con cert paroles, un real, ver pensada sin paroles ne
es possibil. Concedet que mani brevi pensation, mani actiones de vole
eveni instinctiv o intuitiv, un plu alt spiritual vive, quel eleva se
súper obscur fluctuationes de pur instinctes e perceptiones a plen
claritá e libertá del conceptiv pensada, es e va esser connectet a
linguistic capacitá. Omni spiritual valores li hom debi finalmen a su
talent de articulat parlation. Novális di unquande in su aforismes: "`Li
grammatica es li dinamica del spiritual dominia. Un parol de comande
move armés, li parol '`libertá`' nationes.`"

Quande li poet e li pensator vaga líber ad in li immens dominia de
pensas, lor ales es li parol. Li parlant hom victe li circumant natura
per li parol e quam creator forma per li parol su propri, subjectiv
munde, in contraritá e quam contrast al sensualmen perceptibil
fenomenes: li munde del spíritu – de su spíritu. On ha dit, que li hom
es un hibride inter deo e animale, e yo vole dir que li paroles es li
scalunes de ti scaliere celesti, along quel il prova grimpar súper lu
pur animalic ad in li luce del spritualitá. De to seque anc, que li
lingue da nos li fundament e li unesim base de omni cultura.

Güntert

// Li mult lingues de Europa {{{3
==== Li mult lingues de Europa

// XXX FIXED -- Parisano -> parisano

Li lingual situation in li hodial Europa es paradoxal.

Li material civilisation, li scientie, e mem li arte unifica se plu e
plu. Li cultivat europano senti se quasi in hem in omni landes queles
have europan civilisation, it es, plu e plu, in li tot munde. Hodie
presc omni states guerrea per li sam armes. Sin cessa li medies de
intercommunication ameliora se, e in consequentie de to li terra sembla
diminuer se. Un parisano es nu plu proxim a un angleso o a un germano
quam il esset ante cent annus a un paisano francesi.

Li civilisation tende vers unitá.

It existe solmen _un_ scientie, a quel li erudites de omni nationes
contribue, partú on studia li sam problemas per li sam procedes, per li
sam instrumentes. Li laboratorias de America e Japan labora pri li sam
questiones quam tis de Europa. Li observatorias del tot munde prepara un
carte de ciel, in quel ili execute chascun un parte. Un modern erudito
es, si il vole o ne, li colaborator de omnes, qui in li tot munde
cultiva li sam
scientie. It existe, por chascun specialitá scientific, un micri
comunité de erudites, qui, amicos o rivales, conosse unaltru, seque li
activitá de unaltru e reacte un a li altri.

Li scientie, quel es un, domina un tecnica, quel anc es un. Chascun
decovrition scientific change li procedes de fabrication e li
conditiones de production. E omni nov procede de fabrication es rapidmen
conosset in li tot munde.

// XXX FIXED -- banks -> bankes
// XXX FIXED -- afferes -> aferes

Li aferes comercial es international. Li industries de un branche
conclude cartelles trans li frontieras. Li bankes del tot munde es alliat
per comun operationes.

Li ovreros ha sentit, que, in regard a lor patrones, ili have identic
interesses. Li formul "`Laboreros de omni landes, unia vos`" ha evocat ecó
in li classes de ovreros de omni landes.

Li rel-vias, li naves, queles fa possibil li relationes inter li homes,
deve devenir simil, caus necessitá. Li postal servicie ha esset fortiat
unificar se por conformar se secun li principies del union postal
universal.

Li vestes deveni partú li sam. Li guerre ne ha impedit li feminin modes
subir in li tot munde occidental presc li sam changes in li sam témpore.

Omnicos va uniformisar se.

Durant omni to li lingues, queles servi quam organes por li
civilisation, es tre divers, ili deveni constantmen plu mult. Li
conossenties del german, anglesi, hispan, francesi e italian ne sufice
plu a tis queles vole sequer li currente del tot civilisation modern.

// XXX FIXED -- suffic- -> sufic- (e omni altris in li libre)

Chascun nation, quamcunc micri it es, vole haver su propri lingue de
civilisation. Presc chascun nation de Europa ha obtenet autonomie e nu
li conossentie de duant lingues ne sufice por sequer li civilisation de
sol Europa.

Por experir li obstacules quel resulta de to, sufice transpassar un
lingual frontiera. Por tis, doctos o practicos, qui deve sequer li
currente del labor fat in li munde, li diversitá del lingues del
civilisation complica li labor in un maniere íntolerabil. Li aprension
de un scientie o tecnica deveni per chascun die plu laborosi, e li
necessitá aprender divers lingues e sempre plu divers, adjunte un cargo,
quel ne cessa far se plu e plu pesant.

// XXX FIXED -- differ- -> difer- (e omni altris in li libre)

In li sam gradu quam li civilisation deveni plu uniform, li lingues have
a expresser li sam coses per materialmen diferent, ma paralel procedes.
Li notiones ne varia con li paroles, queles expresse les. Li lingues de
Europa per to quo ili expresse, tende a devenir li fidel calcationes de
unaltru.

// XXX FIXED -- applicabil -> aplicabil

On save quel desfacilitás incontra un congress international pro li
diversitá del lingues, ne solmen si it acte se pri un congress de homes
con mediocri education, queles ne conosse foren lingues, ma anc li
congresses de homes alt educat, nam quam rarmen ili ha havet témpore
aprender parlar fluentmen un foren lingue! Li congresses de un partise,
quam li socialistic, quel confesse internationalisme, es fat tre
desfacil per li necessitá traducter omnicos in adminim du lingues, e li
delegates del micri landes deve esser electet solmen inter tal homes,
queles bon conosse un de ti lingues queles es usat in li congress. E it
es ínevitabil haver un comun lingue por far possibil un ver discussion.
Por ti scope on besona un lingue, quel es facilmen aprensibil e
aplicabil e neutral. Solmen un lingue artificial responde a ti
conditiones.

Li practic necessitá haver un lingue international es evident. E proque
un tal lingue es possibil, it deve esser introductet tam bentost quam
possibil.

(Secun A. Meillet, professore de Collège de France.)

// Explanations {{{2
=== Explanations

// Syntax {{{3
==== Syntax

// XXX FIXED -- "Syntax is Interlingue" -> "Syntax in Interlingue"

Syntax in Interlingue is for the most part very similar to English, with
some notable differences in places such as adjectives where they can
also be placed after the noun (general rule of thumb: the longer the
adjective, the more it feels right to place it after the noun). Some
other small differences exist, some of which are seen in the following
examples.

====

- *Li monument es plazzat avan li palace.* = The monument is located
  (placed) before the palace.
- *Li judico es nominat Cadi che li arabes.* = The Arabs call the
  judge Cadi (lit. the judge is named Cadi with the Arabs).
- *Il pensat sovente pri li felici témpore del yunesse.* = He often
  thought about the happy times of (his) youth.
- *Tui amore e tui felicie eleva se avan me quam un etern aurora.* =
  Your love and your happiness rise before me like eternal dawn.
  (Goethe.)
- *Li númere de spectatores hat crescet extremmen per arivas ex vicin
  districtes.* = The number of spectators has grown greatly
  (extremely) by arrivals from nearby districts.
- *Yo ne save, esque yo ha fat bon.* = I don't know if I've done
  right.
- *Por scrir un bon lettre de amore, tu deve comensar sin saver quo tu
  vole dir, e finir sin saver quo tu ha dit.* = To write a good love
  letter, you must begin without knowing what you want to say, and end
  without knowing what you have said. (Rousseau.)

====

The regular word order in Interlingue is:

[cols="3*^"]
|===
| 1. Subject | 2. Predicate | 3.  Object

| *Goethe*   | *ha scrit*   | *Faust*.
|===

The same applies to subordinate clauses.

Note some important differences that take place when the word order is
changed. Words such as *anc*, *solmen*, etc. quantify the word they
stand in front of.  The word *ne* also negates the word it stands in
front of.  Other examples: *tro*, and *tre*.

////////////////////////////////////////////////////////////////

// XXX FIXED -- This example was not right:

- *Vor _libre_ yo ne prende.* = I'm not taking your book (I'm taking
  something else of yours).

// Other examples have been revised.

////////////////////////////////////////////////////////////////

====

- *Yo ne _va prender_ Vor libre.* = I won't _take_ your book (but will
  leave it lying or do something else with it).
- *Ne _yo_ va prender Vor libre.* = _I_ won't take your book (somebody
  else will).
- *Yo va prender ne _Vor_ libre.* = I won't take _your_ book (I will
  take somebody else's).
- *Vor libre yo ne _prende_.* = I'm not _taking_ your book (I'm doing
  something else with it, e.g. leave it lying).
- *Anc _yo_ ama Vos.* = _I_ love you too (other people, including me,
  love you)
- *Yo ama anc _Vos_.* = I love _you_ too (I love other people,
  including you).
- *Solmen _ella_ ride.* = Only _she_ is laughing (nobody else is).
- *Ella solmen _ride_.* = She only _laughs_ (she keeps laughing, she
  doesn't something else).
- *Il tre regreta, que il have solmen _poc_ euros.* = He regrets
  having just _a few_ euros.

====

More on the rule of thumb for adjectives: they tend to stand before the
noun when they are short or refer to the character of the noun, and
after when longer, less directly related, part of a subordinate clause,
adding extra information, etc.

====

- *Li delicat caviare russ.* = delicate Russian caviar.
- *Li lingue international.* = The international language.
- *Ti mann, clar in su pensas e pur in su intentiones.* = That man,
  clear in his thoughts and pure in his intentions.
- *Su patre e su matre hat fat omni arangeamentes necessi por su
  viage.* = His/her father and mother had made all arrangements
  necessary for the trip.
- *Raporte aproximativ pri merces, important durant ti ci estive.* = A
  summary report on goods (that are) important during this summer.

====

In the first two sentences above it is somewhat a matter of taste
whether to say *russ caviare* or *international lingue*, though the word
*international* being long feels a bit more right after the noun. The next
three sentences however are much more clear cut
(*necessi-por-su-viage-arangeamentes* would be odd).

Dependent clauses: note the same word order.

// XXX FIXED -- "pensat, quo" -> "pensat, que"

====

- *Il di, que il es malad.* = He said that he is sick. (*Il di*{nbsp}+
  *il es malad*).
- *Il pensat, que yo hat ja venit.* = He thought that I had already
  come.  (*Il pensat*{nbsp}+ *yo hat ja venit*).
- *Ella questionat, pro quo yo es tam felici.* = She asked why I was
  so happy. (*Ella questionat*{nbsp}+ *yo es tam felici*).

====

In sentences with questions (direct and indirect) that do not start with
question pronouns (where, why…) or adverbs are usually formed with the
general question word *esque* (lit. *is that*), but may be formed
without it.

====

- *Esque Vu comprende me?* = Do you understand me?
- *Ha Vu comprendet me?* = Have you understood me?
- *Yo ne save, esque yo comprende Vos corect.* = I don't know if I
understand you right.
- *Pensa Vu o dormi?* = Are you thinking or sleeping?

====

Other options for *esque* in subordinate clauses are *ca* and *si*.
The third setence could start with *Yo ne save, ca…* or *Yo ne save,
si …*.

The difference between forming questions, wishes (optative phrases) and
conditional sentences:

====

- *Esque ella hat conosset su matre?* = Did she know her mother?
- *Mey ella har conosset su matre!* = If (only) she had known her
  mother!
- *Si ella vell har conosset su matre, ella vell…* = If she had
  known her mother, she would…

====

For the conditional you can add a *in ti casu* (in that case) if wished
to translate English "`then`" (if she had known her mother, _then_ she
would have…), but *vell* on its own is always enough. Also note that
in the conditional, both parts of the sentence use *vell*. This is like
saying "`if she _would have_ known her mother she __would have__…`",
because both parts are conditional. One does see the perfect past
starting off these types of sentences from time to time, however: *Si
ella hat conosset su matre, ella vell har…*

Where some languages use a preposition (especially *a*) before the
subject of a verb and others don't, Interlingue prefers to not use them.
Rule of thumb: if in doubt, try going without a preposition if the
meaning is still clear.

The same goes for reflexive verbs (verbs using *se*). English uses
them infrequently but still does in some places such as "`I'm going to
find _myself_ something to eat`" which would be written *Yo va trovar
alquó a manjar* and not *Yo va trovar _me_ alquó a manjar*.

====

- *Yo mersia Vos* (not *a Vos*). = I thank you.
- *Ples auxiliar li* (not *a li*) *povri mann.* = Please help the poor
  man.
- *Il menaciat su ínamicos.* = He threatened his enemies.
- *Yo memora li cose tre bon.* = I remember it ("`the thing`") very
  well.
- *Il prepara por un viage.* = He is preparing for a voyage.
- *To il solmen imagina.* = He just imagines it.
- *Yo es conscient pri to.* = I'm aware of that.
- *Yo tre joya vider Vos.* = I'm very happy to see you.
- *Yo senti dolore; yo regreta.* = I'm sorry; I regret that…
- *Yo repente.* = I'm sorry ("`I repent that…`")
- *Yo senti calore; yo cale.* = I'm hot.
- *Yo senti frigore; yo frige.* = I'm cold.
- *Yo senti fame.* = I'm hungry.
- *Yo senti sete.* = I'm thirsty.
- *Yo successat far it.* = I was able to do it.
- *On dansat e ludet.* = We/they/one danced and played.

====

NOTE: The above phrases are ones that in the original German are
rendered with reflexive verbs in German; fortunately, English does not
use them nearly as much.
