== Occidental Course in 10 Lessons (lessons 7-8)

 +

[[displaycontent]]
 

 

== *7 Setesim letion*

 

=== 7.1 Texte

 

==== 7.1.1 Li intern veritá

 

To quo, secun li opinion de frances e angles letores, distinte Goethe,
es un qualitá, quel il divide con su nation – constant referentie a
intern veritá. In Anglia e America existe reverentie por talent, e li
publica es satisfat, si li talent es exercit pro un cert fixat o
comprensibil interesse o partie, o in regulari oposition contra un de
tales. In Francia existe un plu grand delicie por intellectual
brilliantie, pro it self. E in omni ti landes talentat homes scri
talentosimen. It es suficent, si li intercomprension es ganiat, li
contact attinger, tant columnes, tant hores ocupat in un vivaci e
honorabil maniere. Al german intellectu manca li frances brilliantie, li
fin practical comprension del angleses, e li american aventura; ma it
have un cert honestie, quel nequande resta in superficial performantie,
ma questiona constant: pro quel scope? Un german publica
demanda controlant sinceritá. "Ci es un activitá de pensada – ma por
quo? Quo vole li mann? De u, de u omni ti pensas?"

 

Sol talent ne posse far un autor. It es necessi que existe un mann detra
li libre, un personalitá qui per su orígine e su qualitá da garantíe a
ti doctrines queles il exposi, e qui existe por vider e constatar li
coses in ti e ne in un altri maniere, qui defende factes proque ili es
factes. Si il ne posse expresser se corect hodie, li sam coses supervive
e va explicar se deman. Un charge jace sur su mente, li charge de un
veritá explicand – plu o minu comprendet, e it constitue su ocupation e
su vocation in li munde soluer li problemas e far les conosset. Quo
importa que il mistrotta e balbutia, que su voce es crud e mis-sonant,
que su metodes e su tropes es ínadequat? Ti mission va trovar metode e
images, articulation e melodie. Etsi il vell esser mut, it vell parlar.
Si ne – si ne vell exister un tal divin parol che li mann – quo noi
cuida, quam fluent, quam brilliant il es . . .

 

(Emerson)

 

[cols=",,,",]
|===
|*distinter*  |to distinguish  |*atinger*  |attain 
|*exposir*  |to expose  |*voce*  |voice 
|*referer*  |to reference  |*aventura*  |adventure 
|*explicar*  |to explain  |*crud*  |crude 
|*reverer*  |to revere  |*charge*  |charge, burden 
|*sonar*  |to sound  |*satisfar*  |to satisfy 
|*performar*  |to perform  |*vocar*  |to call 
|*trope*  |figure of speech, trope |*exercir*  |to exercise 
|*scope* |a goal |*demandar* |to demand, request
|*cuidar* |to take care of |*delicie* |a delicacy
|*sol* |alone |*ganiar* |to win
|*orígine* |origin |*balbutiar* |to stutter
|===

 

Note: the -nd suffix (-and for -ar verbs, -end for -er and -ir verbs)
adds the meaning "thing to be (verb)ed)". This is where words
like *dividende *(thing to be *divided*, from divider) come from, which
adds a certain obligation (a thing to do = a thing one should do).  As
an adjective it can also take the -i at the end for euphony. The
above *un veritá explicand* thus means "a truth to be explained".
Another way to say the same would be *un veritá a explicar*.

 

 

==== 7.1.2 Aforismes

 

Si li triangules vell posser pensar, ili vell imaginar su Due quam
triangulari. (Spinoza.)

 

Li capes de grand homes diminue, si plures de ili conveni; plu mult li
sagies, plu minimal li sagesse. (Montesquieu.)

 

Moventie, progresse, esperantie, vive, omnis es solmen sinonimes de
optimisme. Li antiqui romano qui pensat li proverbie: durant que yo
spira, yo espera, ha concentrat li filosofie del processe del vive, e
dat a un biologic fundamental veritá li forme de un classic calambure.
(Nordau.)

 

Li damas ne veni in li ciel, nam ja in li Apocalipse es dit in un loc:
It esset silent durant un demí seconde. To ne es pensabil ta, u damas es
present. (Kant.)

 

[cols=",,,",]
|===
|*angule*  |angle  |*spirar*  |to breathe 
|*loc*  |place  |*sagie*  |sage 
|*calambure*  |wordplay, pun  |*siler*  |to be silent 
|===

 

 

==== 7.1.3 Li evangelie del labor

 

It existe du folles in li munde. Li un es li millionario, qui crede, que
il posse acumular real potentie per collecter moné; li altri es li
glatt-rasat agitator, qui crede, que si il solmen vell posser prender li
moné de un classe e dar it a un altri, li social maladies vell esser
curat. Ili es ambi sur fals via. Mani del max successosi ho-temporan
collectores de moné ne ha augmentat, ni per minimalissim summa, li
richesse del homanité. Esque cart-luderos contribue al augmentation del
richess del munde?

 

Si noi omni vell partiprender in li productiv labor, intra li límites de
nor capacitá, on vell posser questionar solmen pri to, esque chascun va
reciver to quo il besona. Un real manca del vital necessitás – ne un
fals manca pro absentie de tintinant metallic monetes in nor tascas –
posse depender solmen de ínsuficent production, e ti es, in su órdine,
tro sovente un consequentie de mancant saventies pri to quo e qualmen on
deve producter.

 

Ja in comensa noi deve fixar quam facte: li terra es capabil producter
decent vive a chascun; ne solmen nutrition ma omnicos quo noi besona;
nam omnicos veni del terra. It es possibil arrangear li labor, li
production, li distribution e li recompensation talmen, que a chascun
qui fa su deventie, es garantit un parte del resultate in conformitá al
exact justicie.

 

Omnicos es possibil. Crede es li substantie de coses pri queles noi
espera, e li testimonie pri coses queles ne es visibil.

 

(Henry Ford.)

 

[cols=",,,",]
|===
|*folle*  |a fool  |*partiprender*  |to participate, take part 
|*capabil*  |capable  |*deventie*  |a duty
|*acumular*  |to accumulate  |*capacitá*  |capacity 
|*rasar*  |to shave  |*augmentar*  |to augment, increase 
|*tintinar* |to jingle |*luder*  |to play 
|*monete*  |a coin  |*substantie*  |substance 
|===

 

Note: **mani **before a singular means *many a*, while before a plural
it means *many *(same as *mult*).

 

==== 7.1.4. Un lettre

 

Cosmopolis, 12-esim marte 1930.

 

Mi car amico.

 

Yo mersía Vos cordialmen pro Vor amabil lettre de 10-esim ho-mensu. Yo
joya leer, que anc Vu have interesse por li lingue international
auxiliari, e yo constata, que yo esset rect, quande yo suposit, que Vu
ne posse esser índifferent pri un question quel have grandissim
importantie por li future de nor civilisation. Quam omni novones in li
interlinguistica Vu comensa per decreter. In Vor curt lettre de quelc
lineas Vu expresse Vor opiniones e exposi tant postulates concernent li
lingue auxiliari, que, si Vu self vell provar satisfar les, Vu vell
haver sufficent occupation por quelc cent annus. Vu di, que li lingue
deve esser ne europan; ma universal, i. e. un

sintese de omni lingues existent sur li terra. Vu oblivia, que p. ex. li
lingues chinesi e german es tam different, que un lingue, quel deve
satisfar Vor postulate, vell esser quasi un hibride inter harengo e
sparro. Vu di, que li lingue deve esser idealic, i. e. li max perfect
linguistic instrument pensabil. Vu oblivia, que ne omnicos pensabil es
possibil.

 

Idealic lingues es, secun mi opinion, tam ínpossibil quam idealic
states. Ili apartene ambi a Utopie. Un idealic lingue sam quam un
idealic state es possibil solmen ta u vive idealic homes. Vu di adplu,
que li lingue deve esser absolut regulari, nam tande it vell esser max
facil. Yo ne posse comprender, pro quo regularitá vell esser identic con
facilitá. Li lingue ne es solmen grammatica. It posse esser facil
aprender simplic regules, ma it es tre desfacil memorar e usar
ínaccustomat paroles. Quant minu un nov lingue chargea li memorie del
parlantes, tant plu facil it es.

 

It existet unquande témpores, quande homes credet seriosimen, que on
posse crear, constructer e formar nov lingues arbitrarimen, ex
profundore de su animas, secun principies, queles ili self inventet. It
eveni ancor sovente, que on audi simil opiniones expresset de homes
íniniciat. Plu valorosi quam inventer es constatar li ja factic existent
international lingue, quel vive latent in li national lingues del
occidental cultura. Li international vocabularium es tre rich, e pro que
li scientie e technica ja possede un international terminologie, ili ne
posse acceptar un altri lingue international quam un tal quel conserva
ti internationalitá.

 

Vor devoet

 

Y. Z.

 

[cols=",,,",]
|===
|*mersiar*  |to thank  |*ocupation*  |occupation 
|*sam quam*  |same as  |*iniciat*  |initiated 
|*esser rect*  |be right  |*adplu*  |moreover 
|*suposir*  |to suppose  |*harengo*  |herring 
|*sparro*  |sparrow  |*acustomar* |to accustom 
|*devoer*  |to be devoted  |*exposir * |to expose 
|*chargear*  |to charge, burden  |*obliviar*  |to forget 
|===

 

note: *haver rason* is another way to say 'be right'.

 

 

 

== 7.2 Explanations

 

==== 7.2.1 Adjectival suffixes

 

The three most used adjectival suffixes are:

 

*-al*

 

a general suffix showing a relationship or
dependency: **national **from *nation*, **central **from *centre*, **diferential **from *diferentie*,
etc.

 

 

*-ic*

 

being so, possessing properties of the word: energic (energetic) from
energie, fantastic from fantaste (a fantast, someone with eccentric or
fanciful
ideas), **sistematic **from *sistema*, **problematic **from *problema*,
etc.

 

Note: Greek words ending in -ma take a t, and those ending in -se turn
the s into a -t (xe also counts as it is pronounced cse). Thus:

 

*hipnose - hipnotic*

*sintaxe - sintactic*

 

From the adjective -ic we derive nouns with

 

-*ica* and -*ico*

 

-**ica **refers to the name of the science or art in general, and
-**ico **to the person practicing it. This is one situation where the -o
does not necessarily denote a male.

 

*logic logica logico*: logical, logic, logician

*matematic matematica matematico:* mathematic, mathematics,
mathematician

*politic politica politico*: political, politics, politician

*critic critica critico*: critical, criticism, critic

 

==== What about -ical?

====  

Generally, it is a good idea to resist the urge to express every -ical
English word with another -**ical **in Occidental (just -ic is
preferred). But this is another situation where you can for extra
precision, and a subject mentioned in Cosmoglotta before. Because -ica
as shown above refers to the entire branch of art or science,
-**al **can make an adjective referring to it. Some examples where -ic
or -ical could be preferred:

 

*un jardin botanic:* a botanical garden

*un tractate botanical*: a botanical treatise (a treatise relating to
botany, the science)

 

*precision matematic*: mathematical precision

*curiositá matematical:* a mathematical curiosity (a curiosity that
mathematicians are interested in)

 

*un progression aritmetic:* an arithmetic progression

**un problema aritmetical: **an arithmetical problem (a problem that
arithmeticians are interested in)

 

On a related note, beware of words where English is the odd man out such
as *energic* (energetic) where only English has the added -et- in the
middle.

 

 

*-aci*

 

Tending to (similar to English -acious):

 

**mordaci **= mordacious (**morder **= to bite)

**tenaci **= tenacious (**tener **= to hold)

**vivaci **= vivacious (**viver **= to live)

 

 

*-an*

 

belonging to (often made into nouns with -*ano*, -*ana*, -*ane*):

 

**american **= American (**America **= America)

**homan **= human (**hom **= human)

 

 

*-ari*

 

according to, fitting, belonging to (English -ar):

 

**regulari **= regular (**regul **= rule)

**populari **= popular (**popul **= people)

 

 

*-at*

 

(on nouns) provided with something:

 

**foliat **= leafed (**folie **= leaf)

**barbat **= bearded (**barbe **= beard)

 

 

*-ut*

 

very rich in, exuberant:

 

**barbut **= heavily bearded (barbute)

**sandut **= sandy

**armut **= heavily armed

 

 

*-atri*

 

A resemblance but not entirely of the same quality (similar to English
-ish):

 

**verdatri **= greenish (**verd **= green)

**spongiatri **= spongy (**spongie **= sponge)

 

 

*-esc*

 

(of people) similar to, possessing similar qualities to (similar to
English -esque)

 

**infantesc **= childlike (**infant **= child)

**gigantesc **= giantesque (**gigante **= giant, **gigantic **=
gigantic)

 

 

 

*-bil*

 

(transitive verbs): what can be done (transitive verbs) what one can do.
-ar verbs: -abil, -er and -ir verbs: -ibil

 

navigabil = navigable (navigar = to navigate)

formabil = formable (formar = to form)

audibil = audible (audir = to hear)

horribil = horrible (horrer = to be horrified, to dread)

íncredibil = unbelievable (creder = to believe)

durabil = durable (durar = to last)

ínponderabil = unthinkable (ponderar = to ponder)

ínperceptibil = imperceptible (percepter = to perceive)

ínexpressibil = unexpressable (expresser = to express)

visibil (from the perfect stem) = visible (vider = to see)

explosibil (from the perfect stem) = explodable (exploder = to explode)

 

 

*-in*

 

denotes ancestry, origin:

 

**argentin **= silber (**argente **= silver)

**florentin **= Florentine (from Florence, **Florentia **= Florence)

**svinine **= pork (**svin **= pig)

 

 

*-osi*

 

rich in, full of:

 

**famosi **= famous (**fama **= fame)

**musculosi **= muscled (**muscul **= muscle)

**respectosi **= respectful (**respecte **= respect)

**spinosi **= thorny (**spine **= thorn)

 

The similar suffixes -iv and -ori were mentioned in lesson 3.

 

This finishes up the main suffixes seen in Occidental for forming new
words. On top of this are many other much less productive affixes that
show up from time to time and are worth noting:

 

-*id*: having the qualities of a verb: **timid **= timid (**timer **= to
fear, **timore **= fear), *frigid* = cold, frigid (**friger **= to feel
cold, *frigore* = cold)

-*nd*: (mentioned once in a note above): what is to be done. *quo esset
demonstrand* = what was to be demonstrated (Latin *quod erat
demonstrandum*), **dividende **= a dividend, **examinando **= an
exam-taker (one who is to examine)

 

 

==== 7.2.2 Divers afixes

 

Here are some more Latin- or Greek-derived affixes that are seen in
words in Occidental and most other western European languages:

 

*anti*-: against

*Anticristo *(Antichrist), *antitoxine *(anti-toxin), *antisocial *(antisocial,
asocial)

 

*arch*(i): highest, over-

*archiepiscop *(archbishop), *archángel *(archangel), *archifripon *(an
"arch rogue", *archinull *(total zero, huge loser)

 

*auto*-: auto, self

*automobile*, *autobiografie*

 

*non*-: non

*non-agression, nonsense*

 

*pan*-: pan

*paneuropa, panslavist*

 

*proto*-: proto

*protogerman, prototipe*

 

*pseudo*-: pseudo, false (note: p is not silent!)

*pseudo-Cristo* (false Christ), *pseudoscientie *(pseudoscience)

 

*semi-, hemi*-: half

*semivocale, semicólon, hemisfere*

 

*tele*-: tele-, far

*television, telemicroscope*

 

*-cide*: killer of

*patricide, suicide, homicide*

 

*-fer*: bringing, bearing

*fructiferi *(fruit-bearing), *mammifere *(amammal)

 

-*file*: -phile, loving

*germanofile*

 

*-fobe*: fearing

*germanofobe*

 

-*oide*: -oid, resembling

*negroide, mongoloide, caucasoide, romboide, elipsoide*

 

 

 

==== 7.2.3 Parol-composition

 

Words can be joined together in a variety of ways.

 

{empty}1. Through simple joining, either with or without a hypen. a)
Without a hyphen: *postcarte*, *manuscrite*. b) With a
hyphen: *Nord-Europa*, *automobil-garage*

 

{empty}2. With the vowels i or o between
words: *uniform*, *unilateral*, *centimetre*, *microcosmo*, *aeroplan*.

 

The imperative of a verb can also be used to join words
together: *portamoné *(a wallet, lit. a carry-money), *parapluvie *(an
umbrella, lit. a block-rain), *gardarobe *(a wardrobe, lit. a
guard-robe).

 

 

==== 7.2.4 Parol-families (word families)

 

You might have noticed that properly applying the above derivation rules
almost always produces existing international words with the same
meaning. New ones can be made, as that happens consistently in natural
languages. In the few cases where a regularly formed derivation form
differs substantially from an existing international word, both forms
are permitted.
Examples: **noctal **= *nocturn*, **terral **= *terrestri *(terrestrial), *cielal* = *celest *(celestial), **patrin **= *paternal *(paternal).

 

Here are some example of how international words are created by
deduction and composition from simple elements in the derivation of
Occidental:

 

**protecter **= to protect (protect-er)

**protectoratu **= a protectorate (protect-or-atu)

**protectoria **= a house for orphans (protect-or-ia)

**protection **= protection (protect-ion)

**protectionisme **= protectionism (protect-ion-isme)

*protectionist* = protectionist (the person) (protect-ion-ist)

**protectionistic **= protectionistic (adjective) (protect-ion-ist-ic)

**protectiv **= protective (protect-iv)

 

 

**star **= to stand

*stabil, instabil, stabilitá, ínstabilitá, stabilisar, stabilisation,
stabilisator; station, stationar, stationari, stationario; state, statu,
statue, statuarium, statuette, statuer, statute, statuari, static,
statica; statist; statistic, statistica, statistico; stativ; statura;
constar, constant; constantie, constatar; restar, restantie; distar,
distantie; circumstar, circumstantie* etc.

 

Plus some others if one considers that the -stituer ending is also
related to star: *constituer, constitution, instituer, institute,
institution, institutor, restituer, restitution, substituer, substitute,
substitution*,

 

 

 

 

 

 

== 8 Ottesim letion

 

=== 8.1 Texte

 

==== 8.1.1 Un somnie

 

"In facte, yo havet un drolli somnie just nu," racontat un irlandeso.
"Yo revat, que yo esset in Roma e visitat su Sanctitá, li Papa. Apen yo
hat tappat sur li porta, quande il self apertet it. – "A, Pat, es it Vu,
qui ha venit, o alqui altri?" – "Advere, Vor honore, it es yo e nequi
altri." – "Ples venir con me in li superior etage!" il dit me. E ta
esset un separat chambre, bellissim equipat, quel yo ne ha videt jamá."
"Ples seder," dit su Sanctitá, "quo Vu vole?" – Yo meditat durant un
momente, e in fine yo dit: "Un glass de fort trincage." – "Deve it esser
frigid o calid?" – "Calid," yo respondet. E su Sanctitá departet por
aportar li trincage, ma il esset absent tro long e interim yo avigilat
me. Quam yo nu repente, que yo ne hat petit le dar me it frigid."

 

[cols=",,,",]
|===
|*somnie*  |dream  |*tappar*  |to tap, knock 
|*trincage*  |a drink  |*droll(i)*  |funny 
|*honore*  |honor  |*departer*  |to depart 
|*repenter*  |to repent  |*racontar*  |to tell (a story, etc.)
|*equipar * |to equip  |*Papa*  |Pope (note: papá = papa, daddy) 
|*jamá*  |ever, never  |*interim*  |meanwhile 
|*apen*  |hardly, barely, just as  |*meditar*  |to meditate 
|*avigilar*  |to awaken  |  | 
|===

 

 

 

==== 8.1.2 Aforismes

 

de Otto Weiss.

 

Pri un cose noi omni concorda: ne existe plu abominabil erras quam tis
del altres.

 

It es sovente plu facil pardonar un injurie quel noi ha causat a un
altri hom.

 

Li opinion de mani autore es acceptat del publica – quande il self ha
abandonat it ja de long.

 

Mani nómina se idealist: proque il vole viver ne por, ma per un idé.

 

Un conosset patriot ha dit: "Yo ne comprende que alcun hom vole nascer
quam extraniano."

 

On posse tacer pro divers motives: anc pro to que on have necos a dir.

 

Homes (anc Vu ha certmen constatat it) have plu de témpore, quande ili
vole alquicos de nos, quam quande noi vole alquicos de ili.

 

A un yun mann, qui fanfaronat pri su saventies, un old mann dit: "Vu es
felici, qui vive ancor in ti etá, quande on save omnicos."

 

Quam ínprudent it vell esser, si noi vell dir a nor conossetes: "Yo have
exact tant interesse por Vos quant Vu por me."

 

Quande un hom di: "Un de nos erra," yo save strax, quem il alude.

 

Certmen Vu conosse ti person, qui quande on parla pri un altri hom,
comensa strax parlar pri se self.

 

[cols=",,,",]
|===
|*concordar*  |to agree  |*injurie*  |injury, insult 
|*tacer*  |to be silent  |*ínprudent*  |imprudent, careless 
|*mani*  |many a  |*fanfaronar*  |to boast, talk up
|*abominabil* |abominable  |*etá*  |age 
|*aluder* |to alude |  | 
|===

 

 

 

==== 8.1.3 Bon respondet.

 

"Ples pardonar me, Senior," dit un tre seriosi aparent mann a un jolli
hom, qui stat fumant un grand cigare sur li strada, "quant cigares Vu
fuma in un die?"

"O," li response esset, "forsan quar o quin."

"Quin cigares in un die fa triant quin in un semane, circa un cent
quinant in un mensu, e plu quam mill ott cent in un annu. Ples supposir,
que Vu vell har economisat omni ti moné, quel Vu ha expenset a tabac! Vu
vell posser forsan esser li possessor de ti bell micri dom, quel Vu vide
ci a levul."

"Esque it es Vor, mi Senior?"

"O no, yo ne possede un dom."

"Esque Vu save, de qui it es?"

"No."

"It es mi!"

 

Note: *li mi, li vor* etc. is also used.

 

[cols=",,,",]
|===
|*seriosi*  |serious  |*jolli*  |jolly 
|*fumar*  |to smoke  |*a levul*  |on the left 
|===

 

 

 

==== 8.1.4 Aforismes

 

To quo yo time max mult, es li timore. (Montaigne.)

 

Ti qui es fidel, conosse solmen li trivial láteres del amore. Solmen li
ínfidel conosse li tragedies de it. (Wilde.)

 

Existe international artistes qui nequande aprende un lingue perfect:
ili es li nativ extranianos. (Moszkowski.)

 

Li fanatisme es li sol fortie de vole quel anc li debiles e li íncertes
posse manifestar.

(Nietzsche.)

 

Poc homes pensa, ma omnes vole haver opiniones. (Berkeley.)

 

Un mann qui interprende viver per li favor del musas, yo vole dir, per
su poetic talentes, apari me in alcun maniere quam un puella qui vive
per su charmes. (Schopenhauer.)

 

Dilettantes, dilettantes, talmen tis qui cultiva un scientie o un arte
pro amore o joy pri it, pro lor delecte, es nominat con despecte de tis
qui ocupa se pri ili pro profite, proque les delecte solmen li moné,
quel es ganiabil per to. (Schopenhauer.)

 

In mani landes on have ti opinion: tri ásinos constitue junt un
inteligent hom. Ma to es profundmen fals: pluri ásinos in concret fa li
ásino in abstract, e it es un horribil animale. (Grillparzer.)

 

Un solari sistema es solmen un punctuat profil del mundan genie, ma un
homan ocul es li miniatura del solari sistema. (Jean Paul.)

 

[cols=",,,",]
|===
|*fidel*  |faithful  |*ásino*  |donkey, ass 
|*animale*  |animal  |*debil*  |weak 
|*puella*  |girl  |*constituer*  |constitute 
|*interprender*  |undertake  |*despecte*  |scorn 
|===

 

 

==== 8.1.5 Iguanodon

 

Durant mi viage a Stockholm yo visitat anc li natur-historic muséo e yo
esset vermen impressionat per li granditá opressiv del squelette del
antediluvian iguanodon. Benque yo conosset teoricmen li dimensiones e li
grandore de ti prehistoric gigant, li realitá superat omni
imaginationes. Li longore del caude es tam grand, que it ne have
spacie. in li grand sala, ma on ha devet divider it e posir li
detra-parte paralel al squelette.

 

Su altesse, li prince de S., intrat con mult grandesse in li sala del
iguanodon, ma bentost il esset un modest micri hom apu li colossal
animale. Un dama regardat li gigant e dit: "It es ínpossibil. Etsi un
tal animal ha vivet, qualmen on posse saver su nómine?"

 

 

=== 8.2 Explanations

 

[cols=",,,",]
|===
|*viage*  + |journey  + |*diluvie * + |flood  +
|*caude*  + |tail  + |*animale * + |animal  +
|*impressionar*  + |to impress  + |*benque*  + |even though  +
|*spacie* |space |*superar* |surpass
|===

 

 

==== 8.2.1 Pronouns

 

In the preceding texts we have become very familiar with many of the
pronouns in Occidental. Let's look at them as a whole.

 

Personal pronouns

 

* *yo, me* (I, me)
* *tu, te* (you, you) -- singular and informal
* *noi, nos* (we, us)
* *vu, vos* (you, you) -- plural or formar
* *il, le* (he, him)
* *ella, la* (she, her)
* *it, it* (it, it)
* *ili, les *(they, them)

 

 

Possessive pronouns 

 

* *mi*: my
* *tui*: your
* *su*: his, her, its
* *nor*: our
* *vor*: your
* *lor*: their

 

*se* is used to form reflexive pronouns, and *unaltru* means "each
other".

 

Some examples:

 

*Il da la su parol = Il da su parol a ella* = He gives her his word

*Yo da te mi parol = Yo da mi parol a te* = I give you my word

*Li diferentie inter me e te* = The difference between me and you

*Li diferentie inter mi e tui* = The difference between mine and yours

*Li nores victet li vores* = Ours (plural) beat yours (plural).
If **noi **had had one and **vu **had also had had one, it would be
expressed as *Li nor victet li vor*.

*Yo es tua e tu es mio* = I am yours and you are mine (said by a woman
to a man)

**Ples far lu tui! **= Please do yours! (remember *lu* = "the thing
which is")

 

Note that after prepositions the pronouns except **me **and **te **are
in their subject form). This has long been a subject of discussion, with
some preferring outright object forms (*con le, a la, sin les*) and
others preferring the nominative (*con il, con ella, con ili*). But
interestingly nobody has ever preferred the forms *con yo, con tu*,
only *con me, con te*. Rule of thumb: always **me **and *te*, the others
are up to personal preference. Whether the community will decide on one
form over the other is tough to say: even English has yet to do so in
cases such as You are taller than *me* (than + pronoun) vs. You are
taller than I (short for "*than I am*").

 

 

Demonstrative and determinative pronouns

 

* ti: this, that
* tis: these, those
* tal: such, such a
* tales: such (plural)
* to: that (in general)
* tant: so much, so

 

*ti* is very general, which is why it is translated as
both **this **and *that*. To add precision, add *ci *(here)
or *ta *(there) after: *ti ci* (this),* ti ta* (that).

 

*Ti du crayones es li mis: ti ci es curt e ti ta es long; ples prender
tis.* -- These two pencils are mine: this one is short and that one is
long: please take these.

*Il es sempre tal.* -- He's always like that.

*Yo ama tal homes.* -- I like such people.

*Vu ne ama tales?* -- You don't like such (people)? (Here tales could be
something else besides people as it is not specified)

*To es ver.* -- That's right.

*To es tant ver.* -- That's so right.

 

Interrogative and relative pronouns

 

*qui*? -- who?

*quem*? -- whom?

*quel*? -- which?

*qual*? -- how?

*quo*? -- what?

*quant*? -- how much?

 

Examples:

 

*Qui es ta? It es yo.* -- Who is there? It's me.

*De qui es ti chapel?* -- Whose hat is this?

*Quem tu dat li moné?* -- To whom did you give the money? (*a qui* is
another way to say the same thing)

*Quem Vu saluta?* -- Whom are you greeting?

*Quem tu ama max mult?* -- Whom do you love the most?

*Quel adresse Vu have nu?* -- What/which adress do you have now?

*Qual es li aqua hodie, calid o frigid?* -- How is the water today, hot
or cold?

*Quo es to?* -- What is that?

 

The most used relative pronouns are *quel* (singular) and *queles*
(plural). For people *qui* is also used in the singular and plural, and
for objects and abstract things also *quo*.

 

*Ti qui* (or *quel*) *es pigri ne fa progresse*. -- One who is lazy
makes no progress.

*Beat es tis qui *(or *queles*) *ne vide, ma támen crede*. -- Blessed
are those who do not see, but believe.

*It es un cose quel* (not *qui*) *yo ne comprende*. -- It's something I
don't understand.

*Yo ne comprendet to quo Vu dit*. -- I didn't understand what you said.

*Nor lingue fa on constant progress que* *(= quel facte) tre joya me*.
-- Our language makes constant progress, which much pleases me.

*Qual compositor, tal musica.* -- As the composer, so the music.

*Quant vive, tant espera.* -- As long as there is life, there is (that
much) hope.

 

Note: sometimes users of Occidental do not bother to pluralize *quel*:
*tis, quel...* instead of *tis, queles*. *Queles* in the plural is one
of those words that looks more proper when used but not outright
deserving of a correction when not.

 

*Various other pronouns*

 

Note that many of these are simply formed by prefixing *al-*, *ne-*,
etc. to other existing pronouns. They are not accented.

 

*on* -- one. This is used much more than in English, where it has a
pompous feel ("Pardon me, where can one purchase a..."). In Occidental
it means one, we, people, you (a general you), and even forms the
passive. *In Italia on parla italian* = one speaks Italian in Italy, we
speak Italian in Italy, you speak Italian in Italy, Italian is spoken in
Italy.

*self* -- self

*li sam* -- the same

*alquí* -- somebody

*alquem* -- (object) (to, on...) somebody.

*alcun* -- some, any

*alquó, alquicos* -- something, some thing

*quelc* -- some (a few)

*nequí* -- nobody

*nequem* -- nobody (object)

*nequó, necos* -- nothing, no thing

*nequel, null* -- no (no water, no money...)

*nequal* -- no (sort of)

*nequant* -- no (quantity)

*chascun* -- each

*omni* -- any, all

*altri* -- other

*altricos* -- something else

*pluri* -- several

*mult* -- many

*poc* -- few

*un poc* -- a few

*cert* -- certain

*un cert* -- a certain

*mani* -- many, many a

*tot* -- all

-*cunc* -- fixed to pronouns to give the sense of 'whatever'. *quicunc*
= whoever, *quelcunc* = whichever, *quocunc* = whatever. -*cunc* is not
accented.

 

Note: because *al-, ne-, -cunc* etc. are never accented, the pronouns
are often written without accents (*alquo* instead of *alquó*, *alqui*
instead of *alquí*).

 

These pronouns are easy to remember with sentences incorporating the
same forms:

 

*Quant vu have? Nequant.* -- How much do you have? Nothing.

*Quant vu have? Alquant.* -- How much do you have? Some.

*Qui veni? Quicunc.* -- Who's coming? Whoever.

*Qui veni? Nequi.* -- Who's coming? Nobody.

*Quo tu have? Nequó.* -- What do you have? Nothing.

*Quem tu dat it? Nequem.* -- Who did you give it to? To nobody.

*Qualmen tu fat it? Talmen.* -- How did you do it? Like that.

 

Examples:

 

*Oh hom, conosse te self!* -- Oh human, know thyself!

*In li sam témpore e in li sam loc, mi amica.* -- At the same time and
in the same place, my friend.

*Si alcun fémina parla pri alquo, ella pensa pri alqui.* -- When some
woman talks about something, she thinks about someone.

*Chascun hom es forjero de su propri fortune.* -- Each person is the
forger of his/her own fortune.

*Ples dar me quelc libres, yo have qulec líber hores por leer!* --
Please give me some books, I have some free hours for reading.

*Placer a omnes on ne posse, es arte, quel nequi conosse.* -- Pleasing
all one cannot do, it is an art known by no one. (Note: in Occidental it
rhymes.)

*Ja pluri annus yo vive in ti cité.* -- I have lived in this city for
several years already. (Note: only the present tense is used here. *yo
ha vivet* is also acceptable)

*Il have poc espera.* -- He has little hope.

*Il have un poc de espera*. -- He has a little hope.

*Yo conosse un cert senior Miller, ma yo ne es cert, esque il es ci.* --
I know a certain Mr. Miller, but I'm not certain if he is here.

*It es tot egal, esque Vu vide li tot munde, o quelc partes de it.* --
It is all the same whether you see the whole world, or some parts of it.

*Quicunc va venir, yo ne es in hem!* -- Whoever comes, I'm not at home!

*Quocunc tu di, ples dir li veritá.* -- Whatever you say, please speak
the truth.

*Quelcunc labor vu fa, ples far it bon.* -- Whatever work you do, please
do it well.

 

 
