== Occidental Course in 10 Lessons (lessons 5-6)

 +

[[displaycontent]]
== Quinesim letion

 

=== 5.1 Texte

 

==== 5.1.1 Regress e progress

 

Etsi it sempre ne es litteralmen ver que it custa torrentes de sangue
por pussar li homanité in moventie un millimetre adavan, it támen es
ínnegabil e pruvat del experientie, que íncredibil mult eforties es
necessi por far li homanité comprender un nov idé, benque it vell
aportar it grand avantages. It existe tro mult homes, queles relate con
índiferentie e indolentie a lu nov, o monstra admaxim un platonic
benevolentie, e anc tales, queles combatte it con apert íntolerantie e
mem acumula barrieres e impedimentes por desfacilisar li progress del
cultur. In consequentie de lor ignorantie ili quasi time líber pensada e
li aparentie de nov idés, e ili da preferentie solmen a to, quo sta in
acordantie a lor propri restrictet saventies. Qual perseverantie de su
pioneros ha postulat e va postular li movement por un lingue
international, qual persistentie in li confidentie e esperantie al final
victorie del nobil idé!

 

Omni progress es li resultate de un tenaci luctada inter du tendenties:
un, quel crede in li permanentie de lu existent e insiste in li
conservation de it, e un altri, quel crede in li existentie de alquicos
plu bon. Fórsan con un cert exageration on nómina li unesimes frenatores
e reactionarios, li duesimes fantasistes e utopistes. Li fundamental
differentie inter li du partises es proprimen to, que li regressistes ne
conosse li essentie del nov idés e pro to ne posse apreciar lor valore e
importantie, durant que li progressistes es tro inclinat depreciar li
existentie del conservativ leges del realitá e li potentie del temporari
circumstanties. On vell posser nominar ti du partises realistes e
idealistes, de to ne vell esser alquant ínjust, nam anc li realistes
have su ideales, e anc li idealistes calcula con un realitá, quel posse
fórsan esser plu ver quam li evident.

 

Un filosof unquande ha expresset li sam pensa per ti paroles: "Li munde
sempre ha ridet pri to quo plu tard ha verificat se. In omni témpores
existe homes qui pensa, e homes qui ride. Quande li témpore ha passat e
un nov intrat – it ha sempre esset talmen, ne existe exceptiones – tande
li munde ha regardat a retro e erectet monumentes a tis qui pensat, e
ridet pri tis qui ridet."

 

[cols=",,,",]
|===
|*etsi*  |although  |*líttere*  |letter 
|*custar*  |to cost  |*sangue*  |blood 
|*pussar*  |to push  |*mover*  |to move 
|*negar*  |to deny  |*pruvar*  |to prove 
|*effortie*  |effort  |*avantage*  |advantage 
|*tro mult*  |too much  |*relater*  |to relate 
|*índiferentie*  |indifference  |*indolentie*  |indolence 
|*admaxim*  |at most  |*monstrar*  |to show 
|*apert* |open |*acumular* |to accumulate
|*barrar* |to bar |*impedir* |to impede
|*quasi* |as if, quasi |*timer* |to fear
|*aparer* |to appear |*acordantie* |accordance
|*restricter* |to restrict |*perseverar* |to persevere
|*persister* |to persist |*confider* |to confide
|*victorie* |victory |*nobil* |noble
|*tenaci* |tenacious |*luctar* |to fight, struggle
|*insister* |to insist |*alquicos* |some thing
|*fórsan* |perhaps |*cert* |certain
|*frenar* |to brake |*partise* |party
|*essentie* |essence |*apreciar* |to appreciate
|*valore* |worth |*importantie* |importance
|*inclinar* |to incline, tend |*depreciar* |to depreciate
|*lege* |law |*potentie* |might, power
|*circumstantie* |circumstance |*alquant* |quite
|*ínjust* |unjust |*calcular* |to calculate
|*unquande* |once |*rider* |to laugh
|*verificar* |to verify |*intrar* |to enter
|*regardar* |to regard |*retro* |backwards, retro
|*erecter* |to erect, raise |*exception* |exception
|===

 

 

==== 5.1.2 Economisation

 

Si noi vole economisar moné, noi deve deposir it e ne spoliar it in
omnidial micri expenses. Ma si noi vole economisar témpore, nor hores e
minutes, noi deve utilisar les, e plu exclusivmen ili es usat por digni
scopes, plu ili es transformat in un capitale de caractere,
intelligentie e potentie. Noi cresce ne in aritmetic, ma in geometric
progression, li flut de nov vive ne es solmen addit, ma multiplicat per
lu antean. Un nov pensa, quel on excisela, ne es solmen juntet al
anteyan pensas, ma transforma les e multiplica les, da nos nov
vispunctus, de queles noi vide omni relationes e idés in un altri
perspective.

 

Un passu ancor ad-supra li monte fa li horizonte plu vast in omni
directiones.

 

(Channing.)

 

[cols=",,,",]
|===
|*economisar*  |to economize, save  |*moné*  |money 
|*spoliar*  |to spoil, waste  |*plu...plu*  |the more...the more 
|*usar*  |to use  |*digni*  |dignified 
|*scope*  |goal, aim  |*flut*  |flood, flow 
|*anteyan* |former  |*exciselar*  |to chisel out (*ciselar* = to chisel)
|*junter*  |to join  |*passu*  |a step 
|*ancor*  |still, yet  |*ad-supra*  |up 
|*monte*  |mountain  |*vast*  |vast 
|===

 

 

==== 5.1.3 Li division de labor

 

Noi ha studiat mult e perfectionat mult, durant li ultim témpore,
concernent li grand invention del civilisation: li division de labor.
Solmen noi da it un fals nómine. It ne es, si noi expresse li veritá, li
labor, quel es dividet, ma li homes: dividet in segmentes de homes,
ruptet in micri fragmentes e pezzes de vive, talmen que li micri parte
del intelligentie, quel resta in un hom, ne es suficent por far un
pivote o un clove, ma exhauste se per far li fine de un pivote o li cap
de un clove. E li grand cri, quel eleva se ex nor industrial cités, plu
sonori quam lor sofflada de fornes – omnicos deriva de to, que noi
fabrica omnicos in ili, except homes. Noi inpallida coton, e indura
stal, e raffina sucre e modella ceramica, ma clarar, indurar, rafinar o
modellar un singul vivent anim, tó nequande trova se in nor
calculationes de profite.

 

(Ruskin)

 

Note: *to* is only written with an accent here to show emphasis
("...*that* is never found in our profit calculations").

 

[cols=",,,",]
|===
|*ultim*  |final, recent  |*restar*  |to remain 

|*cap*  |head  |*derivar*  |to derive 

|*concerner*  |to concern  |*suficent*  |sufficient 

|*cri*  |a cry  |*inpallidar*  |to bleach
(also *pallidar*, *in-* strengthens the verb a bit as in to bleach in) 

|*fals*  |false  |*pivote* |fulcrum, hinge 

|*clove*  |nail  |*elevar*  |to elevate, raise 

|*coton*  |cotton  |*sonori* |sonorous 

|*indurar*  |to harden  |*rupter*  |to break, rupture 

|*anim* |soul |*forn* |oven

|*pezze* |piece |*fine* |end
|===

 

 

==== 5.1.4 Sofistica

 

Un yun greco hat aprendet de Protágoras li arte de sofistes contra
payament de 50 mines ínmediatmen e ulterior 50 mines, quande il hat
victet in su unesim processu. Proque il tardat payar li ultim parte,
Protagoras comensat processu contra il. In ti die, in quel li judicament
evenit, li du parties incontrat ante li deliberationes del judicos.

 

"It es plu bon, que tu paya me nu," dit li mastro, "nam si yo victe, tu
va esser judicat a payar, e si tu victe, tande tu ya ha victet in unesim
processu, e va dever payar me anc in ti casu."

 

"No, ples atender un poc," replicat li yun mann, "si tu victe, tande yo
ne ha victet in mu unesim processu, e tande, comprensibilmen, yo ne deve
payar te e si yo victe, tande li judicament ya va esser tal, que yo ne
deve payar."

 

[cols=",,,",]
|===
|*aprender*  |to learn  |*judicar*  |to judge 

|*comprensibil*  |understandable, natural (*comprensibilmen* = of
course)  |*payar*  |to pay 

|*mine*  |mine (Ancient Greek currency)  |*tardar*  |to delay 

|*victer*  |to win  |*evenir*  |to happen 

|*judico*  |a judge  |*atender*  |to wait 

|í**nmediatmen ** |immediately  |*replicar*  |to reply 

|*mastro*  |master  |*comprender*  |to understand 
|===

 

 

==== 5.1.5 Li max perfect lingue

 

Un lingue, aprioric e logic, in quel chascun parol vell esser solmen un
signe de un sol fix notion, un lingue sin images e metáfores e sin alcun
associationes de idés, queles nequande vell lurar li pensa a altri
notiones, un tal lingue vell esser perfectissim, pur principiarimen, pur
teoricmen. Li paroles vell esser solmen instrumentes del pensa e necos
plu.

 

Ma, it es un fact, noi nequande vell posser aprender un tal lingue. To
es, si noi ne presuposi, que li vocabularium deve esser micrissim
possibil. Ma tande it ne vell esser possibil expresser to, quo un
civilisat nation, mem li micrissim popul, posse expresser per su lingue.
Li homan memorie besona firm punctus por adherer, ma sur li
calv, glacie-polit superficie del logic notiones it ne posse retener se.
Just caus lor ínperfectitás e ruditás li natural lingues da nos plu
secur adhesion por li memorie.

 

Li amore al metáfores es tam inradicat in nor mentes, que, etsi noi vell
posser dispensar li metáfores, noi támen ne vell voler it. In omni
lingues, nov e antiqui, on posse constatar li fenomen, que simplic,
descolorat nómines es viceat per paroles, queles per su images
e associationes de idés es quasi plu vivent, plu interessant. E noi
posse profetisar, que tam long quam nor homanité ne ha perdit se ancor
in pur ration, tam long quam sentiment e imagination ancor lude un rol,
tam long quam homes ama li flores del verne ne solmen li sicc folies del
autune – tam long un lingue aprioric, sin historie e sin metáfores ne
va esser parlat sur ti ci globe.

 

[width="100%",cols="25%,25%,25%,25%",]
|===
|*chascun*  |each  |*rud*  |rude, rough 

|*perdir*  |to lose  |*fix*  |fixed, fast

|*sentir*  |to feel  |*amore*  |love 

|*luder*  |to play  |*besonar*  |to need 

|*radica*  |a root  |*rol*  |role 

|*lurar*  |to lure  |*adherer*  |to adhere 

|*mente*  |mind  |*sicc*  |dry 

|*pur*  |pure  |*calv*  |bald 

|*dispensar* a|
to dispense,

rid oneself of

|*necos* a|
nothing

(n.b. derived from ne+cose, thus accented as *necós* and often written
with the accent)

|*glacie* |ice |*presupposir* |to presuppose

|*superficie* |surface |*vicear* |to replace
|===

 

 

==== 5.1.6 Proverbies

 

Honestie es li max bon politica.

Exemples es plu bon quam prescrites.

Laude fa bon homes plu bon, e mal homes plu mal.

Fortuna favora li braves.

Li oldes save, quo li yunes ne conosse, ma li yunes aprende, quo li
oldes ne posse.

Li bravo merite li bella.

De lu sublim a lu comic es sovente solmen un passu.

Leges es quam li texturas del aranés; li micri moscas es captet, li
grandes trapassa.

 

[cols=",,,",]
|===
|*texter*  |to spin  |*mosca*  |a fly 
|*laude*  |praise  |*arané*  |spider 
|*fortuna*  |fortune  |*meriter*  |to merit 
|*capter*  |to catch  |*brav*  |brave 
|*trapassar*  |to pass through  |  | 
|===

 

 

==== 5.1.7 Li historie

 

Per li studia del historie noi percepte li intim conexion, quel existe
inter lu present e lu passat. Li present moment es un transient cose, su
radicas es in lu passat, su esperas in lu futuri. Si omnicos vell
depender del subtil fil del fugient moment, quel ilumina e dura solmen
durant un move del ocul, solmen por evanescer in li abyss de Nihil,
tande omni vive vell significar solmen un exeada ad in li morte. Noi es
tro inclinat regardar lu passat quam alquicos mort, ma it existe ye
vivent evidentie in nor animas hodie. It opresse nos e stimula nos al
action, it tirannisa nos e inspira nos a coses plu sublim.

 

[cols=",,,",]
|===
|*percepter*  |to perceive  |*passat*  |past 
|*subtil*  |subtle  |*Nihil*  |Nothing 
|*conexion*  |connection  |*futuri*  |future (adjective) 
|*fil*  |thread  |*significar*  |to mean / signify 
|*transir*  |to transit, go by  |*fugir*  |to flee 
|*exeada*  |exit  |*evanescer*  |to evanesce 
|*morte*  |death  |*mort(i)*  |dead 
|*depender*  |to depend  |*abiss*  |abyss 
|===

 

 

==== 5.1.8 Aforismes

 

Li historie demonstra, que un energie e scop-conscient labor finalmen
triumfa, ne pro que grand masses de homes auxilia realisar alcun cose,
ma sovente pro que li iniciatores sin repose acte por li idé. (O.
Fehlmann.)

Sovente it es plu desfacil viver por un idé quam morir por it. To es li
diferentie inter heróes e martiros. (O. Wilde.)

Du levul gantes de fa un pare de gantes, du demí veritás ne fa un
veritá. (Multatuli.)

 

[cols=",,,",]
|===
|*scop-conscient*  |goal-conscious  |*auxiliar*  |to help 
|*iniciar*  |to initiate, start  |*gante*  |glove 
|*alcun*  |some  |*repose*  |repose 
|*finalmen*  |finally  |*cose*  |thing 
|*levul*  |left  |  | 
|===

 

 

=== 5.2 Explanations

 

Endings for types of words such as nouns, adjectives and the like are no
more obligatory in Occidental than in natural languages. Vowels at the
end of words are mainly justified by ease of pronunciation.
Internationally-known words found in many languages are just as diverse
in Occidental as in other languages. Some of them are: firma (company),
boa, auto, conto (account), cangurú (kangaroo), marabú (a type of tree),
tabú, colibrí (hummingbird), lampe, idé (idea), etc. Nouns, adjectives
and particles can end in any vowel or consonant, as long as the word can
be clearly spoken. A very common end vowel in Occidental is:

 

*-e*

 

which does not have any particular meaning, but is used for ease of
pronunciation and to distinguish words from others. Nouns: teatre,
centre, lampe (nouns). Adjectives: pie (pious), varie (varied). An
adverb: sovente (often). The -e is also seen in plurals after a
consonant before the -s: nation, nationes. It can also play a role in
distinguishing a noun from an adjective: central (central), centrale
(headquarters).  The most commen adjectival ending is:

 

*-i*

 

which is also used for pronounciation and distinguishing types of words:

 

vivaci = vivacious/lively, sagi = wise, omni = all, stormi = stormy
(storm = storm), uniformi (the noun is *uniform*).

 

For nouns referring to living creatures, the ending

 

*-o*

 

is used to indicate the male gender, and

 

*-a*

 

the female, when necessary. (Genderless or unspecified: -e or no
ending): *un germano* = a German man, *un germana* = a german
woman, **amico **= friend, **amica **= female friend, **cavallo **= male
horse (stallion), **cavalla **= female horse (mare),**gallino **=
rooster, **gallina **= hen.

 

In many other words the -o ending is used for a specific item, while -a
refers to something in a more collective sense, a location or
time. **rosiero **= rose bush, **rosiera **= rose garden, **barberia **=
barbershop, **auditoria **= auditorium, **imperia **= empire, etc.

 

Substantival (noun) adjectives may be used as nouns:

 

**li rich e li povri **= the rich and the poor

**li riches e li povres **= the rich and the poor (lit. the rich ones
and the poor ones)

 

The same endings can be used on adjectives to indicate the gender:

 

**li bello **= the handsome man

**li bella **= the beautiful woman

**li yunos **= the young ones (boys)

**li yunas **= the young ones (girls)

 

The ending can also be used on the definite article itself if there is
no particular noun in mind:

 

Masculine: *lo bell* = the handsome

Feminine: *la bell* = the beautiful

Neutral: *lu bell* = the beautiful

 

Note: lu is by far the most often used of the three above.

 

Finally, the ending -um can be used on an adjective to form a noun that
expresses the general idea of something: **novum **=
newness, **bonum **= goodness, **caracteristicum **= characteristicness.

 

==== 5.2.2 Comparative forms

 

Comparative (more, less) and superlative (most, least) adjectives are
formed in the following way:

 

li bell flore = the beautiful flower

li **plu **bell flore = the more beautiful flower

li **max **bell flore = the most beautiful flower (also *maxim*)

li **min **bell flore = the less beautiful flower (also *minu*)

li **minim **bell flore = the least beautiful flower

li bell**issim** flore = the very beautiful (gorgeous, etc.) flower

 

The above are the regular comparative forms. Other less regular forms
exist due to their being part of already existing international words:

 

**bon **= good

**melior **= better (a**melior**ar, to improve)

**optim **= best (**optim**ist)

**mal **= bad

**pejor **= worse (**pejor**ativ)

**pessim **= worst (**pessim**ist)

**grand **= large

**major **= larger (**major**ité)

**maxim **= largest (**maxim**al)

**micri **= small

**minor **= smaller (**minor**ité)

**minim **= smallest (**minim**al)

 

(note: minim included here for the sake of completeness even though it
is part of the regular comparative forms)

 

==== 5.2.3 Diminutive

 

The usual diminutive (making smaller) suffix is:

 

*-ett*

 

**filietto **= sonny, **filietta **= little daughter (**filie **= child)

**brunetti **= brunette (brun = brown), **rosette **= rosette (from
rose, rose)

**cigarette **= cigarette (**cigare **= cigar)

**pincette **= pincette (**pince **= pincers)

**foliettar **= leaf through (**folie **= leaf)

**volettar **= flutter (**volar **= fly)

 

The same suffix is used to indicate small tools or instruments.
Example: **inflammette **= match (from flamme, flame), *tenette* = grip,
hilt (on a sword, from *tener*, to hold)

 

==== 5.2.4 Pejorative

 

The usual suffix to make something pejorative is:

 

*-ach*

 

cavallacha = nag (cavall = horse)

populache = mob, the unwashed (popul = people)

criticachar = complain, bitch (criticar = to criticize)

imitachar = to ape (imitar = imitate)

 

Many other expressions can be pejorative on their own: **simiar **also
means to ape (**simie **= monkey, ape).

 

==== 5.2.5 -ar

 

Verbs are usually formed with the -ar suffix, the most commonly used for
immediate derivation.

 

**formar **= to form (from *form*, form)

**laborar **= to work (from *labor*, work)

**salar **= to salt (from *sale*, salt)

**motivar **= to motivate (from *motiv*, motive)

**coronar **= to crown (from *coron*, crown)

**scruvar **= to screw (from *scruv*, screw)

**brossar **= to brush (from *bross*, brush)

**lactar **= to milk (from *lacte*, milk)

**sanguar **= to bleed (from *sangue*, blood)

**dominar **= to dominate (from *dómino*, master)

**plenar **= to fill (from *plen*, full)

**exsiccar **= to dry out (from *sicc*, dry)

**abellar **= to beautify (from *bell*, beautiful)

**afacilar **= to facilitate (from *facil*, easy)

 

As the last examples show, adjectives are frequently made into verbs
along with a preposition in front.

 

The present participle can also be made into verbs:

 

**sedentar **= to sit (from **sedent **= sitting, thus to "make sit")

**reviventar **= to revive (from **re **+ **vivent **= living, thus to
"re-make living")

**calentar **= to heat (**caler **= to feel warm, thus *calent* = being
warm and **calentar **= to make warm)

 

 

 

*-isar*

 

"To make thus", "to make as", similar to English:

 

**electrisar **= to electrify (charge with electricity)

**idealisar **= to idealize (from *ideal*, ideal, which comes
from *idé*, idea)

 

Note: electrisar is formed from a sort of hidden word (electr-) formed
by removing the suffix -ic, which forms other words as well such
as *electron *(the** -on **suffix will show up in the next chapter).

 

*-isar* can also be used, though more rarely, with nouns. They form
words you already know:

 

**canalisar **= to canalize (from *canale*, canal)

**tirannisar **= to tyrannize (from *tiranno*, tyrant or bully)

**terrorisar **= to terrorize (from *terrore*, terror)

 

 

*-ificar*

 

"To make into something", "to bring towards" - similar to -isar above
but slightly different.

 

**electrificar **= to electrify (note the difference between this
and **electrisar **above. **Electrisar **means to make something
electric, to charge it, while **electrificar **means to equip something
with electricity or make electric. Flipping a switch would
thus **electrisa **one's room, while equipping a village with power
cables with **electrifica **it. Though such subtle differences are not
too relevant in fluid conversation)

**identificar **= to identify (from *identic*, identical; identify has
these two meanings in English as well: 1 to establish the identity of
and 2 to make the same)

**falsificar **= to falsify (**fals **= false)

**rectificar **= to rectify (**rect **= right)

 

 

*-ijar*

 

To become. The word itself to become is *devenir*, and -**ijar **is an
alternate way of expressing the idea.

 

**maturijar **= to mature, become mature (= *devenir matur*)

**verdijar **= to green, become green (= *devenir verd*)

**oldijar **= to become old, age (= *devenir old*)

 

 

*-ear*

 

This suffix forms verbs that indicate a swinging or repeating motion, or
an intense state of being.

 

**undear **= to undulate, wave (from *unde* = a wave)

**flammear **= to flicker (from **flamme **= flame)

**verdear **= to green (greening fields, verdant forests, etc.)

 

 

==== 5.2.7 Suffixes for verbal nouns

 

The verbal stem (present tense) can also be used as a verbal noun, which
refers to a simple action.

 

*yo pensa* = I think; *mi pensa* = my thought

*il batte* = he hits; *un batte* = a hit

 

Note: for -ar and -ir verbs, this often gives the opportunity to make
very subtle distinctions if one wishes, due to the general -e and
vowelless ending for nouns. This is better explained with examples:

 

The word **pensa **refers to a thought, while **pense **refers to
thought. Both are correct, and have a subtle difference: *Li pensa venit
a me* = the thought came to me (**pensa **is preferred here as it refers
to the action of thinking); **penses **e **paroles **=** **thoughts and
words. This is, again, a subtle distinction that one may use if wished
or ignore at will, like the English words clothing and clothes, dinner
and supper, precise and accurate, venom and poison, etc.)

 

We have already gone over the suffixes -ion and -ura in chapter 3. Here
are some others:

 

 

*-ada, -ida*

 

*-ar verbs use the -ada suffix, -er and -ir verbs the -ida suffix. It
refers to the activity of a verb in its duration.*

 

**promenada **= a walk, a stroll, a promenada (**promenar **= to stroll)

**cannonada **= cannonade (a repeated firing of cannons,
from *cannonar*, to fire a cannon, from **cannon **= a cannon)

**cavalcada **= a cavalcade, riding (**cavalcar **= to ride)

**currida **= running (**currer **= to run)

 

 

*-ntie*

 

More or less equivalent to the English -nce (designates a condition in
its duration), this is formed from the -nt participle plus -ie.

 

**existentie **= existence (**exister **= to exist)

*índependentie* = independence (**depender **= to depend)

**confidentie **= confidence (**confider **= to confide)

**provenientie **= provenance (**provenir **= originate)

**tolerantie **= tolerance (**tolerar **= to tolerate)

 

 

 

*-ment*

 

(This suffix requires some special attention, as their international use
is more limited than the way they are used in English and in French
which uses -ment with great frequency)

 

Forms nouns that signify a special, concrete action or its outcome or
the means for it.

 

**experiment **= an experiment (**experir **= to
experience, **experientie **= experience)

**fundament **= a foundation (**fundar **= to found, fundation refers to
a founding)

**impediment **= an impediment (**impedir **= to impede, impedition
refers to an impediment in the sense of impeding)

**nutriment **= nutrition (*nutrir* = to nourish, *nutrition* =
nutrition in the sense of nourishing)

**developament **= development, a development (**developar **= to
develop, **developation **= development in the sense of developing)

 

Some other examples Edgar de Wahl mentioned in Cosmoglotta:

 

*abonnament *(subscription) is not the act of subscribing but the legal
status where one is subscribed

*payament *(payment) is the money that one pays

*medicament *(medicine) is the medicine itself, not the act of
medication

**ornament **is the ornament itself

**testament **is the legal document

**argument **is the argument that one makes, not the act of arguing

 

 

*-age*

 

{empty}1) the activity of a verb, mainly industrial or professional, its
expenses, etc.:

 

*arbitrage* = arbitration, refereeing

**inballage **= packing (**inballar **= to pack)

**plantage **= planting

**passage **= passage (**passar **= to pass)

**rafinage **= refining (**rafinar **= to refine)

**postage **= postage

**doanage **= customs (collecting tax; **doane **= tax)

 

 

{empty}2) collections with order, things made by:

 

*tonnage* = tonnage (**tonne**= ton)

**foliage **= foliage (**folie **= leaf)

**boscage **= boscage (**bosco **= bush)

**plumage **= plumage (**plum **= feather, pen)

 

 

 

 

== 6 Sixesim letion

 

 

=== 6.1 Texte

 

6.1.1 Li festivitás ye li ocasion del ottcentenarie del cité capital

 

Ja ante ott horas in li matin li publica comensat barrar li stradas
ductent al grand plazza de parade, talmen que li policistes havet mult a
far por retener it in respectabil distantie. Legionarios e pumperos
esset comandat quam auxiliatores por li policie.

 

Ja on posset vider un policist, forductent un laceron e un fripon, quel
esset arrestat quam furtard. Un trincard esset remarcat de un policist,
al gaudie de un galoppon de hotel. Un dormion presc restat sub un
automobil.

 

In li sud-front del plazza esset constructet tribunes por li special
invitat publica. On videt functionarios de divers institutiones,
publicistes e jurnalistes e anc cinematistes. Ye nin horas e tri quart
li central tribune comensat plenar se. Ultra li presidente e su marita,
nascet princessa D. con su can Bolognes, li comissario de policie, li
magistrate municipal, li borgomastro Ciennes on videt mult altri distint
persones. In li diplomatic loge prendet plazze li ambassadores anglesi,
francesi, german, chinesi, japanesi, con lor damas, inter ili li marita
del ambassador italian, li conosset patronessa del societé de
protectores de infantes. Inter li deputates del parlament on remarcat
omni fractiones comensante del max revolutionari bolshevistes, til li
conosset reactionario M., actionario e companion del chef del Grand
Magazin Central, e anc quelc pastores del partise Christian.

 

Presc precis ye deci horas comensat li grand parade militari con elegant
cavalcada del cavalleristes, inter queles excellet li lanseros. Li
chasseros con lor coloristic vestes evocat general sensation. Poy
defilat li artilleristes con lor modernissim mortatori apparates. Inter
li infanteristes marchat max von li musqueteros, flancat per li
jaloneros. Li officeros portat su órdenes, e on posset remarcar, que li
pedones esset plu decorat quam li truppes de ingenieros.

 

Pos li militare defilat li brigade de pumperos e depoy sequet li
scoleros de divers institutes con lor directores, preceptores e
instructores. Pos ili marchat li professionales: tallieros, chapeleros,
sapateros, barberos, carreteros, carpenteros, mureros, vitreros,
ferreros etc. Li ovreros del fabricas ne prendet parte in ti parade, ma
li mineros del vicin carbon-miniera esset representat per lor delegates
in su original costumes.

 

Nu sequet li sportiv organisationes e on posset vider mult conosset
championes del footballistes, boxeros, velocipedistes, canotistes etc.
In fin sequet un corso de automobilistes e motoristes.

 

In li véspere in li vast sala municipal esset arrangeat un grand festa,
u incontrat se li tot population per su eminent laboratores scientific,
politic, artistic e social. Inter li

scientistes on posset reconnosser li professores del universitá, li
romanist E., li germanist F., e li orientalist M. Omni scienties esset
representat, on videt juristes, medicos, inter ili li oculist S., li
internist A. e li dentist U. Anc conosset pictores quam li paisagist L.,
li portretist R. e li aquarellist e aquafortist K. participat al festa.
Ta esset anc li sculptor C. con su marita, li famosi actressa Lola C. On
vide li max different persones in amical conversation: ci un radical
socialist fonde se sub li ardent ocules del excentric baronessa S., ta
un prestro del metodistes parla con li millionario e bankero M. e li
proprietario del grand fabrica de motores, lord Ch. Li charitabil
comtessa T. sembla interessar se ye li activitá del conosset calvinistic
missionario B., un alt barbon, quel in ti desbarbat témpore es quasi un
anachronisme.

 

Li babillada cessat quande li trio: li pianisto Z., li cellisto Str. e
li violinista Senioretta

Ilona M. intonat un arie del local compositor G. Solmen in tard nocte li
festa trovat su fine, talmen que li reporteros havet mult a far scrir li
rapportes al rect témpore, e li redactores e correctores esset occupat
til li límite. Criticastros comprensibilmen ne esset content.

 

[cols=",,,",]
|===
|*cité capital* |capital city  |*presc*  |almost 
|*chapel*  |hat  |*picter*  |to paint 
|*matin*  |morning  |*ultra*  |besides, beyond 
|*sapate*  |shoe  |*paisage*  |landscape 
|*ducter*  |to lead  |*marita*  |wife 
|*barbe*  |beard  |*sculpter*  |to sculpt 
|*retener*  |keep back  |*veste*  |clothing 
|*mur*  |wall  |*fonder*  |to melt 
|*flanc* |side |*vitre* |glass
|*arder* |to burn |*auxiliar* |to help
|*jalon* |a pole |*ferre* |iron
|*laceron* |a rogue, rascal |*pede* |foot
|*pedones* |pedestrians |*ovrero* |worker
|*fripon* |rascal, scoundrel |*mineros* |miners
|*alt* |high |*galoppon* |runner, errand-boy
|*depoy* |thereafter |*intern* |internal
|*babilar* |to chat |*dormion* |sleeper, sluggard
|*talliero* |tailor |*dente* |tooth
|*límite* |limit |  | 
|===

 

 

 

==== 6.1.2 Un farme in li subtropic landes

 

 

Li farmero amabilmen monstrat nos su possessiones. Sur li corte noi
videt a dextri un grand dom. To esset li gallinería, u esset anc anates,
ganses e quelc altri avies. Detra ti voliera extendet se un pisciera
quel servit solmen quam anguilliera. Trans li bassines esset visibil li
grand cafeiera e in lontan un piniera. In li horizonte stat blu montes,
u esset un rich marmoriera, un ardesiera e altri minieras. Li sómmites
esset covrit de nive e glacieros. Del altri látere del corte esset li
orangería con mult tropic plantes e fructieros, bananieros, palmes e
exotic flores. Noi eat sur un bell planat via, de un látere de quel
extendet se un vast herbiera con bellissim trifolie e anc mult bell
flores de camp, queles injoyat li paisage. Ma li farmero totmen ne esset
content con ti malherbe, quam

il nominat les. Il haltat e prendet ex li tasca un tabaciere e presentat
nos quelc cigares: "Vu ne posse imaginar Vos," dit il, "quant me despita
li insectes! vu vide ta li pomiera juntet a mi parc. It es presc vivid
pro li mult vermes, con queles yo guerrea nu ja quelc annus. Anc li
verdi pedicules de folies in mi adjacent pruniera, malgré omni
precautiones, expande se in un horribil maniere."

 

"Esque Vu have forsan formícas?"

 

"O yes. Ci es pluri formicieras in li boscage vicin. Ili es tre laborosi
insectes. Ples notar que just li formícas cultiva li pedicules, e yo
posse solmen consiliar Vos tam rapid quam possibil exterminar omni
formicieras. Ili es tre nociv animales in un fructiera."

 

"Advere! Nu yo va secuer Vor consilie. Ples regardar tra ti clariera,
quel aperte nos li vide súper li mare. Ta Vu posse vider un cannoniere e
du destructores, queles crucea in ti regiones."

 

"Quel es ti nave, quel sub segles veni al portu?"

 

"To es nor seglero, quel aporta nos salpetre por amelioration del terre.
It veni del famos nitrieras in Chile."

 

Pos har fat un promenada tra li principal branches de su proprietás, li
farmero invitat nos in su "garsoniera," quam il nominat su hem nu,
proque su marita esset in un sanatoria. Quande noi hat sedentat nos in
li comod apoyieres, sub li grand castaniero, un servitor aportat sur un
tablette un chinesi teiere con tasses. Pos har trincat té e restaurat
nos un poc, noi eat regardar li industrial institutiones, li spritería,
li lavería, sapatería, carpentería e ferrería, u on fat omni ferrin
ovres til li max fin ferreríes ornamental. Specialmen simpatic esset to,
que on totmen ne videt forjettat ferrallia, quel talmen desgustant
abunda in altri tal ovrerías. Li old forjero con su long albi barbe stat
apu li incude avan li foyiere con ardent brase illuminant su energic
facie, un image del old témpore.

 

 

=== 6.2 Explanations

 

The following suffixes create nouns that refer to persons.

 

*-er-*

 

(From nouns) Similar to -er in English, refers to a person who is
engaged in a type of work, or more rarely someone who coincidentally is
engaged in a task.

 

**molinero **= miller (**moline **= a mill)

**barbero **= a barber (**barbe **= beard)

**lavera **= washwoman (**lava **= washing)

**passagero **= passenger (**passage **= passage)

 

 

*-ist*

 

(From nouns) The follower of an -ism, or someone engaged in some sort of
artistic, ideal, scientific, military, technical or sport-related
occupation:

 

**librist **= book lover (**libre **= book)

**socialist **= socialist (**social **= social)

**Bonapartist **= Bonapartist (follower of Napoleon Bonaparte)

**Darwinist **= Darwinist

**oculist **= eye doctor (**ocul **= eye)

**cavallerist **= cavalry trooper (**cavallerie **= cavalry)

**machinist **= machinist (**machine **= machine)

*telegrafist* = telegrafist (**telegraf **= telegraf)

**automobilist **= automobilist

 

 

*-or*

 

(formed from verbs) Explained in lesson 3, a simple doer of an action. 
Note the following:

 

laborero = a professional worker (this is the -er- suffix). This is
derived from the noun labor + ero

laborator = a worker in general (this is the -or suffix). This is
derived from laborar --> labora + t + or

 

 

*-ario*

 

A person that is characterized through something exterior, such as a
career:

 

**millionario **= millionaire (**million **= million)

**missionario **= missionary (**mission **= mission)

**functionario **= government worker (from *function*)

**bibliotecario **= librarian (**biblioteca **= library)

**notario **= notary (**nota **= enrollment, registration)

 

 

*-on*

 

A person characterized by an inner or natural character:

 

*dormion* = sluggard, sleepy head (**dormir **= to sleep)

**grison **= greybeard (**gris **= grey)

**savagion **= savage (**savagi **= wild)

**spion **= spy (**spiar **= to spy)

 

-on also serves as a suffix for objects, often implying a greater size:

 

**cannon **= cannon (**canne **= reed)

**ballon **= balloon (**balle **= ball)

**galon **= braid, military stripe (**gala **= gala, festival, pomp)

 

 

 

*-ard*

 

A person with a negative or criminal quality:

 

**falsard **= counterfeiter (**fals **= false)

**dinamitard **= terrorist who attacks with dynamite

**mentiard **= liar (**mentir **= to lie)

 

 

 

*-astro*

 

Someone unskilled at his or her profession:

 

**medicastro **= quack (*medico* = doctor)

**politicastro **= political hack, demagogue, politicaster
(**politico **= politician)

**poetastro **= rhymester, versifier, poetaster (**poete **= poet)

 

 

*-es-*

 

Resident of a place or someone who originates from it (also as an
adjective):

 

*franceso* = Frenchman (**Francia **= France)

**francesa **= Frenchwoman

**francesi **= French

**borgeso **= bourgeois, middle-class person (**borgo **= borough, town)

**viennesa **= woman from Vienna

 

 

*-essa*

 

Suffix for females indicating an office or dignified position:

 

**comtessa **= countess (**comte **= count)

**princesse **= princess (**prince **= prince)

**imperatressa **= empress (**imperator **= emperor)

**actressa **= actress (**actor **= actor)

 

Note that *-or* drops the *o* in this suffix.

 

 

 

==== 6.2.2 Qualitative suffixes

 

The following suffixes form many of the nouns referring to the states
and properties of other words.

 

*-ie*

 

An abstract state:

 

**maladie **= sickness (**malad **= sick)

**elegantie **= elegance (**elegant **= elegant)

 

Derivations from participles are particularly numerous:

 

**existentie **= existence (**existent **= existing). The ending -ntie
was covered in the 5th lesson, and we can see that it is simply the
present participle -*nt* plus *-ie*.

 

It may be used on nouns as well to make them abstract:

 

**seniorie **= lordship (**senior **= lord, sir)

**amicie **= friendship (**amic **= friend)

**astronomie **= astronomy (**astronom **= astronomer) and many other
types of sciences

 

 

 

*-tá*

 

Quality or character, more or less equivalent to English -ty:

 

**qualitá **= quality (*qual(i)* = what a)

**homanitá **= humanity (**homan **= human (adjective), from **hom **=
human, (noun))

**amabilitá **= amiability, kindness (**amabil **= amiable, kind)

**membritá **= membership (the status of being a member)

 

Words that refer to a group of people or things use -*té *instead of
-*tá*:

 

**homanité **= humanity, as in the grouping of people as a
whole. **homanitá **above refers to the character of being human
(humanity in the sense of showing kindness and decency)

**societé **= society (**socio **= associate, member)

**membrité **= membership (all the members of something)

 

 

*tá or té?*

 

Besides the above, -**té **is much more limited in scope and any
doubtful cases are given the -**tá **ending, such
as *universitá *(university), which is neither the character of being a
universe (*universe* + *tá*) nor a collection of universes
(*universe* + *té*). In the same way, society (societá) is not simply
the state of being a *socio*, but it is also not a collection of them (a
society is not simply a collection of associates) and thus it
becomes *societá*. Rule of thumb: when in doubt, it's probably *-tá*.

 

 

*-ore*

 

{empty}1. (from verbs): a state of feeling, activity, temperature, etc.

 

**amore **= love (from *amar*, to love)

**terrore **= terror (from **terrer **= to frighten) 

**calore **= heat (**caler **= to be hot)

 

{empty}2. (from adjectives): size, value:

 

**longore **= length (**long **= long)

**grandore **= size (**grand **= large)

 

 

*-esse*

 

Special property or condition, most similar to English -ness. Examples:

 

**altesse **= highness (**alt **= high, **altore **=
height, **altitá **= the quality of being high)

**grandesse **= greatness, magnitude (**grand **= large, **grandore **=
size, **granditá **= being large)

**yunesse **= youth (**yun **= young, **yunitá **=
youngness, **yunité **= the youth)

 

This is also the suffix used for bombastic titles such as your Highness
(*Vor Altesse*).

 

 

==== 6.2.3 Local e colectiv sufixes

 

*-ia*

 

is a frequent suffix for the names of places and countries:

 

**Germania **= Germany (**german **= german)

**dominia **= dominion (**dómino **= master)

**abatia **= abbey (**abat **= abbot)

**auditoria **= auditorium (**auditor **= hearer)

 

 

*-atu*

 

a legal, social, or public institution, state, or office (also location,
time, and territory). Often corresponds to English -at or -iat:

 

**viduatu **= widowhood (**vidua **= widow)

**celibatu **= celibacy (**celibo **= bachelor, single man)

**proletariatu **= proletariat (**proletario **= a proletarian)

**directoratu **= directorship (**director **= director)

**secretariatu **= secretariat (**secretario **= secretary)

**califatu **= caliphate (**calif **= caliph)

**episcopatu **= episcopate (office of a bishop, from **epíscop **=
bishop)

 

 

*-eríe*

 

An occupation and its activities. As -*ería*, it refers to the actual
location. Both are actually formed from the -**er- **suffix (doer of an
action), then -**ie **as above for the quality, or -**ia **for the
location.

 

**vitreríe **= glasswork, glassware (**vitre **= glass, **vitrero **=
glassworker)

**vitrería **= a glassworks (the place)

 

Beyond the occupation, it also refers to a character trait and its
manifestations, same as in English -ery:

 

**coquetteríe **= coquetry (flirtation, from **coquett **= coquettish or
flirtatious)

**bigotteríe **= bigotry (**bigott **= bigoted)

**diaboleríe **= devilry (**diábol **= devil)

 

 

*-iera, -iere, -iero*

 

These three are best learned together.

 

*-iera*: a vast location containing something

*-iere*: a vessel or container holding something

*-iero*: carrying something (forms trees as well - 'carriers' of their
fruits)

 

-*iere* words:

**cigariere **= cigar case (**cigar **+ iere)

**tacabiere **= a tobacco case (**tabaco **+ iere)

**candeliere **= candle box (**candel **= candle)

 

-iero words:

**pomiero **= apple tree (**pom **= apple)

**orangiero **= orange tree (**orange **= orange)

**glaciero **= glacier (**glacie **= ice)

**candeliero **= candlestick

 

-iera words:

**pisciera **= fish pond (pisc = fish)

*torfiera* = peat bog (torf = peat)

**formiciera **= anthill (formíca = ant)

 

 

*-uore*

 

A place or device where something is done:

 

**trottuor **= sidewalk (trottar = trot, jog)

 

 

*-ade*

 

A consecutive, ordered series or certain amount of something:

 

**colonnade **= colonnade (**colonne **= column)

**boccade **= mouthful (**bocca **= mouth)

 

 

*-allia*

 

An unordered or pile of something:

 

**antiquallia **= old junk (**antiqui **= old)

**canallia **= pack of dogs (*can(e)* = dog)

 

 

*-arium*

 

A more scientific or specialized grouping of something.

 

**dictionarium **= dictionary (**diction **= a diction)

**herbarium **= herbarium (**herbe **= grass, herb)

**planetarium **= planetarium (**planete **= planet)

 

 

 
