== Occidental Course in 10 Lessons (lessons 9-10)

 +

[[displaycontent]]
== 9 Ninesim letion

 

=== 9.1 Texte

 

==== 9.1.1 Un parol - un novelle

 

 

Si yo prende un parol ex un lingue, it va racontar me alcun
cultur-historic facte. Lass nos, por exemple, prender li german parol
infanterie. Su form indica, que it es un parol pruntat ex li francesi
lingue. Ergo li franceses deve har havet un cert influentie concernent
li developation e organisation del german armés, altrimen on vell har
conservat li genuin old german parol "Fußvolk," usat ancor in li
decisixesim secul. Ma li parol explica ancor plu. It di, que originalmen
it deve har esset usat por un cert sorte del infanterie, a saver, por li
guardie del Infante de Hispania. Li "Infante" de Hispania es identic con
li international e pro to anc occidental parol "infante," originant del
latin „infans,“ quel es composit del prefix "in" (ne) e "fans"
(parlant), to es, un hom, quel ancor ne posse parlar. Talmen yo veni in
mi exploration a plu e plu lontan témpores e popules, e yo fini che li
unesim conosset form e sense del parol, che li etimon. Li historie de un
parol es un micri novelle, un excerpte ex un immensimen grand libre: li
Historie del Homanité.

 

[cols=",,,",]
|===
|*indicar*  |to indicate  |*concerner*  |to concern 
|*infante*  |infant  |*excerpte*  |excerpt 
|*pruntar*  |to borrow |*developar*  |to develop 
|*lontan*  |far  |*influentie*  |influence 
|*genuine*  |genuine  |*etimon*  |etymon (a word root - cf. etymology) 
|===

 

 

==== 9.1.2 Li grand idés

 

To quo es necessi por elevar li spíritu, ne es to, que un hom save
omnicos, quo ha esset pensat e scrit in relation al spiritual natura, ne
es to, que un hom deveni un enciclopedie, ma to, que li grand idés, in
quel omni decovritiones termina, queles summa omni scienties, queles li
filosof extrae de ínfinit detallies, es comprendet e sentit. It ne es li
quantitá, ma li qualitá de saventie, quel determina li dignitá del
anima. Un mann de immens erudition posse pro su manca de larg e extensiv
idés, esser mult plu inferior in intelectu quam un laborero, qui, con
micri saventies, támen ha trovat grand veritás. Un grand anima es format
per poc grand idés, ne per infinitá de íncoherent detallies. Yo ha
conosset tre doct homes, qui apparet a me tre povri in intelectu, proque
ili havet null grand pensas. Quo vale to, que un mann ha studiat
quantcunc detalliat li histories de Grecia e Roma, si per li historic
documentes li grand idés de libertá e bellitá e bravitá e spiritual
energie ne ha flammat quam vivent foyes in su anima? (Channing.)

 

[cols=",,,",]
|===
|*elevar*  |to raise  |*erudition*  |erudition 
|*terminar*  |to end  |*larg*  |broad, wide 
|*determinar*  |to determine  |*bravitá*  |bravery 
|===

 

 

==== 9.1.3 Anecdotes

 

Du yun juristes, Miller e Brun, visitat sovente li sam yun dama. Un
véspere Miller esset sol con ella. Il dit in tendri ton:

 

"Esque Vu pensa, María, que Vu posse subitmen abandonar patre e matre,
sestra e fratre, ti plesent, comfortabil dom, e emigrar in li savagi
West con un yun jurist, qui posse viver solmen per su profession, e
serchar ta un nov hem, in quel ambi posse esser felici?"

 

Inclinante su bell cap sur li epoles de Miller, ella chuchotat
tendrimen: "Yes, yo pensa que yo posse, Arnold."

 

"Bon," dit Miller, "it es Brun, qui intente emigrar e desira un sponsa,
yo va mentionar to a il." – – –

 

A un yun mann, qui sedet silent in un companie, Teophrástos, li famos
grec filosof, dit: "Si Vu es folli, Vu acte sagimen; si Vu es sagi, Vu
acte follimen." – – –

 

[cols=",,,",]
|===
|*subitmen*  |suddenly  |*savagi*  |wild 
|*matre*  |mother  |*epol*  |shoulder 
|*sponsa*  |spouse (female)  |*sestra*  |sister 
|*serchar*  |to search  |*chuchotar*  |to whisper 
|*foll(i*) |crazy  |*fratre*  |brother 
|*ambi*  |both  |*tendri*  |tender 
|*emigrar*  |to emigrate  |*felici*  |happy 
|*intenter*  |to intend  |  | 
|===

 

 

==== 9.1.4 Aforismes

 

 

Mem li deos combatte li stupiditá in van.

 

Li paroles es solmen vente – li erudition consiste solmen ex paroles –
ergo li erudition es solmen vente. (Swift.)

 

Li gazettes es li secund-indicatores del historie. Ma ili es sovente de
plu ínnobli metalle quam li altri indicatores, e ea anc rarmen correct.
(Schopenhauer.)

 

Quande Pythagoras hat decovrit su conosset teorema, il aportat un
hecatombe al deos. Desde to li boves treme, tam sovente quam un nov
veritá es decovrit. (Börne.)

 

Li majorité del homes lassa voluntarimen presser se in li carne li spine
de un fals teorie, ma ili defende se per omni forties, si on vole denove
extraer it. (Pauly.)

 

 

=== 9.2 Explanations

 

From adjectives we can create adverbsl by adding the ending *-men*. This
ending does not change the stress:

 

*Un prudent mann acte prudentmen.* = A prudent man acts prudently.

 

When the meaning is clear, the adjective by itself may function as an
adverb:

 

*Il parla bon* = He speaks well (lit. good)

*Li sole luce clar* = The sun shines clear(ly).

 

Another way to form an adjective is to use *in maniere*:

 

*Il scri in elegant maniere* = He writes in an elegant manner.

 

Prepositions can be used to form adverbs: *in (li) nocte* = at night,
*in fine* = finally, *in general* = in general, *in ocasion* = on
occasion, *per ocasion* = by chance, etc.

 

Pronomial adverbs

 

*u?* -- where?

 

*ci* -- here

*ta* -- there

*necú* -- nowhere

*alcú* -- somewhere

*partú* -- everywhere

*supra* -- above

*infra* -- below

*extra* -- outside, besides

*intra* -- inside

*detra* -- behind

 

*a(d) u?* -- to where?

 

*a(d) ci* -- to here

*a(d) ta* -- to there

*adavan* -- forward

*retro* -- backward

*ad supra* -- upwards

*a bass, ad infra* -- downwards

*ex, ad extra* -- out from

*in, ad intra* -- into

 

*de u?* -- from where?

 

*de ci* -- from here

*de ta* -- from there

*de supra* -- from above

*de infra* -- from below

 

*qualmen?* -- how? in what way?

*talmen* -- in that way

*tam* -- so (with an adjective or adverb following)

*alquam* -- somehow

*quande?* -- when?

*tande* -- then (also *alor*)

*unquande* -- once

*apen* -- hardly

*ne totmen* -- not entirely

*totmen ne* -- not at all

*forsan* -- perhaps

*junt* -- together

*presc* -- almost

*nequam* -- not at all

*nequande* -- never

*alquande* -- some time, ever

*poc a poc* -- bit by bit, gradually

*solmen* -- only

*ya* -- indeed, well (strengthens the meaning somewhat)

*yes!* -- yes!

*no!* -- no!

*ínterim* -- meanwhile

*nu* -- now

*strax* -- right away

*bentost* -- soon

*sovente* -- often

*ja* -- already

*jamá* -- (n)ever

*sempre* -- always

*antey* -- before

*quant?* -- how many?

*tant*-- that many

*nequant* -- none at all

*alquant* -- a certain amount

*poy* -- after

*in ante* -- beforehand, in advance

*depoy* -- from then

*ancor* -- still

*adplu, ulterior* -- furthermore

*hodie* -- today

*tre* -- very

*tro* -- too

*circa* -- around, circa

*mult* -- many

*ho-annu* -- this year

*ho-témpore* -- these times

*deman* -- tomorrow

*posdeman* -- the day after tomorrow

*yer* -- yesterday

*anteyer* -- the day before yesterday

*un poc* -- a bit

*suficent* -- enough

*vez* -- time (as in two times)

 

With the enclitic -cunc we get words like *ucunc* = wherever,
*quamcunc* = however, as ever, *quandecunc* = whenever, etc.

 

Some more examples showing their function?

 

*Qualmen Vu fa it? Talmen.* -- How do you do it? Like that.

*Quam bell es li flore!* -- How beautiful the flower is!

*Tam bell quam un flore.* -- As beautiful as a flower.

*Plu bell quam un flore.* -- More beautiful than a flower.

*Quam un rey. Quam rey.* -- Like a king. As king.

*Quam Vu save, it es talmen.* -- As you know, that's the way it is.

*Quant homes esset ta? Tant quant yer.* -- How many people were there?
As many as yesterday.

 

 

 

==== 9.2.2 Conjunctiones

 

The most frequently used conjunctions are:

 

*e* -- and

*e ... e* -- both ... and ...

*o* -- or

*o ... o* -- either ... or ...

*ni* -- not (stronger than *ne*)

*ni* .. *ni* -- neither ... nor ...

*sive ... sive ...* -- either ... or ...

*ma* -- but

*nam* -- for, because

*támen* -- however

*ergo, dunc, do* -- therefore, thus, etc.

*plu ... plu* -- the more ... the ...

*nu!* -- well!

*vi* -- behold, here are

*nu ... nu* -- first ... now the other (i.e. doing one thing and then
the other)

 

There are also some subordinate conjunctions:

 

*que* -- that (e.g. he said *that*)

*si* -- if

*quam* -- as, like

*esque, ca* -- whether, if (e.g. I don't know *whether*)

*quasi* -- as if, quasi

*benque* -- though, although

*etsi* -- albeit, although

 

With *quam* and *que* together with other words we get a large number of
conjunctions such as:

 

*sam quam* -- same as

*anteque (ante que)* -- before

*posque (pos que)* -- after

*proque (pro que)* -- because

*porque (por que)* -- in order that

*perque (per que) --* in that (because of...)

 

Note: the *que* here is not translated as "that" in English but carries
that sort of meaning. Point to take home: _Having *que* means the parts
of the sentence before *que* and after it can stand on their own._
Examples of conjunctions with and without *que* to demonstrate the
difference:

 

Il venit *ante* quin annus. -- He came five years ago. (*quin annus* on
its own is not a phrase)

Il venit *ante* *que* il hat trovat it. -- He came before he had found
it. (*il hat trovat it* on its own is a phrase)

 

Il laborat *pro* manca de moné. -- He worked due to lack of money.
(*manca de moné* is not a phrase)

Il laborat *pro que* il mancat moné. -- He worked because he lacked
money. (*il mancat moné* is a phrase)

 

Il luctat *por* su país. -- He fought for his country. (*su país* is not
a phrase)

Il luctat *por* protecter su país. -- He fought to protect his country.
(*protecter su país* is also not a phrase)

Il luctat *por que* su filies mey saver qui hat protectet lor país. --
He fought so that his children would know who had protected their
country. (*su filies mey saver qui hat protectet lor país* -- may his
children know wha had protected their country -- is a phrase!)

 

 

 

 

== 10 Decesim letion

 

=== 10.1 Texte

 

==== 10.1.1 "In comensa esset li parol"

 

Li famosi unesim frase del Evangelium de Johannes cela un profund sense,
anc si noi comprende it litteralmen. Nam solmen per su capabilitá
expresser per paroles su intern traviventies, su observationes e
sentimentes, su perceptiones e desiras e comunicar les, evenit li
metamorfose del hom ex un animale, solmen li linguistic talent corona li
hom quam li dómino del creaturas. Sin parol ne vell exister un clar
notion, sin notion null pensation, sin lingue null alt spiritual vive.
Nam li singul notiones, per li medie de queles li hom pensa, es
strictissim ligat con cert paroles, un real, ver pensada sin paroles ne
es possibil. Concedet que mani brevi pensation, mani actiones de vole
eveni instinctiv o intuitiv, un plu alt spiritual vive, quel eleva se
súper obscur fluctuationes de pur instinctes e perceptiones a plen
claritá e libertá del conceptiv pensada, es e va esser connectet a
linguistic capacitá. Omni spiritual valores li hom debi finalmen a su
talent de articulat parlation. Novális di unquande in su aforismes: "Li
grammatica es li dinamica del spiritual dominia. Un parol de comande
move armés, li parol "libertá" nationes."

 

Quande li poet e li pensator vaga líber ad in li immens dominia de
pensas, lor ales es li parol. Li parlant hom victe li circumant natura
per li parol e quam creator forma per li parol su propri, subjectiv
munde, in contraritá e quam contrast al sensualmen perceptibil
fenomenes: li munde del spíritu – de su spíritu. On ha dit, que li hom
es un hibride inter deo e animale, e yo vole dir que li paroles es li
scalunes de ti scaliere celesti, along quel il prova grimpar súper lu
pur animalic ad in li luce del spritualitá. De to seque anc, que li
lingue da nos li fundament e li unesim base de omni cultura. (Güntert.)

 

 

==== 10.1.2 Li mult lingues de Europa

 

Li lingual situation in li hodial Europa es paradoxal.

 

Li material civilisation, li scientie, e mem li arte unifica se plu e
plu. Li cultivat europano senti se quasi in hem in omni landes queles
have europan civilisation, it es, plu e plu, in li tot munde. Hodie
presc omni states guerrea per li sam armes. Sin cessa li medies de
intercommunication ameliora se, e in consequentie de to li terra sembla
diminuer se. Un Parisano es nu plu proxim a un angleso o a un germano
quam il esset

ante cent annus a un paisano francesi.

 

Li civilisation tende vers unitá.

 

It existe solmen *un* scientie, a quel li erudites de omni nationes
contribue, partú on studia li sam problemas per li sam procedes, per li
sam instrumentes. Li laboratorias de America e Japan labora pri li sam
questiones quam tis de Europa. Li observatorias del tot munde prepara un
carte de ciel, in quel ili execute chascun un parte. Un modern erudito
es, si il vole o ne, li colaborator de omnes, qui in li tot munde
cultiva li sam

scientie. It existe, por chascun specialitá scientific, un micri
comunité de erudites, qui, amicos o rivales, conosse unaltru, seque li
activitá de unaltru e reacte un a li altri.

 

Li scientie, quel es un, dómina un tecnica, quel anc es un. Chascun
decovrition scientific change li procedes de fabrication e li
conditiones de production. E omni nov procede de fabrication es rapidmen
conosset in li tot munde.

 

Li afferes comercial es international. Li industries de un branche
conclude cartelles trans li frontieras. Li banks del tot munde es alliat
per comun operationes.

 

Li ovreros ha sentit, que, in regard a lor patrones, ili have identic
interesses. Li formul "Laboreros de omni landes, unia vos" ha evocat ecó
in li classes de ovreros de omni landes.

 

Li rel-vias, li naves, queles fa possibil li relationes inter li homes,
deve devenir simil, caus necessitá. Li postal servicie ha esset fortiat
unificar se por conformar se secun li principies del union postal
universal.

 

Li vestes deveni partú li sam. Li guerre ne ha impedit li feminin modes
subir in li tot munde occidental presc li sam changes in li sam témpore.

 

Omnicos va uniformisar se.

 

Durant omni to li lingues, queles servi quam organes por li
civilisation, es tre divers, ili deveni constantmen plu mult. Li
conossenties del german, anglesi, hispan, francesi e italian ne sufice
plu a tis queles vole secuer li currente del tot civilisation modern.

 

Chascun nation, quamcunc micri it es, vole haver su propri lingue de
civilisation. Presc chascun nation de Europa ha obtenet autonomie e nu
li conossentie de duant lingues ne suffice por sequer li civilisation de
sol Europa.

 

Por experir li obstacules quel resulta de to, sufice transpassar un
lingual frontiera. Por tis, doctos o practicos, qui deve secuer li
currente del labor fat in li munde, li diversitá del lingues del
civilisation complica li labor in un maniere íntolerabil. Li aprension
de un scientie o tecnica deveni per chascun die plu laborosi, e li
necessitá aprender divers lingues e sempre plu divers, adjunte un cargo,
quel ne cessa far se plu e plu pesant.

 

In li sam gradu quam li civilisation deveni plu uniform, li lingues have
a expresser li sam coses per materialmen different, ma paralel procedes.
Li notiones ne varia con li paroles, queles expresse les. Li lingues de
Europa per to quo ili expresse, tende a devenir li fidel calcationes de
unaltru.

On save quel desfacilitás incontra un congress international pro li
diversitá del lingues, ne solmen si it acte se pri un congress de homes
con mediocri education, queles ne conosse foren lingues, ma anc li
congresses de homes alt educat, nam quam rarmen ili ha havet témpore
aprender parlar fluentmen un foren lingue! Li congresses de un partise,
quam li socialistic, quel confesse internationalisme, es fat tre
desfacil per li necessitá traducter omnicos in adminim du lingues, e li
delegates del micri landes deve esser electet solmen inter tal homes,
queles bon conosse un de ti lingues queles es usat in li congress. E it
es ínevitabil haver un comun lingue por far possibil un ver discussion.
Por ti scope on besona un lingue, quel es facilmen aprensibil e
applicabil e neutral. Solmen un lingue artificial responde a ti
conditiones.

 

Li practic necessitá haver un lingue international es evident. E proque
un tal lingue es possibil, it deve esser introductet tam bentost quam
possibil.

(Secun A. Meillet, professore de „Collège de France.“)

 

 

== 10.2 Explanations

 

==== 10.2.1 Syntax

 

Syntax is Occidental is for the most part very similar to English, with
some notable differences in places such as adjectives where they can
also be placed after the noun (general rule of thumb: the longer the
adjective, the more it feels right to place it after the noun). Some
other small differences exist, some of which are seen in the following
examples.

 

*Li monument es plazzat avan li palace.* -- The monument is located
(placed) before the palace.

*Li judico es nominat Cadi che li arabes.* -- The Arabs call the judge
Cadi (lit. the judge is named Cadi with the Arabs).

*Il pensat sovente pri li felici témpore del yunesse.* -- He often
thought about the happy times of (his) youth.

*Tui amore e tui felicie eleva se avan me quam un etern aurora.* -- Your
love and your happiness rise before me like eternal dawn. (Goethe.)

*Li númere de spectatores hat crescet extremmen per arivas ex vicin
districtes.* -- The number of spectators has grown greatly (extremely)
by arrivals from nearby districts.

*Yo ne save, esque yo ha fat bon.* -- I don't know if I've done right.

*Por scrir un bon lettre de amore, tu deve comensar sin saver quo tu
vole dir, e finir sin saver quo tu ha dit.* -- To write a good love
letter, you must begin without knowing what you want to say, and end
without knowing what you have said. (Rousseau.)

 

The regular word order in Occidental is: 1. Subject, 2. Predicate, 3.
Object: (1) *Goethe* (2) *ha scrit* (3) *Faust*. The same applies to
subordinate clauses.

 

Note some important differences that take place when the word order is
changed. Words such as *anc*, **solmen, **etc. quantify the word they
stand in front of.  The word **ne** also negates the word it stands in
front of.  Other examples: **tro**, and **tre**.

 

*Yo _ne_ va _prender_ Vor libre.* -- I won't take your book (but will
leave it lying).

*Ne _yo_ va prender Vor libre*. -- _I_ won't take your book (somebody
else will).

*Yo va prender ne _Vor_ libre.* -- I won't take your book (I will take
somebody else's).

*Vor _libre_ yo ne prende.* -- I'm not taking your book (I'm taking
something else of yours)

*Anc _yo_ ama Vos*. -- I love you too (other people like you)

*Yo ama anc _Vos_.* -- I love you took (I love many people, including
you)

*Solmen _ella_ ride.* -- Only she is laughing (nobody else is)

*Ella solmen _ride_.* -- She only laughs (she keeps laughing)

*Il tre regreta, que il have solmen poc euros.* -- He regrets having
just a few euros.

 

More on the rule of thumb for adjectives: they tend to stand before the
noun when they are short or refer to the character of the noun, and
after when longer, less directly related, part of a subordinate clause,
adding extra information, etc.

 

*Li delicat caviare russ.* -- delicate Russian caviar.

*Li lingue international.* -- The international language.

*Ti mann, clar in su pensas e pur in su intentiones.* -- That man, clear
in his thoughts and pure in his intentions.

*Su patre e su matre hat fat omni arangeamentes necessi por su viage.*
-- His/her father and mother had made all arrangements necessary for the
trip.

*Raporte aproximativ pri merces, important durant ti ci estive.* -- A
summary report on goods (that are) important during this summer.

 

In the first two sentences above it is somewhat a matter of taste
whether to say russ caviare or international lingue, though the word
international being long feels a bit more right after the noun. The next
three sentences however are much more clear cut
(*necessi-por-su-viage-arangeamentes* would be odd).

 

Dependent clauses: note the same word order.

 

*Il di, que il es malad.* -- He said that he is sick. (Il di + il es
malad)

*Il pensat, quo yo hat ja venit.* -- He thought that I had already come.
(Il pensat + yo hat ja venit)

*Ella questionat, pro quo yo es tam felici.* -- She asked why I was so
happy. (Ella questionat + yo es tam felici)

 

In sentences with questions (direct and indirect) that do not start with
question pronouns (where, why...) or adverbs are usually formed with the
general question word *esque* (lit. *is that*), but may be formed
without it.

 

*Esque Vu comprende me?* -- Do you understand me?

*Ha Vu comprendet me?* -- Have you understood me?

*Yo ne save, esque yo comprende Vos corect.* -- I don't know if I
understand you right.

*Pensa Vu o dormi?* -- Are you thinking or sleeping?

 

Other options for *esque* in subordinate clauses are *ca* and *si*. The
third setence could start with *Yo ne save, ca...* or *Yo ne save, si
...*.

 

The difference between forming questions, wishes (optative phrases) and
conditional sentences:

 

*Esque ella hat conosset su matre?* -- Did she know her mother?

*Mey ella har conosset su matre!* -- If (only) she had known her mother!

*Si ella vell har conosset su matre, ella vell...* -- If she had known
her mother, she would...

 

For the conditional you can add a *in ti casu* (in that case) if wished
to translate English *then* (if she had known her mother, *then* she
would have...), but *vell* on its own is always enough. Also note that
in the conditional, both parts of the sentence use *vell*. This is like
saying "if she *would have* known her mother she *would have*...",
because both parts are conditional. One does see the perfect past
starting off these types of sentences from time to time, however: "*Si
ella hat conosset su matre, ella vell har...*"

 

 

Where some languages use a preposition (especially *a*) before the
subject of a verb and others don't, Occidental prefers to not use them.
Rule of thumb: if in doubt, try going without a preposition if the
meaning is still clear.

The same goes for reflexive verbs (verbs using **se**). English uses
them infrequently but still does in some places such as "I'm going to
find *myself* something to eat" which would be written "Yo va trovar
alquó a manjar" and not "Yo va trovar **me** alquó a manjar".

 

*Yo mersia Vos (not a Vos)*. -- I thank you.

*Ples auxiliar li (not a li) povri mann.* -- Please help the poor man.

*Il menaciat su ínamicos.* -- He threatened his enemies.

*Yo memora li cose tre bon.* -- I remember it ("the thing") very well.

*Il prepara por un viage.* -- He is preparing for a voyage.

*To il solmen imagina.* -- He just imagines it.

*Yo es conscient pri to.* -- I'm aware of that.

*Yo tre joya vider Vos.* -- I'm very happy to see you.

*Yo senti dolore; yo regreta.* -- I'm sorry; I regret that...

*Yo repente.* -- I'm sorry ("I repent that...")

*Yo senti calore; yo cale.* -- I'm hot.

*Yo senti frigore; yo frige.* -- I'm cold.

*Yo senti fame / sete.* -- I'm hungry / thirsty.

*Yo successat far it.* -- I was able to do it.

*On dansat e ludet.* -- We/they/one danced and played.

 

Note: The above phrases are ones that in the original German are
rendered with reflexive verbs in German; fortunately, English does not
use them nearly as much.
