== Occidental Course in 10 Lessons (lessons 3-4)

 +

[[displaycontent]]
== Triesim letion

 

=== 3.1 Texte

 

==== 3.1.1 Li creation

 

In li Bible sta scrit, que Deo ha **creat **li munde.

Pro to il es nominat li **creator **del munde.

Li **creation **durat six dies.

Noi ne have **creatori **qualitás, solmen Deo es vermen *creativ*.

Quo il ha creat? Nos e omni altri *creaturas*.

 

[cols=",,,",]
|===
|*triesim * + |third  + |*crear * + |create  +
|*Deo * + |God  + |*nominar * + |name  +
|*munde * + |world  + |*durar * + |to last  +
|*qualitá * + |quality  + |*vermen * + |truly  +
|*altri* |other |*creatori* |"creator-y"
|===

 

 

==== 3.1.2 Un brilliant carriera

 

Mi fratre have un amico, un ingeniero, qui ha fat un brilliant carriera.
Ja quam yun studente su aspirationes evocat atention. Pos obligatori
teoretic studies in un technical institute e practic preparatori labores
in un micri fabrica, in quel il laborat quam reparator de electric
motores e transformatores, il recivet un transitori ocupation quam
supervisor del machines in un grand industrial interprense. Mersí a su
intensiv labor e su extraordinari organisatori talentes il avansat
gradualmen, de position a position, e nu il es executiv director de un
association de industries in li sam branche.

 

Su precessores esset in oposition a innovationes, ma quam successor de
ti conservativ administratores il devet interprender mult reformationes
e un total reorganisation del administration. Li production e vendition
del productes e fabricates crescet enorm in comparation a to, quo ili
esset ante il. Il ha prendet parte in mult negociationes con extran
states, e li resultate ha esset plu e plu extensiv, comercial
transactiones de exportationes e concessiones in exotic landes.

 

Difamatori lingues di, que il es un poc imperatori, ma to es
exageration. Quande il ha decidet un afere, il es firm in su decision,
ne tolera contradition e intervention, e pro to il have success in su
interprenses. Tal qualificationes es anc absolutmen necessi a decisiv
por un mann in su position.

 

Il es inventor de mult patentat aparates, queles es ancor in su exclusiv
possession. Quam possessor de grand capitales, il ha fat mult donationes
in favor a cultural institutiones, e pro to il have li reputation de un
grand donator e favorisator del scienties e artes.

 

[cols=",,,",]
|===
|*fratre*  + |brother  + |*ja*  + |already  +

|*evocar*  + |evoke  + |*transitori*  + |transitory  +

|*gradualmen*  + |gradually  + |*preceder*  + |precede  +

|*innovar*  + |innovate  + |*succeder*  + |succeed (follow)  +

|*vendir*  + |sell  + |*negociar*  + |negotiate  +

|*extran*  + |outside, abroad  + |*extender*  + |extend  +

|*transacter*  + |transact  + |*conceder*  + |concede  +

|*difamar*  + |speak ill of (cf. defamation)  + |*imperar*  + |order
(cf. imperative)  +

|*exagerar* |exaggerate |*quande* |when

|*intervenir* |intervene (lit. "between-come") |*anc* |also

|*necessi* |necessary |*donar* |give, donate
|===

 

 

==== 3.1.3 Li eterni problemas

 

It existe témpores, quande li filosofic speculation sembla haltar in
total o partial resignation ante li grand problemas del vive, quande ne
solmen definitiv ma anc provisori responses al eterni questiones sembla
van. It concentra se a examination e inregistration de ti resultates,
queles li exploratores e laboratores del special scienties presenta. It
es periodes, quande li homan pensa fa quasi un sorte de guerre de
position contra li eterni problemas, un guerre de position, quel postula
mult devot perlaboration de detallies e penetrativ analise.

 

Ma it existe anc témpores, quande li pensa abandona su timid, defensiv
position, marcha adavan e fa un general atacca. It es tal témpores, pri
queles Hegel ha dit, que "li universal spíritu fa un choc adavan." Con
egal justification on posse nominar les témpores de productiv erras. Tal
periodes seque successiv un pos altri, in ritmic fluctuation quam
sómmites e valleyes de undes.

 

Pos li potent flut del Renascentie, quel in fin manifestat se in li
grand sistemas, sequet li rationalisme del enciclopedistes e lor
imitatores. Ti rationalisme havet su culmination e su coronation, ma anc
su contra-evolution in Kant, li titane del filosofie. Pos il sequet li
romantica, con nov gigantic constructiones de sistemas.

 

E denove, pos li romantica, li filosofie devet retirar a su positiones.
Li positivisme detronat li filosofie in favor al special scienties. Li
materialisme devenit li successor de ti sublim, genuin idealistic
spíritu, quel, malgré omni fantastic misprenses, esset li directiv
factor del romantica. Li special scienties fa nov e nov decovritiones,
ma nor spiritual horizonte deveni plu strett.

 

E nu, esque li signes de nor propri témpore ne da nos indicationes pri
un nov era de filosofic speculation, un nov romantica e idealisme, támen
con plu critic reflection quam li antiqui? Li munde fórsan ne es ancor
tam senil, quam li profetes de fatiga vole far nos creder.

 

[cols=",,,,,",]
|===
|*eterni*  |eternal  |*témpore*  |time  |*coronar* |to crown
|*semblar*  |to seem  |*van*  |in vain  |*evoluer* |evolve
|*ti*  |this, that  |*explorar*  |explore  |*retirar* |retire
|*pensa*  |thought  |*guerre*  |war  |*detronar* |dethrone
|*devot*  |devoted  |*penetrar*  |penetrate  |*devenir* |become
|*abandonar*  |abandon  |*defender*  |defend  |*malgré* |despite
|*adavan*  |forwards  |*spíritu*  |spirit  |*omni* |all
|*choc*  |shock  |*justificar*  |justify  |*misprense* |misunderstanding
|*les* |them |*erra* |error |*nor* |our
|*sequer* |follow |*pos* |after |*strett* |narrow
|*fluctuar* |fluctuate |*sómmite* |summit |*propri* |own (one's own)
|*unde* |wave |*Renascentie* |Renaissance |*indicar* |indicate
|*imitar* |imitate |*culminar* |culminate |*támen* |however
|*fórsan* |perhaps |*senil* |senile |*fatiga* |fatigue
|  |  |*creder* |believe |  | 
|===

 

Note: **omni **before a singular means *each *(same as *chascun*), while
before a plural it means *all*.

 

 

==== 3.1.4 Anecdotes

 

On questionat li filosof Aristippos de Kyrene, per quo li filosofos
distinte se del altri homes. Il respondet: "Si omni leges vell esser
abrogat, solmen li filosofos vell viver quam antey."

 

Alqui objectet que on frequent incontra li filosofos avan li portas del
riches. Aristippos replicat: "Sam quam li medicos avan li portas del
malades. Esque pro to li malades es plu reputat quam li medicos?"

 

"Moné," il declarat, "yo prende del riches ne pro que yo besona it, ma
por que ili mey saver in quel maniere ili posse investir it."

 

[cols=",,,",]
|===
|*per quo*  |by what  |*distinter*  |distinguish 
|*lege*  |law  |*abrogar*  |abrogate, repeal 
|*viver*  |to live  |*antey*  |before 
|*alqui*  |someone  |*objecter*  |to object 
|*avan*  |before  |*porta*  |door 
|*replicar*  |reply  |*sam quam * |same as 
|*medico*  |doctor  |*malad*  |sick 
|*pro to*  |that's why  |*plu reputat*  |more reputed 
|*moné* |money |*besonar* |to need
|*in quel maniere* |in which way |  | 
|===

 

 

=== 3.2 Explanations

 

We have just seen a large number of expressive international words that
end with the 5

 

==== 3.2.1 suffixes -ion, -or, -ori, -iv, ura.

 

Note that these words in Occidental are regularly derived from verbs.

 

The words with *-ion, or, -ori, -iv* and *-ura* are created with the
perfect stem of the verb. But dictionaries only give the infinitive of a
verb. How do you find the perfect stem? This is where we come to

 

==== 3.2.2 de Wahl's Rule.

 

First remove the *-r* from a verb, or *-er* for an *-er* verb. What is
at the end?

 

{empty}1. If it's a vowel, then add a t:

 

[cols=",,",]
|===
|*Infinitive*  |*Perfect stem * |*Derived word *
|*decora/r*, decorate  |*decorat-*  |*decoration* 
|*defini/r*, define  |*definit-*  |*definition* 
|*le/er,* read  |*let-*  |*letion*, reading/lesson 
|*devo/er*, to devote  |*devot-*  |*devotion* 
|*institu/er*, to institute |*institut-*  |*institution* 
|*extract/er*, to extract  |*extract-*  |*extraction* 
|*distint/er*, to distinguish |*distint-* |*distintion*, distinction
|===

 

Note: as in English, Occidental sometimes has two groupings of verbs
with nearly the same meaning where the more Latin-like one has a more
formal or heavy character. To derive *extraction* above the
verb *extracter* is used, but the verb **extraer**also exists
(lit. *ex-traer*, to pull out), which above would lead
to *extra-er* --> *extrat* --> *extration*. This gives them a slightly
nuanced meaning: an *extraction*, derived from *extracter* (to extract),
is only an *extraction*. But an *extration*, derived from *extraer *(to
pull out), is both a pulling out and an extraction.

 

Similarly, the word reader (*letor*, from *le/er* --> *let* --> *letor*)
has a 'hidden' companion in the form of *lecter* that can be seen from
the word *lector* (same meaning in Occidental as in English) that one
can see derived as *lecter* --> *lect*- --> *lector*. The
word *letion* above can also be written *lection*, which carries a more
formal or pompous meaning. This freedom given to the user to explore the
language oneself is a powerful tool for adding nuance in writing.

 

{empty}2. If it's a *d* or an *r*, then it becomes *s*:

 

[cols=",,",]
|===
|*Infinitive*  |*Perfect stem * |*Derived word *
|*explod/er*, to explode |*explos-*  |*explosion* 
|*adher/er*, to adhere  |*adhes-*  |*adhesion* 
|*decid/er*, to decide  |*decis-*  |*decision* 
|===

 

{empty}3. If it's a consonant, then you already have the perfect stem.

 

[cols=",,",]
|===
|*Infinitive*  |*Perfect stem*  |*Derived word* 
|*construct/er*, to construct |*construct-*  |*construction* 
|*express/er*, to express  |*express-*  |*expression* 
|*opin/er*, to opine  |*opin-*  |*opinion* 
|===

 

Five verbs are exceptions to the above and must be learned separately.

 

[cols=",,",]
|===
|*Infinitive*  |*Perfect stem*  |*Derived example* 
|*ceder*, to cede  |*cess-*  |*recession* 
|*seder*, to sit  |*sess-*  |*session* 
|*tener*, to hold  |*tent-*  |*retention* 
|*venir*, to come  |*vent-*  |*intervention* 
|*verter*, to wind  |*vers-*  |*version* 
|===

 

Note: the original de Wahl's Rule included the exception *mover* (to
move) --> *mot-*, from which is derived *motion*. The Occidental
community noted however that *motion* (plus *emotion*)
and *movement* are semantically different and that using two
verbs *moer* (to move, to budge) and *mover* (to move) would allow
greater precision while doing away with an irregularity. Thus, the word
motion is regularly derived from *mo/er* --> *mot-* --> *motion*.

 

==== 3.2.3 Meaning of the suffixes

 

*-ion*

The action, result or location of a verb.

 

*fabrication*, from *fabricar* (to fabricate)

*administration*, from *administrar* (to administrate)

*expedition*, from *expedir* (to send, to expedite)

 

*-or*

The acting person, thing or factor of a verb.

 

*decorator*, from *decorar* (to decorate)

*fabricator*, from *fabricar*

*administrator*, from *administrar*

*expeditor*, from *expedir*

*compressor*, from *compresser* (to compress)

 

*-ori*

* *Adjective derived from -or above, similar to English -ory. Refers to
something that is dedicated to or working as:

 

*un obligatori servicie* = an obligatory service (from *obligar*, to
obligate)

*un organisatori talent* = a talent for organization (lit. an
organisor-y talent; Occidental allows greater freedom than English with
such words)

*un preparatori mesura* = a preparatory measure (from *preparar*, to
prepare)

*un transitori stadie* = a transitory stage (from transir, to cross)

*contraditori propositiones* = contradictory propositions
(from *contradir*, to contradict)

*un ilusori pensa* = an illusory thought (from *iluder*, to feint or
delude)

*scritori crampe* = writer's cramp (i.e. the cramp of a *scritor*)

*defensori discurse* = lit. "defensive discourse" (e.g. the speech on
the defendant's side, from *defender*, to defend)

 

*-iv*

 

English -ive, forms adjectives that denote an active ability:

 

*un decorativ vase* = a decorative vase (*un decoratori vase* would be a
vase intended for decoration, but uncertain as to whether it is actually
decorative or not)

*un obligativ promesse* = a promise that obligates (*obligatori
promesse* = an obligatory promise)

*un explicativ exemple* = an example that explains something
(**explicar **= explain)

*un consolativ response* = a response that brings consolation (*un
consolatori response* = a response given as consolation) (*consolar* =
console)

*un negativ resultate* = a negative result (**negar **= deny)

*un instructiv articul* = an instructive article (**instructer **=
instruct)

*un decisiv parol* = a decisive word (*decider* = decide)

 

*-ura*

 

Similar to English -ure. Forms verbal nouns denoting a concrete,
realized action or its result.

 

**garnitura **= garnish (the English noun garnish, from *garnir*, to
garnish)

**scritura **= writing, scripture (from **scrir **= to write)

**politura **= polish (the noun polish, from **polir **= to polish)

 

*Note 1.* The perfect stem plus an -e (to indicate a noun) is also used
to form showing the result of the action of a verb.

 

**tribute **= tribute (from *tribuer*)

**flute **= flood (from *fluer*)

**scrite **= writing (also note *manuscrite*, a manuscript,
from *manu* (hand) + *scrite*)

**extracte **= extract, from *extracter *(*extrate* for a slightly
different nuance - see note above)

*miscomprense* = misunderstanding (from **miscomprender **=
misunderstand)

 

The -e is technically optional but is used for clarity; it may be
removed for euphonic purposes (usage poetry, to translate colloquial or
informal speech, etc.).

 

The perfect stem on its own is also used as an adjective:

 

*un apert fenestre* = an open window (from aperter = open) (note the
difference between this and *un apertet fenestre* = an opened window)

**un pervers(i) opinio**n = a perverse opinion (from *perverter*, to
pervert) Here again there is a difference between *perversi *(perverse)
and *pervertet *(perverted).

*un devot amico* = a devoted friend (from **devoer **= devote). In cases
where no obvious difference exists between the perfect stem (*devot*)
and the past tense (*devoet*), the two tend to be used interchangeably.
One could still imagine however situations where choosing one or the
other is necessary.

 

Note: -i, like -e above, is affixed to show that the word is an
adjective. -i is also optional, and tends to be used most often when
euphony demands it (e.g. the word *micri*, small, could not be
pronounced without it).

 

*Note 2*: The perfect stem is used when deriving (forming) words, but
not for verb conjugation. Technically words above such
as *apert*, **pervers(i) **etc. can be learned and thought of as
separate entities but knowing how they are derived from verbs gives the
user of the language a much greater range of options when speaking and
leads to much less looking up of words in the dictionary.

 

 

 

 

 

== 4 Quadresim letion

===  

=== 4.1 Texte

===  

==== 4.1.1 Li misterie del cratere in Sall

 

In fine del septembre mill nin cent duant sett (1927) li conosset
geofisico Professor Wegener (de Graz in Austria) visitat un ja de long
conosset, ma per su orígine absolutmen misteriosi cratere in Sall sur li
insul Oesel (Saaremaa), quel apartene al Republica de Estonia. Il esset
in un societé de professores Kraus e Meyer del universitá in Riga e fat
explorationes pri ti fenomen del natura.

 

In to omni expertes esset unanim till nu, que ci ne acte se pri un
extint vulcan, quam on pensa in circules de laicos. Li max probabil
opinion esset ti, que li cratere es un funel de ruition. Nu professor
Wegener expresset un nov surprisant interpretation del orígine de ti
strangi formation. Il pensa que on have ci un funel de penetration de un
grandissim meteorite, simil al funeles de grenades, queles noi conosse
desde li guerre mundan. Li cratere de Sall have un diametre de du cent
quinant (250) e un profundore de deciquin (15) metres. It sembla esser
un diminuet simil formation quam li famosi Arizona-crater in Nord
America, quel advere have du mill (2000) metres in diametre.

 

Ma quo es significativ – per forationes on ja ha constatat in quar cent
(400) metres sub li solea del cratere un enorm meteorite de circa mill
du cent (1200) metres in diametre, it es, un córpore de dimensiones de
un micri satellite. Wegener aprecia li grandore del meteorite, quel ha
productet li cratere de Sall, ye circa cent til cent quinant (100 til
150) metres in diametre, e supposi que it deve trovar se in circa
quinant till settant quin (50 til 75) metres de profundore. Adplu it es
remarcabil, que in li vicinitá del principal cratere es situat pluri
simil, ma mult plu micri, funeles, probabilmen causat per partes, queles
ha separat se durant li cadida, quo es sovente observat che li cadidas
de meteorites.

 

Si li suposition de prof. Wegener es rect, tande li cratere in Sall es
un unic monument de natura in Europa, e li duesim sur li tot globe de
terra.

 

[cols=",,,",]
|===
|*quadresim*  |fourth  |*apertener*  |to belong 
|*unanim*  |unanimous  |*acter*  |to act 
|*acter se pri*  |to be about  |*extinter*  |to extinguish 
|*laico*  |layperson (i.e. not a specialist)  |*circul*  |circle 
|*max*  |most  |*probabil*  |probable 
|*funel*  |funnel  |*ruir*  |collapse 
|*orígine*  |origin  |*strangi*  |strange 
|*penetrar*  |to penetrate  |*simil*  |similar 
|*grandissim* |huge |*conosser* |to know
|*profundore* |depth |*advere* |indeed
|*forar* |to bore / drill |*solea* |sole, bottom
|*córpore* |body |*grandore* |size (cf. grandeur)
|*producter* |produce |*suposir* |suppose
|*adplu* |furthermore |*vicinitá* |vicinity
|*situat* |situated, located |*pluri* |several
|*causar* |to cause |*separar* |to separate
|*cader* |to fall |*sovente* |often
|*rect* |right, correct |*tande* |then
|*unic* |unique |  | 
|===

 

 

==== 4.1.2 Numbers

 

Li cardinal numerales, queles responde al question: *quant?* es:

 

1 un

2 du

3 tri

4 quar

5 quin

6 six

7 sett

8 ott

9 nin

10 deci

 

11 to 19 are formed by **deci **+ the number:

11 deciun

12 decidu

13 decitri

14 deciquar

15 deciquin

16 decisix

17 decisett

18 deciott

19 decinin

 

Tens are formed with the suffix **-ant **after the number:

 

20 duant

30 triant

40 quarant

50 quinant

60 sixant

70 settant

80 ottant

90 ninant

 

Larger and more complex numbers:

 

100 cent

200 du cent

300 tri cent

400 quar cent

500 quin cent

600 six cent

700 sett cent

800 ott cent

900 nin cent

1000 mil

 

31 triant un

75 settant quin

1 000 000 un million

1 000 000 000 un milliard

 

4711 quar mill sett cent undeci

 

Per adjuntion del suffix -**esim **noi have li ordinal numerales,
respondent al question *quantesim*:

 

*quantesim*:

{empty}1. unesim

{empty}2. duesim

{empty}3. triesim

{empty}4. quadresim

{empty}5. quinesim

 

{empty}10. decesim

{empty}30. triantesim

{empty}55. quinantquinesim

{empty}100. centesim

{empty}1000. milesim

 

Note: *decesim *(tenth) is written as **decesim **and
not **deciesim **because -i in **deci **is the adjectival ending we
encountered above (the root itself is dec-). This is another example of
an adjective that requires the -i ending on its own as
otherwise **dec **would be pronounced *dek*.

 

Note 2: -esim also gives rise to internationally-recognized words such
as ínfinitesim (an infinitessimal part) and infinitesimal. In Occidental
these words are regularly derived from common verbs: ín + fini-r (to
finish) + t + esim + al = *ínfinitesimal*.

 

Similarly, sometimes the **-ant **is written **-anti **for euphonic
purposes. But because -**ant **on its own is easy enough to pronounce
the -**anti **form is much rarer.

 

Per adjuntion del sufix -*plic *(*-uplic* pos consonantes) (del
verbe **plicar **= anglesi "fold") noi recive
li **multiplicativ **numerales, queles responde al
question: *quantuplic*?

 

unuplic (simplic)

duplic

triplic

duantquinuplic

decuplic

duantuplic

qua**d**ruplic

centuplic

 

From these words are also derived many known
words: *duplicitá *(duplicity), *triplicar *(to triplicate), etc. Also
note the d in *quadr* to form recognizable terms such
as *quadratic*, *quadrennial*, etc.

 

To summarize: *quant* asks how many, **quantesim **asks which place (the
"howmany-ith"), and **quantuplic **how many times (the "howmany-uple").

 

Existe anc **colectiv **numerales, queles expresse un colection o un
aproximativ númere:

 

unité

pare (a pair)

triene

quarene

quinene

sixene

decene

deciduene (dozen)

duantene

centene

milene

etc.

 

The above numbers are used collectively or approximatively in phrases
such as *un centene de soldates*: a hundred soldiers. English uses
collective nouns rarely (a group of people, a pair of ducks,) while
Occidental allows it with any number with the *-ene* ending.

 

Li fractiones es:

 

1/1 : un tot

1/2: un demí

1/3 : un ters

1/4 : un quart

1/5 : un quinesim

1/100 : un centesim

 

0,1 : null e un decesim

2,3 : du tot e tri decesim (du comma tri)

1 1/2 : un e demí

2 3/4 : du e tri quart

2 x 2 = 4 : du vez du es quar

10 / 2 = 5 : deci sur du es quin

 

De 1/5 li fractiones es simil al ordinales.

 

Forms such as *un triesim* for 1/3 are of course permitted.

 

[cols=",,,",]
|===
|*quant*  |how many  |*composir*  |to compose 
|*in vice de / vice*  |instead of  |*adjunter*  |add to 
|*quantesim*  |which place  |*reciver*  |receive 
|*multiplicar*  |multiply  |*colecter*  |to collect 
|*unité* |unit |*pare* |pair
|===

 

 

 

==== 4.1.3 Li témpore e su division

 

Quel hora es? Quel es li témpore?

 

12:00 a decidu horas (precis), it es midí

12:45 a un hora ante un quart

1:00 a un hora (precis)

1:25 a un hora e duantquin

 

Sixant secundes es un minute.

Sixant minutes es un hor.

Duant quar hores es un die.

Sett dies constitue un semane.

In un mensu es circa quar semanes.

Decidu mensus es un annu.

Cent annus es nominat un secul, mill annus un millennie.

Li sett dies del semane es: soledí, lunedí, mardí, jovedí, mercurdí,
saturdí.

Li decidu mensus es: januar, februar, marte, april, may, junio, julí,
august, septembre, octobre, novembre e decembre.

 

Note 1: The word **hora **refers to the hour of the day. The
word **hor **refers to an hour of time.

Note 2: The word **clocca **is an alternative to the word *hora*. It was
replaced by *hora* during the 1940s but seems to have remained popular
and has a bit of a slangy feel. *Ye clocca du = a du horas*.

Note 3: While we are on the subject, the same has happened with the
word *flicca *(girl, from Swedish flicka), which was changed
to **puella **a long time ago. Now **flicca **has a similar feel to
English gal or chick.

 

Triant dies hav' septembre,

April, junio, novembre,

Triant un have altris tot,

Februar sol have duant ott;

Except in annus intercalar

Duant nin have februar.

 

In li verne plantes cresce in li renascet natura.

In estive flores vive e li dies es calid.

In autune flores mori e li fructes es matur.

In hiverne veni nive e li dies es frigid.

 

[cols=",,,",]
|===
|*quel*  |which  |*midí*  |midday 

|*die*  |day  |*semane*  |week 

|*mensu*  |month  |*annu*  |year 

|*secul*  |century  |*millennie*  |millennium 

|*verne*  |spring  |*estive*  |summer 

|*autune*  |autumn  |*hiverne*  |winter 

|*renascer*  |be reborn (cf. renaissance, **renascentie **in
Occidental)  |*flore*  |flower 

|*nive*  |snow  |*calid*  |hot 
|===

 

 

==== 4.1.4 Aforismes

 

In null altri ocasion on menti tant quam pos un chasse, durant un guerre
e ante un election. (Bismarck.)

 

Si li veritá vell esser dat me con li condition, que yo deve celar it in
me e ne dar it de me – yo vell refusar it. (Seneca.)

 

It es just egal, si on interprende liberar homes queles have null firm
conceptiones ex lor erras, quam si on vole expussar un vagabunde qui
have null firm dom ex su hem. (Locke.)

 

Quo noi nómina accidentie, es li asil del ignorantie. (Spinoza.)

 

[cols=",,,",]
|===
|*null*  |no (none)  |*veritá*  |truth 
|*interprender*  |undertake  |*expussar*  |chase out 
|*ocasion * |occasion, event |*accidentie*  |accidence, chance 
|*chasse*  |hunt  |*celar*  |to hide 
|*liberar*  |to free, liberate  |*ignorantie*  |ignorance 
|*mentir*  |to lie (not tell the truth)  |*refusar*  |to refuse 
|===

 

 

=== 4.2 Explanation

 

Knowing how to derive words with prefixes and suffixes is of great
importance in the understanding of international words, because being
able to do this allows you to form a large number of
internationally-understood words on your own from a single root. None of
the prefixes or suffixes in Occidental, seemingly so large in number,
were created from scratch, but already exist in many internationally
known foreign words. The difference in that in Occidental they are not
simply imported loanwords, and have been given a more precise sense and
have been made for more general and meaningful use.

 

Let's take the root **centre **as an example (centre in English as
well). From this word we already recognize words derived from
it: *central, centrale, centralisme, centralisar, centralisation,
centralisator, decentralisar, decentralisation, concentrar,
concentration, excentre, excentric, excentricitá, subcentral*, etc. By
learning Occidental's derivation one gains an understanding for how they
are made up.

 

We are now going to look at prepositions, which in Occidental are not
simply standalone particles but also used to form words.

 

==== 4.2.1 Prepositiones

 

[cols=",,,",]
|===
|*a, ad * |to  |*intra* |between

|*along * |along  |*malgré* |despite

|*alor * |then  |*per* |by, through

|*ante * |before  |*por* |for

|*apu * |by, next to |*pos* |after

|*avan * |before  |*preter* |past

|*caus * |because of  |*pri* |regarding

|*che * |at, with  |*pro* |due to

|*circum* |around |*secun* |according to

|*con* |with |*sin* |without

|*contra* |against |*sub* |under

|*de* |of, from |*súper* |over

|*desde* |since |*sur* |on

|*detra* |behind |*til* |until

|*durant(e)* |during |*tra* |through

|*ex* |out |*trans* |across

|*except* |except |*ultra* |beyond

|*extra* |besides |*vers* |towards

|*in* |in |*vice* |instead

|*infra* |below |*ye* |preposition used when no other apt preposition
comes to mind
|===

 

 

Let's take a look at a few from all of these.

 

==== *a*

Of. Has many uses:

 

*Il dat li flores a su amata* = He gave the flowers to his girlfriend.

*Un epistul a nor societé* = A letter to our society (note: society as
in a group or company).

*Yo viagea a Berlin* = I travel to Berlin.

**Li vapornave ea a Lisbon **= The steamboat goes to Lisbon.

**Clar a departer **= Ready (clear) to depart.

**Un error a regrettar **= A regretful error. (lit. an error to regret)

 

 

==== *ante*

Means before in terms of time and place (**avan **only refers to place).

 

*Ante Cristo* = Before Christ

*Avan li dom* = Before the house

 

 

==== caus

Because of. The reason for something goes right after *caus*, which is
an abbreviation of the longer *in cause de*.

 

**Caus vor intervention **= Because of your intervention.

**Caus li politic evenimentes **= Because of the political events.

 

 

==== con

With.

 

**Li filio ea con su patre **= The son goes with his father.

*Ella stat con lácrimes in li ocules*. = She stood with tears in her
eyes. (Note: the phrasing "the hands", "the eyes" to refer to body parts
is more common internationally than the English his/her/their. But
English also uses it sparingly such as in "look me in the eyes" (not
"look me in my eyes")).

 

 

==== de

*De* has a wide usage, and oftentimes other prepositions can be used in
its place.

 

*Li dom de mi patre* = The house of my father, my father's house

*Li dramas de Schiller* = Schiller's dramas

*Ti libre es scrit de un fémina* = This book is written by a woman
(**per **fits here as well)

**Un senior de Berlin **= A gentleman from Berlin (*ex* fits here as
well)

*Li max grand de omnis* = The largest of all (**ex **potentially fits
here as well)

*Un vase de aure* = A vase of gold

 

 

==== *desde*

Since, for.

 

**Desde du annus **= For two years.

 

 

==== ex

Out (of), from.

 

*Il venit ex su chambre* = He came out ofhis room.

*Yo trinca ex li glass*. = I drinkt out of the glass.

*Traductet ex german in Occidental*. = Translated from German into
Occidental.

 

 

==== per

By, through, with

 

*Il defendet se per un gladie* = He defended himself with a sword.

**Il salvat se per svimmar **= He saved himself by swimming.

**Li moné ha esset furtet per un ínconosset hom **= The money has been
stolen by an unknown person.

 

 

*por*

 

**Un libre por omnes e por nequi **= A book for all and for nobody.

**On manja por viver, on ne vive por manjar **= You eat to live, you
don't live to eat.

 

 

==== pri

 

**Noi parlat pri politica **= We talked about politics.

*Yo mersía pro Vor auxilie* = I thank (you) for your help.

 

 

==== *til*

 

*Yo laborat til decidu horas.* = I worked until twelve o'clock.

**Til li extrem fine del munde **= Until the very end of the world

 

 

==== tra

 

**Yo videt le tra li fenestre **= I saw him through the window.

 

 

==== trans

 

**Lindberg volat trans li Atlantic Ocean **= Lindberg flew across the
Atlantic Ocean.

 

 

==== vers

 

**Li avie volat vers li sole **= The bird flew towards the sun.

 

 

 

These prepositions are also used to form other words.

 

**aportar **= to bring (*a* + *portar*, to carry)

*antediluvian* = antediluvian (**ante **+ *diluvie*, a flood)

*avanposto* = outpost (*avan* + *posto*)

*circumstantie* = circumstance (**circum **+ **stantie **from **star **=
to stand)

**constellation **= constellation (**con **+ **stelle **= star)

**contravention **= contravention (**contra **+ **vention **= coming,
from *venir*)

**deportar **= deport (**de **+ *portar*, to carry)

**exportar **= export (**ex **+ *portar*, to carry)

**ex-imperator **= former emperor

**extraordinari **= extraordinary (**extra **+ *ordinari*)

**inclusiv **= inclusive (**in **+ *cluder*, to close or shut)

**intervalle **= interval (**inter **+ *valle*, a bulwark or embankment
(related to English wall))

**preterpassant **= passing by (**preter **+ *passar*, to pass)

*subordination* = subordination (**sub **+ *ordinar*, to order)

**traducter **= to translate or render (**tra **+ *ducter*, to lead)

**transatlantic **= transatlantic

*vice-presidente* = vice president (**vice **+ *presidente*)

 

 

==== 4.2.2 Prefixes

 

The following prefixes are only used in compound words.

 

==== *bei-*

Related by marriage. **belfratre **= brother-in-law (**fratre **=
brother)

 

 

*des*- (usually *de*- before consonants):

 

{empty}1. Before nouns: nullation or opposing meaning, un-:

 

**desagreabil **= disagreeable (**agreabil **= agreeable, friendly)

**deshonor **= dishonour

**desilusion **= disillusion

 

{empty}2. On verbs: loss of something:

 

**desarmar **= disarm (armar = to arm)

 

 

 

==== *dis-*

Separation, moving away:

 

**dismembrar **= dismember (membre = limb)

**distracter **= distract (**tracter **or **traer **= to pull)

 

 

==== ín-

Opposite meaning, in/un/etc.:

 

**ínoficial **= unofficial

**ínclar **= unclear

**íncurabil **= uncurable

**ínpossibil **= impossible

 

*Note 1:* other more internationally-recognized forms such
as *impossibil *(vs. *ínpossibil*), *irregular *(vs. *ínregular*) etc.
were often used in Occidental but the user base showed a preference for
a regular *ín-* and the other forms have become rarer.

 

*Note 2:* not to be confused with the unstressed preposition *in-*,
similar to the one in English in words such as *inclusiv*, *inspecter*.

 

 

 

==== mis-

Wrong, improper, mis-:

 

**miscomprender **= misunderstand (**comprender **= to understand)

*misparlar* = misspeak (**parlar **= to speak)

 

 

*pre-*

Before, pre-:

 

**prematur **= premature (*matur* = mature)

**prevenir **= forestall, preempt, prevent (**venir **= to come)

**prehistoric **= prehistoric

 

 

==== pro-

Ahead, forth

 

**producter **= to produce (**ducter **= to lead)

**projecter **= to project (**jecter **= to throw)

 

 

==== re-

Again, re-:

 

**reaction **= reaction

**renascentie **= renaissance, rebirth (**nascentie **= birth)

**revider **= see again (**vider **= to see)

 

 

==== Which form to use?

 

When Occidental was first announced in 1922, Edgar de Wahl proposed a
number of standalone and derived words that he believed to be equally
valid, leaving the decision between them to the community to see which
form it preferred. This process of ironing out took place over the next
25 years, at a very gradual pace as all changes in the end were very
minor. Some examples of theoretically equally valid forms are the
following:

 

(Etymologic -- doubled consonant -- modern single consonant form)

* adportar -- apportar -- *aportar *(to bring, from ad + portar, lit. to
'to pull')
* adnexion -- annexion -- *anexion *(to annex, from ad + nexer, lit. to
'to tie')
* adtractiv -- attractiv -- *atractiv *(to attract, from ad + tracter,
lit. to 'to pull')
* obpression -- oppression -- *opression *(to oppress, from ob +
presser, lit. to 'against press')
* subposition -- supposition -- *suposition *(to suppose, from sub +
poser, lit. to 'under place')

 

The form on the left was rarely if ever used, due to 1) the
uninternational appearance and 2) the possibility of appearing to have a
different meaning. Subposition for example simply looks like "under
position" and does not give the sense of supposition.

 

The second form was used for a time, but eventually the community
settled on the form on the right for simplicity, with doubled consonants
used in the cases mentioned in the beginning of the book (ss to maintain
the [s] sound in all cases, ch for [sh], etc.).

 

 

 

 
