== Occidental Course in 10 Lessons (lessons 1-2)

 +

[[displaycontent]]
== Occidental Course in 10 Lessons (English translation)

 

Mag. phil. A.Z. Ramstedt, Helsinki

 

Occidental-Buró Berlin

 

'''''

 

 

== 1 Unesim letion

 

=== 1.1 Texte

 

==== 1.1.1 Un international congress

====  

Noi have un grand international congress in li cité. Li nationes de
Europa es representat per eminent cultural persones. Li centre del
congress es in li palace del parlament. Elegant modern automobiles sta
ante li portas e sur li stradas e plazzas. Li fassades es decorat per li
national flaggas. Li flaggas del nordic landes have li cruce quam
symbol. On vide delegationes de divers partes de Europa, de nord e sud,
de ost e west. Un deputation visita li presidente del state in li
grandiosi residentie contra li ópera. Special correspondentes fa
observationes e scri articules por li redactiones de grand jurnales e
telegrafa al burós de information.

 

In li grand sala del palace es li general convent. In li micri chambres
li special comissiones e comités have secret conferenties. Nu li
official programma comensa. Li

borgomastre del cité saluta li congressantes. On electe un presidente.
Du secretarios scri li protocolles. Un delegat del central states
presenta un proposition pri li organisation del international trafic per
aeroplanes. Li orator parla con fascinant eloquentie e li auditoria
escuta con interesse e applaude con entusiasme. Un polemic debatte
comensa e it fini per un resolution in favor al propositor. On accepta
li proposition e refusa li contrapropositiones.

 

In li vestibules e corridores sta gruppes de persones, famosi
professores de universitás, rich directores de commercial firmas,
energic secretarios de social e professional organisationes, e militares
in gala-uniformes. Ili have portafolias con documentes e actes e
discusse li actual situation e international aferes.

 

[width="100%",cols="25%,25%,25%,25%",]
|===
|*afere* |affair |*ili* |they
|*ante li portas* |in front of the doors |*letion* |lesson
|*cité* |city |*scri* |write
|*con* |with |*visita* |visit (verb)
|*contra* |against  |*fa*  |do 
|*grand * |large  |*por * |for 
|*discusse* |discuss |*sala * |room 
|*escuta* |listen |*per * |through, by 
|*cruce * |cross  |*parla * |talks 
|*quam * |as  |*fascinant * |fascinating 
|*on vide* |one sees |*eloquentie* |eloquence
|*parte* |part |*residentie* |residence
|*propositor * |proposer  |*portafolies * |briefcases 
|*famosi * |famous  |*sta* |stand (verb)
|*fini* |finishes |*unesim* |first
|===

 

 

 

==== 1.1.2 Li macules in li sole

====  

Un yun monaco sede in un turre e observa interessat li sole tra un
telescope. Per hasard il fa un sensational observation: it existe
macules in li sole. Il hasta al prior del monastere e exclama:

„Patre, qui nu posse esser sin macules, nam mem li sole have macules.“

Ma li prior responde tranquilmen:

„Tu erra, mi filio. Yo ha leet Aristóteles multvez, de comensa till
fine, e necú il mentionapri macules in li sole. Tui ocules have macules,
e ne li sole.“

 

[cols=",,,,,",]
|===
|*monastere * |monastery  |*tranquilmen* |tranquilly  |*multvez * |many
times 

|*exclama*  |exclaims  |*nam*  |because  |*tu erra*  |you err (=are
wrong) 

|*patre * |father  |*mem*  |even  |*mi filio*  |my son 

|*yo ha leet*  |I have read  |*mentiona*  |mentions  |*esser*  |be 

|*responde* |responds |*tui ocul* |your eye |*macul* |spot

|*turre* |tower |*yun monaco* |young monk |*sede* |sits

|*hasta* |rushes (lit. hastes) |*tra* |through |*hasard* |chance
|===

 

 

==== 1.1.3 Aforismes

 

Genie es un percent inspiration e ninant nin percent transpiration.
(Edison.)

 

Li humore es un del elementes del genie, ma, si it dómina, solmen un
surrogat de it; it es li compane del diminuent arte e destructe, anihila
it in fine. (Goethe.)

 

Un bon comedie es plu durabil quam un systema de filosofie. (Hume.)

 

Grand artistes es li sol riches qui divide lor tot felicie con nos.
(Pauly.)

 

[cols=",,,,,",]
|===
|*ninant*  |ninety  |*compane* |companion |*diminuent*  |smaller,
diminishing 

|*nin*  |nine  |*divide*  |divide, share  |*plu durabil*  |more durable 

|*lor*  |their  |*si*  |if  |*quam*  |than 

|*tot*  |entire, whole  |*dómina*  |dominates  |*destructe* |destroys 

|*felicie* |happiness, fortune |*sol* |sole, only |*nos* |us
|===

 

=== 1.2 Explanation

 

Reading the first lesson, we find that the majority of words in
Occidental are already long familiar to us. That is, the vocabulary in
Occidental is largely composed of already-existing international words,
those that most countries in Europe (and of course countries in the
Americas, in Australia, African countries with European languages, etc.)
can already understand, and do not need to learn anew. These
international words are, as we can see through these examples, used in
an "unmutilated" form. But, - and this is what makes Occidental unique -
in the language they are not foreign loanwords, but entirely regularly
composed and derived from international root words, that have been
chosen in such a way that all these completely international and natural
words come into being by themselves. This has never been achieved before
in existing planned world languages.

 

The word-building system in Occidental is in fact the same one that is
found in international words, but as we will see later, can be easily
learned and mastered with the help of a few rules.

 

But it's not just the vocabulary of Occidental that is natural and easy
to learn; the grammar is also extremely easy thanks to its regularity.

 

==== 1.2.1 Article

 

* un congress - a congress
* un lampe - a lamp
* li congress - the congress
* li lampe - the lamp

 

There is no grammatical gender in Occidental. *Un* is the indefinite
article (a/an), and does not decline (change form). 

 

*Li* is the definite article (the), which also does not decline.

 

==== 1.2.2 Singular and plural

 

* genie - genius
* genies - geniuses
* congress - congress
* congresses - congresses
* lampe - lamp
* lampes - lamps
* suc - juice
* sucs - juices
* dictionnarium - dictionary
* dictionnariums - dictionaries 

 

Plural is formed with an -s, -es after a consonant. Some consonant
endings such as -g, -um, -c only add an -s for phonetic reasons.

 

==== 1.2.3 Cases

 

de un congress - of a congress

a un congress - to a congress

del congress - of the congress

al congress - to the congress

 

For the definite article (the), a + li is abbreviated to al and de + il
to del.

 

==== 1.2.4 Adjectives

====  

un modern automobil - a modern automobile

du modern automobiles - two modern automobiles

 

Adjectives in Occidental do not decline for gender, number or case.

 

==== 1.2.5 Persons

 

While verbs in English conjugate depending on the person and number,
they do not in Occidental.

 

[cols=",,,",]
|===
|*yo have*  |I have  |*yo es*  |I am 
|*tu have*  |you have  |*tu es*  |you are 
|*il have*  |he has  |*il es * |he is 
|*ella have*  |she has  |*essa es*  |she is 
|*it have*  |it has  |*it es*  |it es 
|*noi have*  |we have  |*noi es*  |we are 
|*vu have * |you (plural) have  |*vu es*  |you are 
|*Vu have * |you (polite) have  |*Vu es*  |you are 
|*ili have* |they have |*ili es* |they are
|*on have* |one has |*on es* |one is
|===

 

 

 

'''''

 

 

 

== 2 Duesim letion

 

=== 2.1 Texte

 

==== 2.1.1 Un dialog

====  

Un yun mann promena sur li trottuore de un strada e observa li vive. Il
incontra un amico, quel saluta le e strax comensa questionar:

"Bon die, mi amico. Quo Vu fa nu?"

"Yo promena."

"Quo Vu ha fat hodie? Yo ne ha videt Vos ante nu."

"Yo ha laborat."

"Quo Vu fat yer?"

"Yo esset in hem e reposat."

"Quo Vu hat fat anteyer, si Vu esset yer tam fatigat?"

"Yo hat laborat li tot die e nocte."

"Quo Vu va far deman?"

"Yo va scrir un long articul por un jurnal, e yo espera, que yo va har
scrit it till fine posdeman."

"Mey Vu haver success in Vor interprense! Ma it vell esser interessant
saver, pri quo Vu va scrir e por qui Vu va scrir."

"Ci noi ne posse star plu. Noi deve ear."

"Lass nos visitar un café! Ta noi posse seder e trincar un glass de bir
e parlar. O si Vu vole, café o té. Ples venir con me!"

"Mersí pro Vor invitation! Ma ples pardonar: pro quo Vu vole saver quo
yo fa, e pri quo e por qui yo scri?"

"Pro que un yun mann deve saver omnicos."

 

Note: hodie as a combination of ho+die is stressed as hodíe, and omnicos
as a combination of omni (all) + cose (thing) is stressed as omnicós. 
They may be also written as hodíe and omnicós.

 

[cols=",,,",]
|===
|*duesim * |second  |*ne * |not 
|*promena * |strolls (cf. promenade)  |*ante nu * |before now 
|*trottuor * |sidewalk  |*laborar * |work 
|*vive * |life  |*yer * |yesterday 
|*amico * |friend  |*reposar * |repose, rest 
|*le strax * |him right away  |*tam * |so 
|*bon die * |good day  |*fatigar * |tire 
|*quo * |what  |*nocte * |night 
|*questionar* |question, ask |*deman* |tomorrow
|*hodie* |today |*Vos* |you (object)
|*por* |for |*esperar* |hope
|*o* |or |*que* |that (as in "I hope *that*")
|*voler* |want |*posdeman* |the day after tomorrow
|*venir* |come |*mersí* |thanks
|*interprense* |endeavour |*pro* |due to
|*Vor* |your (polite form) |*saver* |know
|*pri quo* |about what |*pro quo* |why ("due to what")
|*ci* |here |*por qui* |for who(m)
|*plu* |more |*pro que* |because ("due to that")
|*dever* |must |*omnicos* |everything
|*ear* |go |*ta* |there
|===

 

 

==== 2.1.2 Li furtard e li prestro

 

Un furtard veni a un prestro por confesser su mult peccas e reciver
pardon e absolution. Li prestro sede in su stul e escuta benevolent,
durant que li furtard raconta le pri su trics.

"Quo tu ha fat, mi filio?" questiona li prestro. – In li sam moment li
furtard vide, que li prestro porta un fin aurin horloge in un tasca de
su gilete. Il prende it sin que li prestro remarca to.

"Yo furte," li furtard responde.

"Talmen tu ne deve dir. Ples dir, yo ha furtet!" – Nu li furtard ja ha
deposit li horloge in su tasca.

"Yo ha furtet," il confirma.

"Yes, bon, mi filio. Nu tu deve retornar to quo tu ha furtet."

"Esque Vu ne vole haver it?"

"No, tu deve dar it al possessor."

"Li possessor ne vole haver it."

"In tal casu, ples departer in pace. Tui peccas es pardonat."

 

[cols=",,,",]
|===
|*furtard*  |thief  |*sam * |same 
|*prestro*  |priest  |*portar*  |carry 
|*confesser*  |confess  |*su*  |his, hers, its 
|*mult*  |much  |*horloge*  |watch (wristwatch) 
|*fin* |fine |*aurin* |golden
|*pecca * |sin  |*tasca*  |pocket 
|*reciver*  |receive  |*gilete*  |vest 
|*prender*  |take  |*durant que*  |while 
|*furter*  |steal  |*racontar*  |tell 
|*remarcar to* |notice it |*talmen* |thus, in that way
|*dir* |say |*deposir* |put in / deposit
|*confirmar* |confirm |*retornar* |return
|*to* |it, that |*esque* |(asked to ask questions)
|*dar* |give |*possessor* |owner (possessor)
|*tal* |such a |*casu* |case
|*pace* |peace |*tui* |your (informal)
|===

 

 

==== 2.1.3 Anecdotes

 

Li persian legates postulat del Spartanes terra e aqua quam signe de
subjugation. Li Spartanes jettat les in un profund bronn: "Ta vu have
terra e aqua."

 

Zeno, li filosofo, dit a un querellant yun mann: "Li natura ha dat nos
du oreles e un bocca, por que noi mey escutar mult e parlar poc."

 

"Si yo va venir a Laconia, yo va extinter omnicos e omnihom per foy e
gladie," scrit Philippos, li rey de Macedonia, al Spartanes. "Si,"
respondet li Spartanes.

 

Un asiatic potentate esset questionat, quel esset su opinion pri li vin.
Il respondet: "It es un fluide, quel es extraet de lingues de féminas e
cordies de leones, pro que, quande yo ha trincat vin, yo posse parlar
sin cessar e combatter mem li diábol."

 

[cols=",,,",]
|===
|*postular*  + |demand  + |*terra e aqua * + |earth and water  +
|*jettar* |throw, toss  + |*profund* + |deep  +
|*querellar*  + |quarrel  + |*orel*  + |ear  +
|*bocca*  + |mouth  + |*por que*  + |in order to ("for that")  +
|*poc*  + |little  + |*extinter*  + |extinguish  +
|*omnihom*  + |everyone  + |*foy*  + |fire  +
|*gladie*  + |sword  + |*quel*  + |which  +
|*vin*  + |wine  + |*fluide*  + |fluid  +
|*fémina* |woman |*cordie* |heart
|*cessar* |stop |*combatter* |combat
|*leon* |lion |*diábol* |devil
|===

 

 

==== 2.1.4 Proverbies

 

* Mannes fa domes, ma féminas fa hemes.
* Li infante es li patre del mann.
* Plu vu studia, plu vu trova, que vu save necos.
* Aure dat por sanitá, ne es dat in vanitá.
* On ne posse seder sur du stules.
* Errar es homan, pardonar divin.
* Parlar es plu facil quam far.
* Quande li fox predica tolerantie, ples gardar vor ganses.
* Sur un rulant petre moss ne cresce.
* Li morites governa li viventes.
* Bon comensat es demí parat.
* Que sempre es comensant, nequande es finient.
* Mult homes es vocat, ma poc homes es electet.
* Li sapon es li mesura de bon-esser e cultura del state.

 

[cols=",,,",]
|===
|*proverbie * + |proverb  + |*dom * + |house  +
|*hem * + |home  + |*infante * + |infant, child  +
|*trovar * + |find  + |*necos * + |nothing  +
|*aure * + |gold  + |*sanitá * + |health  +
|*in vanitá * + |in vain  + |*du * + |two  +
|*homan * + |human  + |*divin * + |divine  +
|*facil * + |easy  + |*quande * + |when  +
|*predicar * + |preach  + |*gardar * + |guard  +
|*rular* |roll |*petre* |stone
|*crescer* |grow |*morir* |die
|*parat* |done |*sempre* |always
|*nequande* |never |*vocar* |call
|*hom* |person |*sapon* |soap
|===

 

 

=== 2.2 Explanations

 

2.2.1 Conjugation

 

Verbs in Occidental are all regular (except for the verb to be (*esser*)
which is written *es* in the present). There is only one conjugation
with four forms. Taking the verbal stem ama- (love) as as example we
have the following four forms:

 

{empty}1. ama

{empty}2. ama**r**

{empty}3. ama**nt**

{empty}4. ama**t**

 

1. **ama **has the following uses:

 

{empty}a) Active present indicative (regular present form): *yo ama* = I
love, *il ama* = he loves, *vu ama* = you love, etc.

{empty}b) Active present conjunctive: *Il di que il ama* = He says that
he loves

{empty}c) Imperative: *ama*! = love! *veni*! = come!

 

2. **amar **is the infinitive. **amar **= to love, **venir **= to
come, **presser **= to press.

 

3. **amant **is the active participle (English -ing). **amant **=
loving, **venient **= coming, pressent = *pressing*

 

4. **amat **has the following uses:

 

{empty}a) Perfect participle (i.e. an adjective): **amat **=
loved, **venit **= come, **presset **= pressed. *Li amat patria* = the
(be)loved homeland.

{empty}b) Active indicative preterite (i.e. past tense): *yo amat* = I
loved, *tu amat* = you loved, *il amat* = he loved, *noi amat* = we
loved, *ili amat su patria* = they loved their homeland, etc.

 

The other forms are created with the help of auxiliary verbs.

 

Active:

 

[cols=",,",]
|===
|Perfect  + |*yo ha amat*  + |I have loved  +
|Pluperfect  + |*yo hat amat*  + |I had loved  +
|Future I  + |*yo va amar*  + |I will love  +
|Future II  + |*yo va har amat*  + |I will have loved  +
|Optative  + |*yo mey amar*  + |I may love  +
|Conditional  + |*yo vell amar*  + |I would love  +
|Precative  + |*ples amar!*  + |please love!  +
|Hortative  + |*lass nos amar!*  + |let us love!  +
|Perfect infinitive |*har amat* |to have loved
|Future infinitive |*va amar* |to will love
|Perfect participle |*hant amat* |having loved
|Future participle |*vant amar* |having to love
|===

 

1. *har* resembles *haver* (to have) but is used for verb conjugation,
while *haver* only refers to the verb to have. *yo ha venit* = I have
come, *il ha esset* = he has been, *noi hat curret* = we had run, *il
hat cadet* = he had fallen.

 

2. **ples **in* ples amar* adds politeness to the imperative, in the
same way as the English please. *ples venir!* = please come! *veni*! =
Come!

 

Passive

 

[cols=",,",]
|===
|Present  + |*yo es amat * + |I am loved  +
|Preterite  + |*yo esset amat * + |I was loved  +
|Perfect  + |*yo ha esset amat*  + |I have been loved  +
|Pluperfect  + |*yo hat esset amat*  + |I had been loved  +
|Future I  + |*yo va esser amat*  + |I will be loved  +
|Optative + |*yo mey esser amat*  + |may I be loved  +
|Conditional  + |*yo vell esser amat*  + |I would be loved  +
|Present infinitive  + |*esser amat*  + |to be loved  +
|Perfect infinitive |*har esset amat* |having been loved
|Present participle |*essent amat* |being loved
|===

 

Other forms

 

{empty}1. Using the verb *ear *(to go): *Li dom ea constructet* = the
house is being built. Using *ear* adds a sense of continuation (the
construction is going on). *Li libre eat printat* = the book was being
printed.

 

{empty}2. Using the verb *star *(to stand): *Li dom sta constructet* =
the house is built. Using star adds a sense of finality (the house
"stands" built). *Li libre stat printat* = the book was printed (the
book's printing was all done).

 

{empty}3. Using **se **after a verb to make it passive or reflexive (to
make it refer to itself). *Li jurnal printa se rapidmen* = the magazine
is being quickly printed (the magazine "prints itself" quickly). *Li
cose explica se simplicmen* = it's easy to understand ("the thing
explains itself simply"). *Yo nómina le Brian* (I call him Brian), *il
nómina se Brian* (his name is Brian = "he calls himself Brian").
Adding *se* to a verb may also give a sense similar to that in
English: *Yo procurat un libre* = I got a book; *Yo procurat me un
libre* = I got myself (me) a book.

 

*Progressive form:*

 

[cols=",,",]
|===
|Present  + |*il es laborant*  + |he is working  +
|Preterite  + |*il esset laborant*  + |he was working  +
|Perfect  + |*il ha esset laborant*  + |he has been working  +
|===

 

The progressive form is used much less often than in English, and is
used to stress the fact that the action is ongoing.

 

*Il esset laborant quande yo intrat.* = he was working when I entered.

 

It works as an adjective in the same way as in English:

 

*It va esser un tre fatigant annu.* = It will be a very tiring year
(from *fatigar*, to tire)

 
